### ISSUE TITLE
Chapters on Meteor for Mobile

### ISSUE THREAD

**Issue by cdcv** [meteor/guide#100]
Would like to recommend that the Meteor guide include three additional chapters: 
Creating a Meteor Mobile App (issues like choosing an appropriate framework, Cordova, etc).
Building a Meteor Android App (issues like mobile config, getting it to the device, simulator testing, build, code signing, etc).
Building a Meteor iOS App (as above plus XCode-related issues).

One of the principle reasons to use Meteor is cross-platform compatibility. This is also one of the main areas where time is spent.  I strongly urge the creation of material on this.  I suspect that these chapters will be some of the most widely used in the end.  Once someone has long-ago forgotten learning Meteor basics, they still need to stay up to date on the latest tweaks required to get apps to run in mobile environments.  This is critical for everyone from first-time-app-builders to senior developers (who in my experience still end up having to do a lot of research as part of getting a new app to publish given how quickly all of the tools change).

Also, I'd like to suggest that sample 'real' mobile apps, with all the required bits and pieces required of an actual production-quality app, be provided.

**Comment by stubailo** [comment]
This is the one you're looking for: https://github.com/meteor/guide/issues/40
