### ISSUE TITLE
Section 6 - Running on Mobile - 404

### ISSUE THREAD

**Issue by LaughingBubba** [meteor/guide#1038]
In this section the reader is asked to install the iOS and Android SDK's.

However, the SDK doesn't install and the reader is asked follow a link.
```
$> meteor install-sdk ios
Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites
```

Unfortunately the link 404's out.

This is the offending link: [http://guide.meteor.com/mobile.html#installing-prerequisites](http://guide.meteor.com/mobile.html#installing-prerequisites)

**Comment by coagmano** [comment]
I think `mobile` got changed to `cordova` at some point:
https://guide.meteor.com/cordova.html#installing-prerequisites

Feel free to make a PR fixing the links

**Comment by filipenevola** [comment]
I have fixed already, it will be updated in the next release.
