### ISSUE TITLE
Remove or improve the part about crosswalk

### ISSUE THREAD

**Issue by namenotrequired** [meteor/guide#1047]
I mean this section: https://guide.meteor.com/cordova.html#what-environment -> Android

This section is mostly about Crosswalk. As far as I can tell,

- Android 4.4 and below have very small market share in 2020
- The two links to pages on crosswalk-project.org redirect to an unrelated website which is confusing
- Talking about it as a "plugin" is confusing, because people come to this same article to see how to install cordova plugins. But this "plugin" it is installed as a package. People see the code example (`meteor add crosswalk`) and think that's how you install cordova plugins.

Can we remove this section, or is crosswalk still relevant in 2020?

If it is, can we clarify the confusion?

**Comment by lorensr** [comment]
I'm fine removing

**Comment by filipenevola** [comment]
Yes, please remove @namenotrequired

**Comment by namenotrequired** [comment]
Done: https://github.com/meteor/guide/pull/1049
