### ISSUE TITLE
Triggering Actions [BLAZE]

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/guide#106]
I think a part of the guide should talk about how we do our client side Business Logic. My opinion is to create modular functions that are called from template events. If you look at most Meteor code, events have tons of stuff going on. I'd like to adopt a pattern we use at Workpop called the "Action Creator" pattern. What we've done is created a Global Object that can be instantiated with mixins.

Heres an example:

```
var incrementer = function (store){
  return store.set(store.get() + 1);
}

// then we register this to a global 
ActionMixins.registerMixin('incrementer', {
   incrementer: incrementer
}
```

With actual modules this becomes irrelevant sadly, but has worked for us in the short term.

Lets get into template code for a sec

```
Template.incrementModule.onCreated(function () {
// now my template instance has a shared reference to the incrementer function and
//  any other function decided to include as part of the incrementer
  this.actionCreator = new ActionCreator(['incrementer']);
  this.incrementStore = new ReactiveVar(0);
});

Template.incrementModule.events({
   'click .ev-up': function (event, template) {
      var incrementStore = template.incrementStore;
      return template.actionCreator.incrementer(incrementStore)
   }
});
```

Okay cool. so now my template logic is clean as hell. and i actually can test my UI Business Logic without hooking into template events.

This pattern was pseudo copied from Reflux. But im starting to think if I had module support and I used Blaze, id probably just have modules instead of this shit.

Let me know. Also I'm not sure this was the right place to post this?

**Comment by tmeasday** [comment]
Hey @abhiaiyer91,

That's interesting, although I wonder if it's a little more overkill than is strictly needed. Is the idea that you can then write tests against the `incrementer` mixin in isolation?

In the guide we were going to advocate a simple approach that looks like:

```jsTemplate.incrementModule.onCreated(function () {
  this.increment = () => {
    ...
  }
});

Template.incrementModule.events({
   'click .ev-up': function (event, instance) {
      instance.increment();
   }
});
```

Then you can write unit tests against the template, and avoid event handlers by just calling `instance.increment()` directly. You could either inspect the rendered output of the template or assert against the state vars of the instance.

I agree that your approach is great if you start really abstracting behaviours of templates and wanting to share them between templates however. I'm just not sure I'd recommend doing it from the beginning (i.e. before that behaviour needs to be shared).

**Comment by abhiaiyer91** [comment]
@tmeasday So here's the story.

In our app we can Hire, Decline, Message people from 4 different views. And the Views themselves had different styles, and structurally were different components with different states etc. That was the design. So one day we woke up and were like, WELL we have duplicated this code 4 ways and when we fix a bug in it, now we have 4 places to update. It was hell. The birth of the pattern I described came out of realizing that those these components were different and looked different they shared similar "actions". 

It wasn't till after we implemented the pattern we realized, "Damn now we can test these in isolation" without hassle! 

I agree that doing this in the beginning is super overkill, especially if you don't know what your app looks like yet...but I think it was our saving grace in a tough time. We now use this everywhere in our app. We have mixins per feature that are shared between components, e.g. the message feature has messaging mixins. But we also have global mixins like, "analytics events, key detection for keyup/keydown events" etc etc.

Thanks for listening to me :)

**Comment by tmeasday** [comment]
Yeah it makes perfect sense. I would hazard a guess that although it's not uncommon, it's not something every app needs to do so I'd be inclined to leave it out (at least of this current iteration) of the guide.

But I definitely think a lot of people would get value from it if you blogged about it! It's very Reacty again of course ;)

**Comment by abhiaiyer91** [comment]
Great! I'll do just that!
