### ISSUE TITLE
Can't use Tailwind CSS v2.0 because postcss@^8.0.9 is not supported by juliancwirko:postcss

### ISSUE THREAD

**Issue by Tombiliby** [meteor/guide#1065]
Hi everybody,

I don't find the solution to use tailwind css v2.0, the juliancwirko: postcss module does not support postcss version above 6.0.22. Tailwind css works with PostCSS 8

I haven't found it but is there already a topic about it?

**Comment by StorytellerCZ** [comment]
Not to my knowledge, but this should be brought up in the package repository.
