### ISSUE TITLE
Add page last updated date?

### ISSUE THREAD

**Issue by quangv** [meteor/guide#1066]
First time reading the guides, kind of feels dated, the way it talks about ES2015 like it's new...

Was thinking maybe it'll be good to post (if possible) the last updated date of the page?

Or maybe the last version of Meteor the page applied to.

🤔 maybe the guides would benefit from having version numbers, perhaps align with Meteor releases?

----

Edited: Oh guess it already has version numbers! I still think there might be a benefit from adding a last updated date. Technology / technology recommendations changes so often, that it's good to know _when_ I'm reading. For example I'm just glossing over the Blaze stuff, in favor of React.

**Comment by filipenevola** [comment]
@quangv thanks for your suggestion.

We are going to update many things in the guide in the next weeks.

If you found specific places were the information is out-dated please open specific issues so we can fix asap.
