### ISSUE TITLE
angular is not supported

### ISSUE THREAD

**Issue by mibto** [meteor/guide#1069]
Hi
In the official docs it says that angular is supported by meteor but this is not true anymore. Please remove it from:
https://guide.meteor.com/ui-ux.html#view-layers

Thanks,
Michael

**Comment by filipenevola** [comment]
Hi @mibto, were you using Angular with Meteor and is it not working for you anymore?

We do need to update our guide, specially this part about view layers but I would like to understand more your point here on Angular.

**Comment by mibto** [comment]
Hi @filipenevola 

Well the last update to the project of Urigo is 3 years ago and it has several issues of breaking with current Angular / Meteor versions. There is no nice basic setup to start from. for me is this project dead and should not be advertised in the meteor docs

**Comment by filipenevola** [comment]
Hey, the community has updated Angular integration, see the tweet for more details https://twitter.com/meteorjs/status/1367507774133981192
