### ISSUE TITLE
Call Helper From View

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/guide#107]
Alright here's the situation. Have you guys ever written helpers that are not very DRY?

Heres an example

```
Template.example.helpers({
   'helper1': function () {
      var abhiArray = Abhi.find({}, {fields: {'foo': bar});
      return _.map(abhiArray, function (coolestPersonEver) {
          // do some work
      });
   },
  'helper2': function () {
       var abhiArray = Abhi.find({}, {fields: {'foo': bar});
      // do something else
   }
});
```

.Now there are work arounds for this. 

1. You can bind it to the template instance if your subscription is ready from the parent
2. You can return one helper as an object and utilize all the different things you want to do...

or you can do something interesting which maybe shouldnt be in the guide..

What I do sometimes in situations that I may not be able to bind something to the `template instance`, or i want to use the value of a hepler in lets say `onRendered` is ofcourse hack the view :)

```
Blaze.callHelperFromView = function (helper) {
  return Template.instance().view.template.__helpers[' ' + helper]();
};
```

So my above example could turn into

```
Template.example.helpers({
  'getAbhi': function () {
    return Abhi.find({}, {fields: {'foo': bar});
   },
   'helper1': function () {
      var abhiArray = Blaze.callHelperFromView('getAbhi');
      return _.map(abhiArray, function (coolestPersonEver) {
          // do some work
      });
   },
  'helper2': function () {
      var abhiArray = Blaze.callHelperFromView('getAbhi');
      // do something else
   }
});

Template.example.onRendered(function () {
       var abhiArray = Blaze.callHelperFromView('getAbhi');
      // do something

});
```

Idk, this isn't really straight forward at all. Whats the best practice in this situation? How do we inform people what that is via the guide?

**Comment by tmeasday** [comment]
Hey @abhiaiyer91,

I think the pattern of attaching methods to the template instance (https://github.com/meteor/guide/blob/master/content/blaze.md#attach-functions-to-the-instance) solves the problems you'd use this for, and is a bit simpler to understand than using Blaze in this way.

What do you think?

**Comment by abhiaiyer91** [comment]
I agree. With the exception of a reactive data source you wanna share? or would you just `autorun` in `onCreated`?

**Comment by tmeasday** [comment]
I mean if it's a reactive data source and you end up calling it from a helper, it still works, I think?

As in, this will work fine:

```js
Template.foo.onCreated(() => {
  this.getData = () {
    return Data.find();
  };
});

Template.foo.helpers({
  data() {
    return Template.instance().getData();
  }
});
```

**Comment by abhiaiyer91** [comment]
hahaha duh! youre right. great
