### ISSUE TITLE
missing meteor test --drive-package information

### ISSUE THREAD

**Issue by joaozitopolo** [meteor/guide#1084]
It's not clear how to fill the parameter --drive-package for meteor tests.
There are two examples, but without the drive name, and the meteor test --help has no reference for that.

**Comment by filipenevola** [comment]
Hi @joaozitopolo, I see a few examples where we show the driver name, like [here](https://guide.meteor.com/testing.html#running-unit-tests) 

Could you clarify where do you think is it missing?

**Comment by joaozitopolo** [comment]
Thanks Filipe.
The first time this term appears is [here](https://guide.meteor.com/testing.html#driver-packages), but only in a distant example I'll have one item from that domain allowed.
I think when you are looking the documentation, you'll try to run commands from that block. Ask someone to read until this part I referenced, and ask him/her what is necessary to fill the drive-package option.
Another thing: there are no help about this on CLI command.
(It's an improvement for meteor, not a complain :smile: )

**Comment by filipenevola** [comment]
Hi @joaozitopolo, I understand your concern but it makes sense to first explain what is a driver package and [later](https://guide.meteor.com/testing.html#running-unit-tests) explain how to run this command.

About the help in the CLI, we have [this part ](https://github.com/meteor/meteor/blob/a919b513b9ef55db4a01f7ff30f100822ba8f7db/tools/cli/help.txt#L658-L659) in the help.

If you think this is not enough please open a PR suggesting changes there. We will be glad to review.
