### ISSUE TITLE
Cut and pasting includes line numbers

### ISSUE THREAD

**Issue by zol** [meteor/guide#113]
It would be nice if you could cut and paste from the example code directly into your editor. Currently, you also get the line numbers, like:

```
1
2
3
4
5
Lists.schema = new SimpleSchema({
  name: {type: String},
  incompleteCount: {type: Number, defaultValue: 0},
  userId: {type: String, regEx: SimpleSchema.RegEx.Id, optional: true}
});
```

**Comment by yyx990803** [comment]
It seems to work fine for me as long as you don't select the line numbers.

**Comment by zol** [comment]
Ahh, I see great, thanks. Closing this out.

**Comment by stubailo** [comment]
In the tutorial we used CSS to make the numbers not selectable. Could we do that here as well?

See an example: https://www.meteor.com/tutorials/blaze/collections
