### ISSUE TITLE
Add SEO

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#115]
I'm not really sure where it would go - deployment? What do you think, @tmeasday?

**Comment by arunoda** [comment]
* Google bots and render the app, but cannot connect to DDP. So, it's crucial to have FastRender
* There are some packages we can use manipulate document.head for social tags - This is our package - https://github.com/kadirahq/meteor-dochead (but there are also many packages like this)
* twitter does not use Google's deprecated AJAX SEO protocol. So it's crucial to do SSR. 
* Our dochead works great with SSR as well.

**Comment by tmeasday** [comment]
Yeah, probably deployment. I think it should go in the "production" section that we discussed earlier.

**Comment by tmeasday** [comment]
I did *something* in here: https://github.com/meteor/guide/pull/109, specifically https://github.com/meteor/guide/commit/5986a0ae77c0bd6ae51df908de2e1c988a99910d

@stubailo do you want to do discuss it here or on the PR? If there, close this issue

**Comment by stubailo** [comment]
There.
