### ISSUE TITLE
Template render error because of {{

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#119]
How do we get around this? I guess in the worst case we could escape all occurrences of this, but there sure are a lot of them with Spacebars...

Tagging @yyx990803 because you probably know what the best solution is.

**Comment by yyx990803** [comment]
Current solution: wrap code blocks inside `{% raw %} ... {% endraw %}`. I'll see if I can write a hexo plugin to do that automatically.

**Comment by stubailo** [comment]
For some reason, if I use that technique the page actually renders, but you can see the raw tags in the code snippet.

Also, I've narrowed the problem down specifically to `{{#`.

**Comment by yyx990803** [comment]
Closed via a359df561caaef95adef5f96aa4e6359b72fc5a9
