### ISSUE TITLE
Methods

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#120]
### Article outline

https://github.com/meteor/guide/pull/121

### Major decision points

1. We're going to introduce a wrapper package for methods: https://github.com/meteor/method
  1. Simpler argument validation with `simple-schema`
  2. Better defaults
  3. Easier mocking and testing
  4. Standardized validation error format: https://github.com/meteor/validation-error

**Comment by PhilippSpo** [comment]
In _Advanced Method boilerplate_ in the _Defining_ section there is an error in the code example in the `call` method:
```js
Meteor.apply(this.name, [args], options, callback);
```
should be:
```js
Meteor.call.apply(this.name, [args], options, callback);
```

**Comment by stubailo** [comment]
Are you sure? Meteor.apply is actually a valid API function.

**Comment by PhilippSpo** [comment]
OK didn't know that! What is it supposed to do then? Sorry if I miss something obvious here.

**Comment by PhilippSpo** [comment]
Ah I see.

**Comment by stubailo** [comment]
The situation is actually exacerbated because the (undocumented) options we are passing can _only_ be passed to `Meteor.apply`, and not `Meteor.call`. Just one of the reasons I now just use the `ValidatedMethod` wrapper and don't think about it anymore.

**Comment by PhilippSpo** [comment]
Yes I also noticed that when reading in the docs about `Meteor.apply` (I probably should look into the docs more often). I really love the idea of having the `ValidatedMethod` wrapper that handles this for me. Also being able to just call JavaScript methods instead of the Method call with magic strings is great!
Btw. the docs always use the `check` function to validate Method arguments.. Is there any reason to still use `check` in favour of `SimpleSchema`?

**Comment by lorensr** [comment]
@stubailo I'm also curious why you chose the first over the second?

```
validate: new SimpleSchema({
    todoId: { type: String },
    newText: { type: String }
  }).validator(),
```

```
validate({ todoId, newText }) {
  check(todoId, String);
  check(newText, String);
},
```

**Comment by stubailo** [comment]
Three reasons:

1. Avoid having two different ways to check types
2. Reuse db schema in method args
3. This throws formatted validation errors, which can be inspected on the client - check throws opaque errors with no info.

If you want to discuss further I'd suggest doing it on the article forum thread or a new issue, though, instead of this closed issue: https://forums.meteor.com/t/meteor-guide-methods/19662

**Comment by lorensr** [comment]
Makes sense, thank you!
