### ISSUE TITLE
can't find mdg:cursor-utils

### ISSUE THREAD

**Issue by roelvan** [meteor/guide#130]
In http://guide.meteor.com/collections.html a package named `mdg:cursor-utils` is mentioned at the end. But I cannot find it anywhere (atmosphere, `meteor add mdg:cursor-utils`). If it does not exist we should remove it form the docs or add a link to where we can find it.

**Comment by stubailo** [comment]
Here's the issue to track: #73 

The guide is still a work in progress, so not everything is guaranteed to work right now.
