### ISSUE TITLE
Recommend using subs-manager

### ISSUE THREAD

**Issue by elie222** [meteor/guide#131]
I was just reading through this page: https://github.com/meteor/guide/blob/master/content/data-loading.md

It seems to me that a better practice would be to use the `meteorhacks:subs-manager` for subscriptions. This would be mean not using `this.subscribe()` in templates since this doesn't work with subsmanager.

The advantage to using subs-manager is to not constantly resubscribe to the same data. If a user goes from `posts` to `post/1` to `posts` it's a shame to reload all the posts again. This is a common occurrence in apps and not using subsmanager leads to a much slower app, sending more data over the wire, and extra load on the servers.

**Comment by artisin** [comment]
If this is to be added, I would recommend we recommend using [subs-cache](https://github.com/ccorcos/meteor-subs-cache) it gives a little extra but much need control over how the subs are cached.

**Comment by elie222** [comment]
Good point

**Comment by SachaG** [comment]
+1 for using subs-manager or something similar. It's required for any application that does granular subscription management, imo.

**Comment by lorensr** [comment]
Also for this section:

http://guide.meteor.com/ui-ux.html#subscription-readiness

A better UX would be for the data to already be there. I mostly do global subs at pageload myself – is there a pattern for early subscribing to some smart template subs, and for sometimes keeping the data around when the templates are destroyed?

**Comment by tmeasday** [comment]
I would subscribe to the pub somewhere higher in the component hierarchy -- a layout component which is always there (it doesn't need to involve any UI if there is no common UI).
