### ISSUE TITLE
Bold title text in navigation?

### ISSUE THREAD

**Issue by dburles** [meteor/guide#137]
I think it helps the eye a little, here's how it could look:

<img width="266" alt="screen shot 2015-12-04 at 10 12 38 am" src="https://cloud.githubusercontent.com/assets/319567/11644629/b8b3fdba-9da1-11e5-8961-ee6ed8957c5e.png">

**Comment by stubailo** [comment]
Ooh, I like it. @tmeasday? I bet there is something more pretty we could do eventually, but this is certainly an improvement.

**Comment by tmeasday** [comment]
LGTM!
