### ISSUE TITLE
Other things that could be mentioned in "Method call lifecycle"

### ISSUE THREAD

**Issue by glasser** [meteor/guide#147]
I'm looking at http://guide.meteor.com/methods.html#Method_call_lifecycle and it all looks accurate to me.

There may be other details worth mentioning (or perhaps not):
- [x] stubs: what happens with their return value (or error if thrown)?  the answer is basically "nothing, unless you pass an undocumented returnStubValue option" I believe
- [x] what does Meteor.call actually return?  The answer is different in browser vs Node.  (I think on the client "nothing, unless returnStubValue is set"; in Node, it uses Fibers to return the value from the (remote) server... unless there's a callback passed?  or maybe even if there is? who knows)
- [x] "wait" methods.  A special client-only option that means "don't call this method overlapping with any other method" (and also apply some extra rules around optimistic UI "quiescence")
- [x] The fact that publications sent down in Step 5 ​*are not applied*​ to documents touched by the method in minimongo until Step 6 (this is actually kinda important and subtle)
- [x] The "In this case" clause in Step 5 appears to be referring to an example that isn't mentioned anywhere else in this whole "advanced concepts" section.  Maybe use the example more consistently throughout the set up steps?

[sashko: made checklist, checking off as I go]

**Comment by stubailo** [comment]
OK I need to do an experiment to determine:

1. What happens if `returnStubValue` is passed in a server-side method call - do you not get the remote return value anymore?
2. If you pass a callback to Meteor.call on the server, do you still get the return value? I'd guess yes.

@glasser do you remember - was there any particular use case for the `wait` option? Is there anywhere I could read about the rationale behind adding it?

**Comment by glasser** [comment]
`wait` is used by login methods.  The idea was that running login (changing user ID) at the same time as any other method is confusing, so this is a (client-side!) mechanism for "preventing" that.

I think this was an @avital and @n1mmy design from right before I joined.

**Comment by avital** [comment]
It was a @gschmidt design :)

**Comment by avital** [comment]
It was to ensure that methods are executed in a reliable user context that's not dependent on when each method finished executing.

**Comment by glasser** [comment]
Sure, I understand that; I'm not sure I ever understood why this wasn't a server-side decision, though (eg, a primitive on the server that you can use to block until any other unblocked simultaneous method bodies are done), perhaps in addition to client-side.

**Comment by stubailo** [comment]
I'm still not completely clear on what it does - how does it compare to just not calling `unblock`? And we're just talking about methods from the same user, right, not all methods on the server.

**Comment by stubailo** [comment]
Never mind, I got it. Hopefully this is good: ac5791a8f007b323967beb4e54f73f097b062766
