### ISSUE TITLE
Minor inaccuracies in SSL security section

### ISSUE THREAD

**Issue by glasser** [meteor/guide#148]
> Yes, Meteor does hash your password on the client before sending it over the wire, but hashing a password in this way provides only minimal security, and someone who intercepts that sent password will be able to, with time, decode it into the actual password. That’s why passwords in the database are salted - a random string is appended to the password before hashing. It is not possible to do this on the client, so the passwords sent over the wire are not secure even though they are hashed. The only way to secure that transfer is by using SSL.

So, background: the thing we send over the network is `SHA256(actual password)`, and the thing we store in the DB is `bcrypt(SHA256(actual password))`.  SHA256 is not a salted algorithm (it produces the same output for each input); bcrypt is.

"someone who intercepts that sent password will be able to, with time, decode it" is not true.  If you've chosen a suitably random password `p`, one should not be able to go from `SHA256(p)` to your password `p`.  ie, yes, if your password is a common one then it can be recognized from a rainbow table or just by trying all the common ones, but if your password is essentially a random string then nobody is going to be able to figure it out only knowing its SHA256.

The issue here isn't "if somebody knows `SHA256(p)`, they will be able to derive `p`".  It's that ​*the only thing you need to log in is `SHA256(p)`*​.  ie, if somebody sees your login message, then they can just replay it and log in as you, end of story.  No need to decode anything.

Salting is important and it's what protects you against "I stole the database and then just compared what i saw there against precalculated tables to instantly figure out what the passwords are" (instead, you have to actually try to run your guessed password through bcrypt with the same salt to check).  But it's not why SSL is important here.

Moreover: this isn't just a weakness of accounts-password.  accounts-base itself has it just as bad, with "resume tokens", so this ends up affecting OAuth users too.  The "resume token" which is sent with every new DDP connection once you're logged in is effectively yet another password that gives full access to your account.  It is possible to make them expire over time (or explicitly expire all outstanding tokens) but in practice, if you can eavesdrop on somebody's connection ​*no matter whether they used password or oauth*​, you can use the resume token to get into their account.

(Of course, everything above is true of most common mechanisms to authenticate to web apps.  Substitute "cookie" for "resume token" above...)

The overall point (use SSL!!!) is totally valid though.

**Comment by glasser** [comment]
I was thinking of closing https://github.com/meteor/meteor/issues/4363 now that the guide entry exists, though maybe not until the above is resolved.

**Comment by stubailo** [comment]
Yep, we have it in our todo list for this week. Thank you for the incredibly detailed write-up. This is exactly the kind of stuff we should be getting right in the guide.
