### ISSUE TITLE
"Welcome!" probably shouldn't be the 6th article in the sidebar

### ISSUE THREAD

**Issue by glasser** [meteor/guide#149]
When I look at http://guide.meteor.com/ I see that "Welcome!" is the 6th article.  I suspect it should be the first.

**Comment by jessenorton** [comment]
Yeah, I found that confusing too. Also it would be good if the navigation subcategories collapsed, as well as expanding.

**Comment by stubailo** [comment]
Yes we haven't decided on the order yet - once we do well organize everything. Thanks for recording it in an issue!
