### ISSUE TITLE
Setting up Lists.deny is invalid json 

### ISSUE THREAD

**Issue by craigbennett1981** [meteor/guide#155]
In the security guide 

Lists.deny({
  insert() { return true },
  update() { return true },
  remove() { return true },
});

should probably be ...

Lists.deny({
  insert: function() { return true },
  update: function() { return true },
  remove: function() { return true },
});

**Comment by dburles** [comment]
Hey @craigbennett1981 it's es2015! https://babeljs.io/docs/learn-es2015/

**Comment by craigbennett1981** [comment]
Thanks @dburles, it seems I am a bit behind the times ;)
