### ISSUE TITLE
Get feedback about accounts article from splendido

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#165]
@splendido, can you take a look at the accounts article? Interested to know what you think.

http://guide.meteor.com/accounts.html

**Comment by splendido** [comment]
I'll try to have a look at it tonight (starting 4 hours from now ;-) )!

**Comment by splendido** [comment]
Done: I'd say you've done a great job!

Besides my comments you've already saw, at the moment there's nothing else about the content jumping to my mind: in case I'll let you know after reasoning a bit more about it.

tnx!

**Comment by stubailo** [comment]
Awesome! Thanks for the great work on the accounts packages.

**Comment by splendido** [comment]
My pleasure!
