### ISSUE TITLE
Recommended packages index

### ISSUE THREAD

**Issue by Mardaneus86** [meteor/guide#180]
The articles so far are great to read. The articles recommend a fair amount of packages along the way, so I think it would be nice to see an index of all those recommendations. Possibly linking to the places they are mentioned.

Having to go through the guide and find all places where specific packages are mentioned (sometimes pretty obfuscated) is quite a hassle. Having an overview as a reference would be helpful.

I guess this could be automated easily by parsing all markdown files and scan for `atmospherejs.com` references.

**Comment by stubailo** [comment]
> I guess this could be automated easily by parsing all markdown files and scan for atmospherejs.com references.

Ooh, I really like this idea. Also, this index will be very helpful if we want to run additional tests on those packages to make sure they all work together well.

I guess this would run as part of CI somehow, I wonder where it would put the data - perhaps just in a JSON file at the root of the site that can be easily downloaded?

**Comment by stubailo** [comment]
This command seems to work:

```
grep -roh 'atmospherejs.com/[a-z]*/[0-9a-z-]*' content/ | sort
```

Returns:

```
atmospherejs.com/alanning/roles
atmospherejs.com/alanning/roles
atmospherejs.com/aldeed/collection2
atmospherejs.com/aldeed/simple-schema
atmospherejs.com/aldeed/simple-schema
atmospherejs.com/dburles/collection-helpers
atmospherejs.com/dfischer/prerenderio
atmospherejs.com/fourseven/scss
atmospherejs.com/juliancwirko/postcss
atmospherejs.com/kadira/blaze-layout
atmospherejs.com/kadira/dochead
atmospherejs.com/kadira/flow-router
atmospherejs.com/mdg/validation-error
atmospherejs.com/mdg/validation-error
atmospherejs.com/meteor/blaze-html-templates
atmospherejs.com/meteor/less
atmospherejs.com/meteor/reactive-dict
atmospherejs.com/meteor/stylus
atmospherejs.com/meteorhacks/npm
atmospherejs.com/mquandalle/jade
atmospherejs.com/nimble/restivus
atmospherejs.com/okgrow/analytics
atmospherejs.com/okgrow/analytics
atmospherejs.com/peerlibrary/computed-field
atmospherejs.com/percolate/find-from-publication
atmospherejs.com/percolate/migrations
atmospherejs.com/percolate/migrations
atmospherejs.com/percolate/momentum
atmospherejs.com/reywood/publish-composite
atmospherejs.com/simple/rest
atmospherejs.com/simple/rest
atmospherejs.com/tap/i18n
atmospherejs.com/tmeasday/publish-counts
atmospherejs.com/useraccounts/core
atmospherejs.com/useraccounts/flow-routing
atmospherejs.com/useraccounts/iron-routing
atmospherejs.com/useraccounts/unstyled
atmospherejs.com/zimme/active-route
```

**Comment by Mardaneus86** [comment]
Nice @stubailo, the list by itself is already useful. I'm wondering how this can be integrated into the guide though.
I'm not familiar with CircleCI, so I'm afraid I can't be of much help with that right now.

**Comment by stubailo** [comment]
Yeah I suspect we won't have something for this in the near future, but I 100% agree that we should have a nice index eventually.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
