### ISSUE TITLE
should mention throwStubExceptions in error handling part of methods section

### ISSUE THREAD

**Issue by irrigator** [meteor/guide#182]
I just learned that the [validated-method package](https://github.com/meteor/validated-method) turns on the throwStubExceptions option of Meteor.apply, which stops the server-side method from being called if an error was thrown by the client. What's more, "if you have some permission logic that relies on data only available on the server, you should wrap it in an if (!this.isSimulation) { ... } statement."

I think this is a very good pattern, which not only conserves server resource but also forces you to make clear what kind of errors can be determined on the client and what can only be determined on the server. 

It might be a good idea to add this pattern to the error handling part of methods section. Its not being there may cause confusion.

**Comment by stubailo** [comment]
You're right! Going to add it now.

**Comment by stubailo** [comment]
Added: 1de40f80bd3cac7633d73d585dc097d1aa849ea6

There might be some other content in the ValidatedMethod README that isn't in the guide... let me know if you find something else!
