### ISSUE TITLE
Discussion: namespacing methods and publications

### ISSUE THREAD

**Issue by irrigator** [meteor/guide#183]
The reason is that in many cases a method is not necessarily tied to one particular collection. The denormalization nature of MongoDB makes this kind of situations more common than usual.

**Comment by stubailo** [comment]
I guess you can name it whatever you want, it just seems that a lot of frameworks (like Rails, for example) group things around models. It seems natural to me that if you were looking for a method, it would be easiest to look nearby the relevant collection code.

Do you have a different idea for naming?

**Comment by irrigator** [comment]
The problem is that oftentimes it's hard to decide which method belongs to which collection. As a result, it will be rather confusing to search for a method around one collection, only to find it's in another.

Let's take an imaginary app for example. In the app there are users collection and publishers collection. One user can follow many publishers. It uses two-way referencing for this one-to-many relationships: there is a "followedPublishers" field in users collection and there is a "followedBy" field in publishers collection. The "following a publisher" action needs to update both users collection and publishers collection. Should I name it "Meteor.users.methods.followPublisher" or "Publishers.methods.followedBy" ?

**Comment by stubailo** [comment]
I just can't think of a naming convention where you wouldn't have to make such a decision.

**Comment by irrigator** [comment]
Me neither :). But I will continue thinking about this and other ways to improve the Guide as I build more apps. 

Thanks for your quick reply.
