### ISSUE TITLE
Concepts and philosophy article

### ISSUE THREAD

**Issue by mbrookes** [meteor/guide#187]
Discussion: https://github.com/meteor/guide/pull/186#issuecomment-169828784

**Comment by stubailo** [comment]
This can be a good place to explain some of the Meteor mental model and organization -

1. Why client-side rendering
2. Reactivity
3. Different components and projects of Meteor, and how they compare to competitors/alternatives
4. Where to find different repositories on GitHub

**Comment by tmeasday** [comment]
I guess we sort of already cover this in the welcome article--I suspect expanding on that would make sense rather than duplicating the ideas again in another article? Unless there's a lot of content you are thinking of?

**Comment by mbrookes** [comment]
@tmeasday - we were discussing the content here: https://www.meteor.com/projects. It's perhaps a bit long to be used directly in the guide, but there's a lot of valuable material there which sets the scene for the rest of the guide, and isn't easily discoverable in its current location.

**Comment by tmeasday** [comment]
Ahh, yeah. I did see some other correspondence about that. I quite like that stuff, it seems like a lot of useful work to drop on the floor (although is there a maintenance plan for it?).

**Comment by stubailo** [comment]
Yeah I mean that stuff really should be much shorter and the guide is a great place for it IMO

**Comment by mbrookes** [comment]
I guess, to use @tmeasday's words, "it got dropped on the floor", as the link is now dead.

**Comment by abernix** [comment]
If there's an actionable item here that can still provide value, I'd love for us to look into that.  Please do submit a PR to this repository for consideration!

The "projects" (i.e. list of packages) is currently available in the `packages` directory of the main repository: https://github.com/meteor/meteor/tree/devel/packages.  It roughly represents what was at the now defunct `meteor.com/projects` page. Individual packages have their own `README.md`, which is certainly the most reasonable way to maintain that documentation, but it's possible it should be linked to somewhere.   This page is briefly linked to within the [`DEVELOPMENT.md`](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#additional-documentation) document which outlines the various parts of Meteor core.

**Comment by mbrookes** [comment]
I'm not actively involved with Meteor any more, but this was in my open issues. It was the content at meteor.com/projects that was valuable. If it's gone, it's gone.
