### ISSUE TITLE
Suggestion: adding i18n to the outline?

### ISSUE THREAD

**Issue by SachaG** [meteor/guide#19]
Implementing internationalization in your app doesn't take that much work thanks to the aweseome [tap:i18n](package), so I think it'd be worth mentioning it.

**Comment by stubailo** [comment]
It's under here: https://github.com/meteor/guide/blob/master/outlines.md#meteor-guide-uiux

Is that a good place? That's where I've put most of the user-facing stuff like animations, accessibility, etc.

**Comment by SachaG** [comment]
Well, my only objection would be that if you consider i18n as purely user-facing you tend to focus on templates and forget that you also have to translate things like errors thrown, schema field labels (if you're using something like Autoform), dates, etc.

**Comment by stubailo** [comment]
Yeah but all the things you mentioned are user-facing, right? Like by definition you only have to translate things users see.

**Comment by SachaG** [comment]
Yeah you're right. Happy to have that section wherever you think it fits :)

**Comment by stubailo** [comment]
Yeah I think the ux guide should have stuff about error messages and dates

**Comment by stubailo** [comment]
Going to close this since it's already in the outline!
