### ISSUE TITLE
TOC sometimes too long to fit on screen

### ISSUE THREAD

**Issue by GregS2** [meteor/guide#191]
I notice that sometimes the table of contents is too long to fit on the screen, and there is no way to scroll down. The workaround is to click around on the headings until a shorter section is expanded, which shortens the TOC.  It would also be nice if clicking on the heading of the currently open section would toggle it expanded & collapsed for each click, but that doesn't work either.

**Comment by stubailo** [comment]
Interesting - it always scrolls just fine for me. What browser are you in? Is there a particular page it happens on?

**Comment by GregS2** [comment]
Thanks. Tried with both Chrome & Edge on Windows 10. No particular page - to reproduce, I can click on the heading for "Collections and Schemas", which expands the table of contents, and then I can't access the lower portion of the TOC. The problem is only with the table of contents pane. When I scroll down, only the content pane scrolls. There is no separate scroll bar for the TOC pane.

P.S But I've just noticed how the currently visible section of the content automatically highlights the associated heading in the TOC, as I scroll - nice touch. ;^)

**Comment by GregS2** [comment]
FYI, on a touchscreen (Android tablet in my case), I can scroll the TOC pane by swiping.

**Comment by stubailo** [comment]
Ok ill try loading it in Windows and see what happens.

**Comment by GregS2** [comment]
Thanks. 
Same problem on Ubuntu using Chrome - no scroll bar.
HOWEVER, there is a scroll bar when using Firefox on Ubuntu!

**Comment by jlevycpa** [comment]
I can confirm the same behavior on Windows 10. Chrome, IE, and Edge do not show a scroll bar for the TOC. Firefox does show the scroll bar. 

If you have a scroll wheel or a touchpad that supports a scroll gesture the TOC will scroll, but one of my laptops has neither of those things and the guide is basically unusable there.

**Comment by yyx990803** [comment]
@stubailo this is probably related to the CSS here: https://github.com/meteor/guide/blob/92965a1a400f727221b3aac7c2b4216bb9b923f5/site/themes/meteor/source/style/main.styl#L41-L43

**Comment by stubailo** [comment]
@yyx990803 is this to hide the scrollbar on Windows? Perhaps we can just not hide it?

**Comment by tmeasday** [comment]
We'd take a PR that moves the current article TOC to the top of the article, in the style of rails guide

**Comment by jlevycpa** [comment]
Was this resolved? I see it was closed but the scroll behavior still looks the same to me.

**Comment by stubailo** [comment]
Oops looks like we closed it as a duplicate of the newer issue 280. Sorry!
