### ISSUE TITLE
Considering translation to other languages

### ISSUE THREAD

**Issue by p4bloch** [meteor/guide#192]
Having this guide is an amazing resource for mastering Meteor, and due to its complexity I believe it would be helpful to translate into other languages.

I think the key variables to consider are both **how** and **when**. I participated in the translation of Discover Meteor and the process was very simple and many people collaborated. We could create separated repos for each language in order to keep the original guide's PRs clean.

As to when, I believe it all depends on how stable the guide or each of its pages are.

**Comment by stubailo** [comment]
That sounds like a great idea. Can you tell me more about the Discover Meteor process? How did you find out about updates to the source material? How up-to-date was it? How did you build and deploy the translation?

**Comment by necmettin** [comment]
I would like to participate in a translation effort (into Turkish). I have translated many open source apps and some documentation into Turkish and I can work in whatever manner you guys decide.

Considering the content is in Markdown, we translators could follow commits to find out which pages have changed, and go on with plain Markdown files. But this method requires too much manual labor on the translators' (or team leaders') side.

As a translator, I have first-hand experience of the pain of creating a smooth translation process. My two cents would be using one of Transifex, Pootle, LaunchPad or Weblate.

**Comment by p4bloch** [comment]
@necmettin looks like you have way more to add into this issue than me, thank you for jumping in!

With Discover Meteor we had an organization for each language: DiscoverMeteor_ES, DiscoverMeteor_PT, etc, and each one had a fork of the original (private) repo. That way we could add collaborators to the organization, who were responsible of approving the pull requests.

We had a [translation guideline](https://www.discovermeteor.com/guidelines), and as with the deployment I think @tmeasday is who implemented it. They also implemented [a progress system](http://www.discovermeteor.com/translations) which would a very nice to have.

**Comment by tmeasday** [comment]
@SachaG would be the best person to speak about it but it was a bit of an involved process getting it all set up. However part of that was because we were hosting the translations in a different way (freely available, on Heroku IIRC) than the core book. Probably in this case we could piggy-back @yyx990803's work pretty easily. I suspect a system built on branches would be easiest.

**Comment by SachaG** [comment]
Yeah I think our collaboration process works well (basically, self-organized GitHub teams) but the deployment is a bit cumbersome. I wanted each translated version to be deployed to a separate Heroku instance, in case a team decided to customize their version. But that didn't happen, so if I had to do it again I'd probably host everything with a single app. Happy to answer questions :)

**Comment by John-Luke** [comment]
I have an interest in helping the translation into Portuguese (I never participated in any translation project, but it's always a good time to start)

**Comment by necmettin** [comment]
Ping.

I want to start translating already. :)

Maybe we can start with:

1. Create folders with language code under `translations/`, e.g. `translations/tr/`.
2. Start translating.
3. Create pull requests for each file completed. The translators would be responsible for tracking their own progress.

It would be even easier to work with if the English source was moved to `en/`, but I wouldn't mind either way.

We can move on to a better/ more automated/ whatever process in the future, but this way, we can start right now. This _issue_ has been open for six weeks now, we can start now and optimize/automate later.

**Comment by tmeasday** [comment]
I think it's better to just open a branch for each language and send PRs there. 

Then at some point we can make the build system publish each branch to a separate endpoint.

Which languages would we like branches for?

**Comment by p4bloch** [comment]
I agree with Tom.

My only concern will be keeping branches up to date with the english version. To avoid this conflict, I would suggest we only translate pages that are locked for modification in the english branch.

**Comment by tmeasday** [comment]
On that subject, I'd suggest anything that's in the v1.2 guide (http://guide.meteor.com) except perhaps for the "Build System" and "User Interfaces" articles.

**Comment by p4bloch** [comment]
I think it would also be useful to implement a wiki page on this repo or somewhere else so we can keep track, manually at first, of which articles are stable enough to be translated.

**Comment by stubailo** [comment]
I think the problem with articles being outdated is always going to exist - none of the articles are going to be static forever. But I think a good strategy would simply be to have a warning far ahead of time when we are considering making significant changes. So you should assume an article is stable unless notified otherwise.

**Comment by lightningboss** [comment]
Before the translation process, I think each language should have its own styleguide.

**Comment by necmettin** [comment]
I have a few points to discuss:

@p4bloch An article that is not stable enough to be translated should not be in the master branch anyway. So there is no need for a translator or content creator to mark a file as _stable enough_ or not.

@stubailo There is no need for notifications of possible significant changes. It will take weeks for the translators to catch up to master anyway. Also, a translator of opensource projects knows that the sentence s/he translated today can change tomorrow.

@lightningboss I'm not sure I understand. You mean writing and grammar rules for the language, things like _single space after punctuation_, right?

@tmeasday Why leave out those two? Imho, anything that is part of The Meteor Guide (except anything that is specific to the English language - which there are none afaik) should be translated.

I sense some misunderstanding here. It seems you assume we will translate all the branches (hence the need for _stable enough_ and _locked_). That's not the case (it should not be, that's not how translation works in digital projects). Only the master branch, anything merged into master will be translated. Orphan or unmerged branches will not be translated until they are part of master. Anything that finds its way into master is _stable enough_, and _is marked for translation_.

**Comment by lightningboss** [comment]
@necmettin In German, we use some English words. The Discover Meteor Book has some [guidelines](https://github.com/DiscoverMeteor/DiscoverMeteor_de), each translator should consider. E. g. using the word _Code_ instead of the German translation (_Quelltext_). The goal should be writing consistent text.

**Comment by necmettin** [comment]
@lightningboss I see what you mean now. You mean translation rules (i.e. _do not translate folder names_) and translation memory (i.e. _translate Code as Code instead of Quelltext everywhere_).

**Comment by tmeasday** [comment]
> @tmeasday Why leave out those two? Imho, anything that is part of The Meteor Guide (except anything that is specific to the English language - which there are none afaik) should be translated.

Oh, just because there are changes to those articles coming in 1.3. You can see the latest versions at guide.meteor.com/v1.3, or on the `version-1.3` branch.

**Comment by tmeasday** [comment]
I've created a `translation-de` and a `translation-es` branch. Please send PRs there (including styleguide-related stuff).

We'll figure this out as we go but if people want to get started, feel free. Also it may make sense to open separate issues if people want to discuss details of specific languages.

Any other languages we want?

**Comment by necmettin** [comment]
I will be translating into Turkish.

We need maintainers for each language, one person for each language responsible for accepting PRs into their respective languages. I wish to be the Turkish language maintainer.

Also, I may be way off, but if I read the repo correctly, you guys do not tag versions. Will you be invalidating 1.2 documentation when 1.3 comes out (or when you are confident you've covered 1.3 guide-wise)?

Shouldn't we maintain documentation for each Meteor version? How do you plan to distinguish v1.2 and v1.3 documentation? Using branches would Ωmean multiple master branches (one for each version). Not everyone can/will switch to 1.3 right away, so we need to maintain 1.2 docs, too, right?

Either way (versioning by tagging or branching), I think translations will need to use the same method to distinguish versions. Let me know how we (I) should go about this.

Thanks.

**Comment by tmeasday** [comment]
I've added a `translation-tr` branch.

> We need maintainers for each language, one person for each language responsible for accepting PRs into their respective languages. I wish to be the Turkish language maintainer.

Let's wait a bit and see how things pan out before assigning maintainers. Send some PRs to the branch!

> Also, I may be way off, but if I read the repo correctly, you guys do not tag versions. Will you be invalidating 1.2 documentation when 1.3 comes out (or when you are confident you've covered 1.3 guide-wise)?

We'll branch the current `master` as `version-1.2` right before merging the current `version-1.3` branch.

> Either way (versioning by tagging or branching), I think translations will need to use the same method to distinguish versions. Let me know how we (I) should go about this.

I guess I was thinking we should just focus on translating the latest version (ie. `master`). I'm not sure we'll have enough energy to maintain multiple versions in each language.

**Comment by lightningboss** [comment]
I just have another question. How should I handle the translation of partials of one language? E. g. I've only translated half of an article but want others to make comments on those translations?

Where should the styleguide go?

**Comment by necmettin** [comment]
My experience is that you don't have to finish translating a file to commit your work. Especially if it's a plaintext (or markdown) repo.

Considering the translations are in the same repo as branches, that means they will not be merged to master. So you can keep your styleguide-{{language}} in your branch.

**Comment by necmettin** [comment]
For our repo maintainers, I'm thinking if I should create a wiki for Turkish translation. I don't think we need/want translation commits in repo history, right? So I'm thinking import current files to the wiki; create a few extra files like contributors-turkish, translation-memory-turkish, translation-status-turkish; translate everything and then push them back to the repo all at once. After current push (4feffcc) is done, create a commit to translation-tr for each push to master. How does that sound?

**Comment by stubailo** [comment]
Personally I would much prefer having all of the commits in one repository. you can easily create a fork of the repository for temporary work and then merge it back in when you are ready.

**Comment by tmeasday** [comment]
> Where should the styleguide go?

I think you could just put them right in the README of the branch (like we have the english styleguide in the master branch).

> I don't think we need/want translation commits in repo history, right?

I don't see any problem with having translation commits on the translation branches. That way authors will get (some) acknowledgement for their work. It seems simplest that way.

**Comment by tmeasday** [comment]
We have a PR for a start to the German translation: https://github.com/meteor/guide/pull/269 if any German speakers would like to take a look!

**Comment by gcacars** [comment]
Hey @tmeasday, can you create a branch for the Brazilian Portuguese? Something like translate-ptBR or translate-pt-BR. I want to translate the guide. Note that portuguese (from Portugal) is different from Brazilian portuguese.

**Comment by tmeasday** [comment]
@gcacars - done! https://github.com/meteor/guide/tree/translate-pt-BR

**Comment by yoshi-sato** [comment]
Hello @tmeasday .
I am interested in translating the guide into Japanese. Could you maybe create a branch like translate-jp so that I can PR?

**Comment by tmeasday** [comment]
Maybe @lorensr is the one to do this now?

**Comment by filipenevola** [comment]
Hi @yoshi-sato, great that you are going to translate to Japanese.

I just created the branch for you.
https://github.com/meteor/guide/tree/translate-jp

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
