### ISSUE TITLE
React

### ISSUE THREAD

**Issue by discdiver** [meteor/guide#194]
Like the Blaze article, but for React. To quote Geoff's Dec. Devshop talk: "So, I think we should aim to support React, Angular, and Blaze as equal partners. That means expanding the Meteor Guide to cover all three, not just Blaze."

Great work on the guide!

**Comment by stubailo** [comment]
Thanks! Yes we should definitely have react and blaze sections as soon as we can.

**Comment by tmeasday** [comment]
See #83
