### ISSUE TITLE
Best CDN for Galaxy + SSL

### ISSUE THREAD

**Issue by 416serg** [meteor/guide#195]
I know there is <a href="http://guide.meteor.com/deployment.html#cdn">this</a> in the guide but I am wondering what your opinion is on what is a good CDN + Meteor + SSL combo.

I am setting up Galaxy and using  CloudFlare but had to disable websockets so I am wondering if there is a workaround or a best-practices set up.

**Comment by stubailo** [comment]
I'll ask the Galaxy folks what they think!

**Comment by stubailo** [comment]
OK, we don't have any concrete guidance from Galaxy. Perhaps @tmeasday will have some ideas.

**Comment by 416serg** [comment]
@stubailo thanks! You guys are awesome

**Comment by tmeasday** [comment]
@416serg we've general used and seen others use CloudFront as their CDN. We're planning on expanding the instructions (see #198) with a bit more detail but @queso's post linked to from that issue http://joshowens.me/using-a-cdn-with-your-production-meteor-app/ pretty much nails it.

**Comment by tmeasday** [comment]
For SSL I don't have any particular recommendation of who to use. I think people tend to get it from their domain registrar.

**Comment by 416serg** [comment]
@tmeasday I am actually setting up CloudFront as per his article but it seems like I am doing something wrong as to the set up since I get the following two issues
 
* i get a `"Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://myid.cloudfront.net/21bedf9958c1674a094d5a166e541b67e39bc8a9.css?meteor_css_resource=true"."`
* when i go to `https://myid.cloudfront.net/` the whole meteor app loads at that url.

I don't think that should be happening so I am not sure if I am doing something wrong or it's the `WebAppInternals.setBundledJsCssPrefix` behaviour.

But we can close this off I guess since it's getting taken care of in the future

**Comment by lorensr** [comment]
I don't think @416serg is speaking of where to get an SSL cert, but the fact that Cloudflare SSL currently doesn't support websockets unless you're an enterprise customer. However, it looks like they'll at some point either be opening it up to non-enterprise accounts or to Galaxy:

![image](https://cloud.githubusercontent.com/assets/251288/12462201/0666ae44-bf8b-11e5-9700-6dd709c69086.png)

**Comment by queso** [comment]
@416serg I am also curious to here what you find in regards to the MIME type issue. I did not run into that, but I am using Nginx to serve up my static assets directly instead of passing those requests to Meteor, which isn't as fast at reading files off disk.

**Comment by queso** [comment]
I would again argue for not using CloudFlare here, they really try to do too much, imo. Even if they added websocket w/ SSL support, you are basically giving them all the traffic up front and hoping they do the right thing with it.

By using Nginx for load balancing and CloudFront from AWS, I can easily control where and how things go. Nginx now picks up things like bot requests and forwards it all to prerender install I am running.

**Comment by 416serg** [comment]
@lorensr was exactly right about my concern with SSL and CloudFlare. After reading @queso 's post about CDN and his set up I was drawn towards CloudFront. However I am no expert in backend stuff so I am not sure what to set up for Nginx etc (or if I can even do that since I have the app on Galaxy as well as Modulus). 

I am not sure what happened with the MIME type issue, I am going to be troubleshooting that tonight to figure out what exactly caused it to happen but it was weird seeing my app show up at the CloudFront url and not just the static assets.

Will keep you guys posted (gonna leave this open for now)

**Comment by tmeasday** [comment]
@416serg the whole app being available at the CDN url isn't unexpected; it is just proxying all requests through to your Meteor app after all. I think this is basically how Cloudflare wants you to do things. You'll probably see issues with websocket traffic with CloudFront though.

I've not seen that mime type issue before though. It looks like perhaps the CSS file isn't actually being served by cloudfront. It's possible it's a stale entry in the cache somehow (can you post the true URL?) -- I'd try starting again with a new CloudFront distribution and deleting old one.

**Comment by 416serg** [comment]
@tmeasday Yeah i realized I was worried for now reason. The error was coming from an old cached css file, that, when I went to was return my Meteor 404 page. All the headers on active css files are good to go so that was my problem.

I will create a new distribution and check back and monitor the websocket traffic. 

Thanks!

**Comment by tmeasday** [comment]
> probably see issues with websocket traffic with CloudFront though

When I said this, I meant if you tried to put the whole site behind the CDN (ie. send users to to the CDN base URL) rather than just the assets as @queso suggests. Reading it now it seems like my above comments could be confusing.

**Comment by 416serg** [comment]
@tmeasday so you mean if I set this up using the `WebAppInternals.setBundledJsCssPrefix(Meteor.settings.cdnPrefix);`

I should be good to go?

**Comment by tmeasday** [comment]
I think so. I mean if the site works and the JS and CSS are being served from the CDN (you can check in developer tools) then I think you are good.
