### ISSUE TITLE
Multi Tenancy?

### ISSUE THREAD

**Issue by muloka** [meteor/guide#197]
Hey,

Currently looking up how to create a multi tenant Meteor app and came across this discussion: https://forums.meteor.com/t/multitenancy-and-meteor/5653

Nonetheless I was wondering if this topic would be something worth covering as part of the Meteor guide?

Cheers,

Louis

**Comment by stubailo** [comment]
How much content about this would we need to make it useful? Is it just a short list of stuff like "have a separate database per app" or something like that?

**Comment by zimme** [comment]
Why was this closed?

**Comment by stubailo** [comment]
I think we closed it because it was old and didn't have any responses. Are there some good articles about how to do it?

**Comment by zimme** [comment]
I could try and write up at least which approaches there is and which i belive is most used, i.e. the only approch i've run inte when doing multi tenancy with Meteor.

**Comment by stubailo** [comment]
That would be amazing!

**Comment by carlditzler** [comment]
`[Activity in the forums](https://forums.meteor.com/t/guide-chapter-multi-tenancy/22347)` shows interest. This also comes up on stackoverflow.
Should include multiple methods for different cases:
1. Single Meteor app with separate db per tenant (including single master or in each separate db for user management)
2. Multiple Meteor apps per tenant with single (e.g., handle tenant routing/authentication) or multiple dbs
3. Single Meteor app, included db, for all tenants handled via multiple domains with nginx/Passenger
4. Support with Docker or similar

**Comment by davidalekna** [comment]
Hey guys, is there any updates on this?

**Comment by leizard** [comment]
I'm in the same boat too. Would love to have more information about this.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
