### ISSUE TITLE
Deployment > CDN expansion

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#198]
(1). I think many people think of a CDN as a thing you can upload static assets to, and the js/css bundles do not feel like static assets, since at least in dev they're always changing filenames, and even if they only changed once per deploy in production, it would be a chore to upload them to the CDN every time. So for those, they might dismiss the idea of CDN, or not understand how it will work with `WebAppInternals.setBundledJsCssPrefix(DNS_HOSTNAME)`. 

So I think it would be helpful to explain 'origin' support, and how a URL is written and fetched from the server if not already cached, as explained in:

http://joshowens.me/using-a-cdn-with-your-production-meteor-app/

cc @queso 

(2). "If you are following the above approach, you may also want to manually add the CDN’s hostname whenever you put an image/other asset URL in your application’s code. To do this throughout your app, you can write a generic helper like imageUrl()"

I think it would be good to clarify that you mean if you have `public/images/foo.png`, then to reference it, do:

```
<img src="{imageUrl "images/foo.png"}">

Template.registerHelper 'imageUrl', (file) ->
  'https://d1477spkfkmftw.cloudfront.net/' + file
```

**Comment by tmeasday** [comment]
I think you are right. I was literally just thinking that this section doesn't have enough detail I think subsequently people are confused.

**Comment by tmeasday** [comment]
Also, mention `WebAppInternals.setBundledJsCssHook`

**Comment by lorensr** [comment]
I can write this as I add a cdn to my app soon, unless you're already working on it?

**Comment by tmeasday** [comment]
That'd be awesome!

**Comment by lorensr** [comment]
@tmeasday did you actually mean `WebAppInternals.setBundledJsCssHook` or rather `setBundledJsCssPrefix`? I'm not finding `-Hook` in the code or Google.

**Comment by tmeasday** [comment]
Apologies `setBundledJsCssUrlRewriteHook()`.
