### ISSUE TITLE
Use meteorpad for example/demo apps

### ISSUE THREAD

**Issue by zimme** [meteor/guide#21]
This way users have a chance to start playing with examples/demos within seconds instead of having to set up an example manually or cloning a repo to get started.

**Comment by SachaG** [comment]
If we do this can we find a way to make MeteorPad faster first? Sometimes it works great, but sometimes it's barely usable. Which is a shame, as I think MeteorPad would be invaluable otherwise (I try to use it for every tutorial I write).

**Comment by stubailo** [comment]
Yeah... I'm not a super huge fan of Meteor pad. I wonder if we could use something more generic like terminal.com or nitrous.io or similar? They might be excited about being an "official partner" for Meteor demos.

On a related note, I currently don't have plans to write guide-specific examples; I was going to try to modify the existing apps like Todos to follow the guide recommendations, but not every point might make it into an example app.
