### ISSUE TITLE
1.3 Migration

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#219]
What things do we need to cover? Here's my list:

1. Breaking changes (as we'd normally do this)
2. Recommended changes : Modules [link to app structure guide]
  1. App changes: `import` / `export` `includes/`.
  2. Package changes ? (no longer `export` in package.js?)
  3. Using Npm
  4. React with Meteor
3. Recommended changes : Testing [link to testing guide]
  2. App tests -> migrating from velocity to `meteor test-app --integration`
  3. Unit tests -> migrating from package test approach to `meteor test-app --unit`
4. Recommended changes: Mobile [link to mobile guide] ?

**Comment by tmeasday** [comment]
Initial PR here: https://github.com/meteor/guide/pull/221

**Comment by dburles** [comment]
On the npm integration, I think it's going to be important now to educate people on how to determine if they should be searching atmosphere or npm for any particular package - seems like it's easily going to be a point of confusion for many
