### ISSUE TITLE
Atmosphere

### ISSUE THREAD

**Issue by robfallows** [meteor/guide#22]
How about a short section on getting the most out of atmosphere?

Maybe this is a bit too basic for the intended audience, but given the number of forum questions which end up answered as "try adding package xxx:yyy", some guidance would appear to be useful.

- Search strategies
- Refining the list:
  - Things to look for that are good
  - Warning signs

**Comment by stubailo** [comment]
I think this could go in some more generic "getting started with Meteor" type of guide? Otherwise, it basically becomes docs for Atmosphere, which should probably be on that website instead.

**Comment by queso** [comment]
@stubailo is there a way for the community to contribute to an effort to put docs on Atmosphere? If so, +1

**Comment by stubailo** [comment]
> contribute to an effort to put docs on Atmosphere?

Tell me more?

**Comment by stubailo** [comment]
Oh, right - you're saying that there should be a guide on Atmosphere about how to use it effectively, and it's a shame that people can't contribute to that.

**Comment by stubailo** [comment]
So this intersects well with a question that's open in my mind: Where do we put docs about using packages from NPM and Bower? Perhaps there's a short article about using external packages?

**Comment by tmeasday** [comment]
Maybe add this to the using packages article?
