### ISSUE TITLE
Publications and Data Loading validation error catching

### ISSUE THREAD

**Issue by rdagger** [meteor/guide#227]
[Defining a publication](http://guide.meteor.com/data-loading.html#publications) recommends data validation using SimpleSchema instead of Check.  The SimpleSchema validate method will cause the publish method to break if the parameters are invalid as designed but it doesn't throw an error.  Check would throw an error to the console.

Is there a way to capture validation errors in publish methods when using SimpleSchema

**Comment by tmeasday** [comment]
Hey @rdagger - I think they both throw an error if you use SimpleSchema in the way we recommended in the guide (`schema.validate()`).

You can pick up subscription errors in an `{onStop}` callback to your `Meteor.subscribe()` call:

```js
Meteor.subscribe('asdf', {
  onStop(error) {
    if (error) {
      console.log(error);
    }
  }
});
```

We considered writing a wrapper for pub/sub similar to `ValidatedMethod` to make it easier to access that error but decided it was a bit much in the end. We should probably document how to do this in the guide though. Do you agree @stubailo?

**Comment by abecks** [comment]
I was recently tripped on this issue aswell. My subscriptions stopped working and I had to track this down manually. 

Perhaps updating the example subscribe to include an onStop example would help:

```
Meteor.subscribe('todos.inList', list._id);
```

to:

```
Meteor.subscribe('todos.inList', list._id, {
   onStop: ...
});
```

On that note, what is the best way to update the UI reactively if a subscription fails due to an error? Currently, my UI listens for subscriptionHandler.ready() to be true. An error does not set ``ready`` to true, so my loaders are stuck indefinitely. I'm assuming I need to wire up my own reactive variable based on ``ready`` AND not having errors returned from the subscribe call. A best practice pattern here would be greatly appreciated!

**Comment by abecks** [comment]
I wanted a global subscription error handler so I knew when any one subscription failed. I didn't want to repeat the onStop handler for every subscription in my app, so I created the following monkey patch:

```
import { Meteor } from 'meteor/meteor';
import { Blaze } from 'meteor/blaze';
import { _ } from 'meteor/underscore';

if (Meteor.isClient) {
  function getSubscribeArgs(...args) {
    const onStop = function globalOnStopHandler(error) {
      if (error) {
        console.error(`Error in ${args[0]} publication`, error, this);
      }
    };

    const lastParam = args[args.length - 1];
    if (_.isObject(lastParam) && _.any([lastParam.onReady, lastParam.onStop], _.isFunction)) {
      // lastparam is callback object, add onStop if it's not present
      if (!lastParam.onStop) {
        lastParam.onStop = onStop;
      }
    } else {
      // lastparam is not callback object so we'll add ours
      args.push({ onStop });
    }
    return args;
  }

  const oldMeteorSubscribe = Meteor.subscribe;
  Meteor.subscribe = function meteorSubscribeOverload(...args) {
    return oldMeteorSubscribe.apply(this, getSubscribeArgs.apply(this, args));
  };

  const oldBlazeSubscribe = Blaze.TemplateInstance.prototype.subscribe;
  Blaze.TemplateInstance.prototype.subscribe = function blazeSubscribeOverload(...args) {
    return oldBlazeSubscribe.apply(this, getSubscribeArgs.apply(this, args));
  };
}
```

Putting it here in case someone else finds it useful. It would be great to have a better way to do this. If subscription handlers had a prototype we could specify it there?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
