### ISSUE TITLE
Provide one-page version of the guide

### ISSUE THREAD

**Issue by mitar** [meteor/guide#231]
Useful for searching across all with browser (I do not trust other searching features). Also easier to store to the disk. Easier to use offline.

**Comment by stubailo** [comment]
Could also be useful to generate a giant PDF.

**Comment by hwillson** [comment]
Just a quick note about this - until there is either a one page version or the site search is re-enabled, you can always search the raw search JSON, if you're looking for something in a hurry. 

http://search-api.swiftype.com/api/v1/public/installs/h1KW95Mz3fNyf4cnqVtr/search.json

Search in your browser, then find the closest "title" section to see where the result is in the Guide. Hurts the eyes but it works.

**Comment by stubailo** [comment]
Whoa. Does searching google work? Like can you just search "meteor guide <topic>"? Let me check...

**Comment by stubailo** [comment]
Lol, close enough?

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=meteor%20guide%20seo

**Comment by hwillson** [comment]
Haha - actually, it does work though; just add the site: restriction to clean things up a bit: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=site:guide.meteor.com+validatedmethod

**Comment by mitar** [comment]
I prefer seeing things on the page. So that I can move around. See where some term is used across topics.

**Comment by stubailo** [comment]
@mitar yeah, this is why we turned off the search feature - it just told you which page the term was on, and didn't do a good job showing you where it was mentioned. Hopefully their new thing is better!

**Comment by mitar** [comment]
But the simple solution is just to provide one-page and this is it. This is what this ticket is about. :-)

**Comment by stubailo** [comment]
@mitar yes, I agree having one-page is good for a lot of things!

@yyx990803 is this easy to do?

**Comment by mitar** [comment]
Search discussion should probably go to #232.

**Comment by mitar** [comment]
(And those examples.)

**Comment by skirunman** [comment]
Search is enabled, do we still need 1 page site?

**Comment by stubailo** [comment]
It's useful to have one page that you can print as PDF, until we have a PDF download option.

**Comment by skirunman** [comment]
Agreed, PDF download would be nice.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
