### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by mitar** [meteor/guide#232]
Provide search over the guide.

**Comment by stubailo** [comment]
Pretty excited about this: https://community.algolia.com/docsearch/

@yyx990803 suggested it.

**Comment by stubailo** [comment]
@maxiloc posted this in a new issue, moving it to this thread:

-----

Hi there,

Following https://github.com/vuejs/vuejs.org/pull/235

I tried to make the same PR for meteor guide as @yyx990803 suggested
But I am not sure where to put the input.
I successfully configure our crawler for the guide content, so if you are interesting you just need to add the following thing:

```
<link href="//cdn.jsdelivr.net/docsearch.js/1/docsearch.min.css" 
rel='stylesheet' type='text/css'>
```

```
<script type="text/javascript" 
src="//cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js"></script>
```

```
<input id="search-input" />
```

```
<script>
docsearch({
  apiKey: 'ccee06ad1a884cf67686f7574d6f8594',
  indexName: 'meteor_guide',
  inputSelector: '#search-input',
});
</script>
````

Then to customize the dropdown you can follow https://community.algolia.com/docsearch/documentation/#customization

Feel free to ping me if you have any question

**Comment by obiwarn** [comment]
v1.3 Guide is becoming really large. 

Could be a good idea to integrate search there.

**Comment by tmeasday** [comment]
I'll take a look..

**Comment by skirunman** [comment]
Can this be closed?

**Comment by stubailo** [comment]
Yeah looks like it works!

**Comment by tmeasday** [comment]
@maxiloc I'm getting "Invalid Application-ID or API key" now with the above parameters -- is it possible our index got disabled?

**Comment by maxiloc** [comment]
Yes it has been disabled. I just re-enable it and update it. The new key is b123b42bb515f300dc09dc88f7695ec1

**Comment by tmeasday** [comment]
Thanks very much @maxiloc !
