### ISSUE TITLE
Client-side state management

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/guide#234]
I'd be happy to submit a draft if you guys had any thought into doing this.

**Comment by stubailo** [comment]
Can I rename this issue to "Guide article on managing client-side state"? I think focusing around a specific technology before thinking about the problems is a mistake.

**Comment by tmeasday** [comment]
I'm in two minds on this one. I think Redux is super useful to a lot of people and there'd be a lot of value in documenting how best to use it with Meteor.

However I'm not sure that we actively recommend people use it for client-side state do we? It seems like overkill to me for most apps.

Perhaps as you suggest @stubailo we have a client-side-state article, which starts with the stores section here (http://guide.meteor.com/data-loading.html#stores) [which always seemed out of place], and then moves on to Redux as an "advanced" solution for complex apps.

**Comment by abhiaiyer91** [comment]
IM in

**Comment by stubailo** [comment]
Here's a folder of outlines you can use as an example: https://github.com/meteor/guide/tree/master/outlines

Let's work on an outline, and that will help us see if an article makes sense!

Please submit a PR with an outline to that directory. Excited to see what you come up with.

**Comment by skirunman** [comment]
I think this is a key add to the guide as managing local state, especially for UI, should have some opinionated best practices such as don't use sessions, use template reactive-vars or reactive-dict for more global state that needs to exist across hot reloads, etc.

See https://www.discovermeteor.com/blog/study-plan-meteor-1-3/#local-state-management for some ideas I would like to see covered.

**Comment by skirunman** [comment]
Related to this are https://github.com/meteor/guide/issues/77 https://github.com/meteor/guide/issues/78 https://github.com/meteor/guide/issues/79

**Comment by skirunman** [comment]
There used to be some good info in the concepts section of the [docs on reactivity](https://github.com/meteor/meteor/blob/devel/docs/client/full-api/concepts.html#L278). I'd like to suggest that this gets combined into a single article that covers managing local state and reactive data sources. Probably also split out the [data loading stores](http://guide.meteor.com/data-loading.html#stores) info in to this new section and discuss this before diving in to pub/sub.

**Comment by stubailo** [comment]
Yeah, that makes sense to me. If someone puts together an outline for this article in the spirit of the ones we did for the others, I'd be happy to review it!

Example outlines: https://github.com/meteor/guide/tree/master/meta/outlines

**Comment by mitar** [comment]
Copying from #77:

From the discussion [here](https://forums.meteor.com/t/tracker-2-0-the-evolution-of-tracker-solutions-to-its-core-problems) we found few main things guide should tell people about Tracker:
* you should use `fields` to limit your Mongo queries to only fields you are interested in, because otherwise computations might be invalidated for you unnecessary
* use something like [computed fields](https://github.com/peerlibrary/meteor-computed-field) package to limit the reactivity only to changes of data, even if inside you get some unnecessary invalidations
  * related to this is to explain a bit more about different equality of variables, see https://github.com/meteor/guide/issues/79

**Comment by skirunman** [comment]
After thinking about this a bit more it makes sense to me to have two articles.

1)Intro to Meteor reactive data, would cover how tracker works and how to use it, and also include intro to all included Meteor reactive data sources that is currently discussed in the [old docs concepts section on reactivity](https://github.com/meteor/meteor/blob/devel/docs/client/full-api/concepts.html#L278). This could be the first article in the Data section of the guide.

2) Client state management best practices with focus on UI state, mini-mongo, reactive dict/var and session, concepts like redux, etc. This would include moving the aforementioned [data loading stores section](http://guide.meteor.com/data-loading.html#stores) to this article.

If people are on board with this I can probably flush out some outlines tomorrow. Thoughts?

**Comment by stubailo** [comment]
Yeah that sounds pretty good to me. Since we removed that section from the docs, it makes sense to add one to the guide. Let's get some outlines going!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
