### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by maxiloc** [meteor/guide#237]
Hi there,

Following https://github.com/vuejs/vuejs.org/pull/235

I tried to make the same PR for meteor guide as @yyx990803 suggested
But I am not sure where to put the input.
I successfully configure our crawler for the guide content, so if you are interesting you just need to add the following thing:

```
<link href="//cdn.jsdelivr.net/docsearch.js/1/docsearch.min.css" 
rel='stylesheet' type='text/css'>
```

```
<script type="text/javascript" 
src="//cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js"></script>
```

```
<input id="search-input" />
```

```
<script>
docsearch({
  apiKey: 'ccee06ad1a884cf67686f7574d6f8594',
  indexName: 'meteor_guide',
  inputSelector: '#search-input',
});
</script>
````

Then to customize the dropdown you can follow https://community.algolia.com/docsearch/documentation/#customization

Feel free to ping me if you have any question

**Comment by stubailo** [comment]
Moved to #232
