### ISSUE TITLE
Make the Blaze guide a replacement for Spacebars README

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#238]
For example, this is a crucial piece of information we are missing: https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#reactivity-model-for-each

**Comment by tmeasday** [comment]
Hmm, that's odd, I'm sure we planned on including that in the "understanding blaze" section.

**Comment by stubailo** [comment]
Yeah I thought so too. Let's try to see what else we missed. Not time sensitive though.
