### ISSUE TITLE
Suggestion: Emails

### ISSUE THREAD

**Issue by Urigo** [meteor/guide#24]
* Package
* Avoiding spam
* MX records
* Tracking emails
* Popular services - get services to write us guides or link to their own

**Comment by SachaG** [comment]
Telescope's email package also does the following:

- Wrap email contents in a nice layout (with header, footer, common styling, etc.)
- Auto-generate the text version of the email.

**Comment by stubailo** [comment]
What about sending SMS messages, etc? Or is that super different?

**Comment by SachaG** [comment]
I don't know, but the [Herald](https://github.com/Meteor-Reaction/Herald) package can help manage notifications across multiple media.

**Comment by stubailo** [comment]
Whoa, interesting!

**Comment by SachaG** [comment]
Here's how it's used in Telescope: https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-notifications/lib/notifications.js

First I set up a bunch of notifications, then for each I define "couriers" that manage the notification for the various media (in my case, just email and on-site).

And here's how I actually trigger a notification:

https://github.com/TelescopeJS/Telescope/blob/4d2d328da12fd78f6e5d7b4f0b3b90b3f9283700/packages/telescope-notifications/lib/callbacks.js#L20

**Comment by Pushplaybang** [comment]
This is a big one, and would be deserving of a proper discussion in the Meteor guide, from simple to advanced. + 1

should include : 
 - Basic emails
 - HTML email
 - Service integration (mandrill, mailchimp etc)

While packages can solve problems like this, have a guide that walks you through these sorts of core application features will aid developers in building more advanced functionality on top.

**Comment by tmeasday** [comment]
This feels more like a cookbook article than a guide article, see https://forums.meteor.com/t/community-contributed-docs-examples-from-stackoverflow/20888/6
