### ISSUE TITLE
Using packages

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#240]
How to best use packages from NPM and Atmosphere; things like `package.json` and shinkwrapping.

**Comment by tmeasday** [comment]
#242

**Comment by skirunman** [comment]
There is a some info that I think is key to using Meteor Atmosphere packages that is currently not in the guide such as:
1) How to list the packages you are using.
2) How to update to a specific version of a package.
3) How to remove a package.
Also, benefits like Meteor's constraint resolver and access to package exports and package globals without using ES2015 modules. I understand we want to transition to NPM and use of explicit import/export, but think this should be mentioned for completeness as Atmosphere and Meteor packages are not going away anytime soon. I'll submit a PR.
