### ISSUE TITLE
[1.3-beta.11] Points of confusion with testing

### ISSUE THREAD

**Issue by aldeed** [meteor/guide#246]
@tmeasday, I've been trying to update an app with a bunch of unit tests to 1.3-beta.11. I know that testing.md in `testing-modules-content` branch is a work in progress, but I thought it would be useful to list the things that are confusing me here.

I am using `avital:mocha` and `expect` pkg for assertions and spies. Overall it is working pretty well, except for the following.

1. I can't figure out how to designate a `*.tests.*` file to run only on the server. I can wrap the `describe` block in `if Meteor.isServer`, but the `import` lines still run and throw errors on the client. 
2. The article says that `Meteor.isTest`, `Meteor.isUnitTest`, etc. will be set, but they are not set in my `*.tests*` files when I run `meteor test-app --unit`.
3. Two of my `*.tests.*` files tests are not listed in the server results in the browser. This is probably something weird about the tests, but could also be a bug. I just want to mention it here because if I figure out why it's happening, the cause and resolution should probably be in the guide.

**Comment by tmeasday** [comment]
Hey @aldeed, thanks for trying it out and giving feedback!

1. -- You can put the `import` inside the `if (Meteor.isServer)` via using `require`: https://github.com/meteor/todos/blob/master/imports/api/lists/lists.tests.js#L18

  @benjamn do we have a better approach to this problem that doesn't involve having to use `require`? In our case (`import './server/publications.js'`) I would have expected it to just do nothing (as the file is in a `server/` directory) rather than throw.

2. This is surprising. Can you reproduce this in a simple app?

3. Do the files execute? Can you also reproduce this and post it somewhere?

**Comment by aldeed** [comment]
Thanks. For 2, I will try to reproduce and post here and/or as a bug. For 3, yes, they execute, and the mocha UI also stops at 75%, as if it knows the tests exist but they never finish or never display results. Similar to what happens with a long-running test, but they never time out.

I agree we need a better approach for server-only/client-only. Using `require` instead of `import` makes me sad. :) In theory if there is a way to designate entire files, either by being in `/server` or maybe `*.server-tests.*`, then you could also support `--unit --server`, e.g., to run and watch only server files.

**Comment by aldeed** [comment]
@tmeasday, reproduced 2 and submitted a bug report here: https://github.com/meteor/meteor/issues/6331

It is only an issue in server code.

I also noticed a couple other issues with the guide article in one of the code examples:

1. `const {describe, it} = mocha;` line is not needed because `describe` and `it` are already available in the test files when they run. Is there some other reason to define those explicitly? If so, guide should mention it.
2. `from "avital:mocha"` should be `from "meteor/avital:mocha"` and `from "mdg:factory"` should be `from "meteor/mdg:factory"`

**Comment by aldeed** [comment]
For issue 3 in my OP, I removed all tests and gradually added them back until I figured out what test was causing the issue. It seems to be that the Fibers wrapper in `practicalmeteor:mocha-core` (which avital:mocha uses) is swallowing an error and that causes the tests to stop running and never time out. I will try to do a minimal repro of that and submit an issue or PR to that package.

**Comment by tmeasday** [comment]
@aldeed -- yeah I have sent some PRs in the past to try and fix some problems with that fibers wrapper; I'm not sure if it ever got completely sorted out. Let me know if I can help with that, it would be good to figure it out once and for all.

**Comment by tmeasday** [comment]
re: `const {describe, it} = mocha;` <- I kind of feel like it's better to do it this way as it "fits" with the import model rather than having globals, even though most mocha examples out there don't do it this way.

**Comment by aldeed** [comment]
I don't necessarily disagree about the explicit `const {describe, it} = mocha;`, but the way I read the wrapper code, it looks like the `it` function would not be wrapped in fiber if you do it that way.

**Comment by tmeasday** [comment]
Ahh, ok. I'll double check that but you are probably right. Probably we should try and get this changed in the underlying mocha-core package that people are using at some point.
