### ISSUE TITLE
Testing Section Feedback

### ISSUE THREAD

**Issue by samhatoum** [meteor/guide#247]
@tmeasday I'm looking at the [defining-a-mocha-test](https://github.com/meteor/guide/blob/testing-modules-content/content/testing.md#defining-a-mocha-test) and I have some feedback for you :)

The test shown in the guide looks like this:
```javascript
import {mocha, chai} from "avital:mocha";
import Todos from './Todos.js'
import Factory from "mdg:factory";

const {describe, it} = mocha;
const {assert} = chai;

describe('todos', () => {
  describe('mutators', () => {
    it('builds correctly from factory', () => {
      const todoId = Todos.insert(Factory.build('todo'));
      const todo = Todos.findOne(todoId);
      assert.typeOf(todo, 'object');
      assert.typeOf(todo.createdAt, 'date');
    });
  });
});
```
The `builds correctly from factory` test is more of an integration test than a unit test, by virtue of having multiple units. The test integrates the Factory and the `Todos` collection + a Mongo connection + database (or in-memory possibly). For this test to be a unit test, it would have to isolate the very specific unit. 

Here are my thoughts on how you would do unit testing. Let's take a closer look at the Factory SUT:

```javascript
// todos-factory.js
import Factory from "mdg:factory";

Factory.define('todo', Todos, {
  listId: () => Factory.get('list'),
  text: () => faker.lorem.sentence(),
  createdAt: () => new Date()
});
```

I can see the SUT is the `build` method on the `Todo Factory` namespace, and it should behave as follows:

* it should create an object of type Todos
* it should set the list id to the current list
* it should insert fake content into the text field
* it should set the createdAt date to be the current date

I would then expect the tests to isolate those individual behaviours and not care about the database insert. Something like this (using Jasmine syntax):

```javascript
// todos-factory.tests.js
import Factory from "mdg:factory";
import { Todos } from './todos-factory.js';

describe('Todo Factory', function() {
  describe('build', function() {
    it('should create a Todos object', function() {
      const todo = Factory.build('todo');

      expect(typeOf todo).toEqual('object');
      expect(typeOf todo.listId).toEqual('string');
      expect(typeOf todo.text).toEqual('string');
      expect(typeOf todo.createdAt).toEqual('date');
    });

    it('should set the list id to the current list', function() {
      spyOn(Factory, 'get').and.returnValue('someId');

      const todo = Factory.build('todo');

      expect(Factory.get).toHaveBeenCalledWith('list');
      expect(todo.listId).toEqual('someId');
    });

    it('should insert fake content into the text field', function() {
      spyOn(faker.lorem, 'sentence').and.returnValue('fake content');

      const todo = Factory.build('todo');

      expect(todo.text).toEqual('fake content');
    });

    it('should set the createdAt date to the current date', function() {
      const todo = Factory.build('todo');

      expect(todo.createdAt).toEqual('date');
    });
  });
});
```

Notice the organization and structuring of `describe` / `it` blocks. An approach that really works well for clarity of intent, is use the describe blocks to drill down to the SUT, then to specify what the SUT should do in the it block. Typically, the SUT can be pinpointed using 2 describe blocks as you would likely have a NameSpace and a method (see below for an example).

Another tip for clarity is to allow the eyes to travel very quickly to see what the test is doing. Tests always follow the setup / execute / verify sequence. By simply putting a blank line between these sections, it makes it super clear what the test is doing. This allows you to a do a "squint test" (mentioned in this [awesome talk](http://blog.testdouble.com/posts/2015-11-16-how-to-stop-hating-your-tests.html)) and see that your tests are following a structure through out. If you don't see a pattern to the setup/execute/verify or it's difficult to read, it's a sign that the test is either being too clever or trying to do too much.

Putting all these tips in once place, here's the structure for any type of test (unit/integration/acceptance):

```javascript
describe('NameSpace', function() {
  describe('method', function() {
    it('should behave in a given way', function() {
      // setup
      
      // execute

      // verify
    });
  });
});
```

That's all I have for now, hope that helps you write awesomeness.

**Comment by tmeasday** [comment]
Thanks @samhatoum, I really appreciate this.

You are right of course that that unit test is really an integration test. I think I should pick a better example that actually sets the SUT to something inside the Todos app, and isolates it properly, as you did with the factory above. Maybe the factory is a good example, I'll think about it.

The larger issue here is our new "unit test mode" doesn't really guarantee that things are unit tested -- you need to isolate things, as you've shown above, to achieve that. We can't really ensure that a test run in "unit test mode" is a unit unless we implemented something like Jest (which we aren't going to do, at least right now anyway).

So I fear our "unit test mode / integration test mode" is a misnomer really. "Integration test mode" tests are really a special kind of integration test where the whole app is available. What would you call such a test?

The integration test mode is intended to replace Velocity tests (again where the whole app is available). Here's an example https://github.com/meteor/todos/commit/5f558744d966b77bc94b662639cb25169356748d [1]

Do you think that the way we've built integration test mode it will enable people to port their Velocity tests easily?

[1] PS I'm interested to hear your thoughts about the above. The two things I have struggled with in the past, and still struggle with here is that 
 a) There's no callback to know when the routing is done
 b) There's no callback for when the *subscriptions triggered by the route change* are done.

It seems a more acceptance test-style approach of just waiting until a condition is true (with a timeout) would work. I guess it's better than nothing but I wonder if you have ideas?

cc @avital

**Comment by robfallows** [comment]
@samhatoum : thanks for this - it's cleared up a lot of confusion for me :+1:

**Comment by Sanjo** [comment]
> The larger issue here is our new "unit test mode" doesn't really guarantee that things are unit tested -- you need to isolate things, as you've shown above, to achieve that. We can't really ensure that a test run in "unit test mode" is a unit unless we implemented something like Jest (which we aren't going to do, at least right now anyway).

> So I fear our "unit test mode / integration test mode" is a misnomer really. "Integration test mode" tests are really a special kind of integration test where the whole app is available. What would you call such a test?

As a developer I usually do not strictly differentiate when I unit test something or test a functionality that needs multiple units to work together. So 90% of what I also consider integration tests would run in the --unit mode for me. With ES2015 modules this is even better because unit dependencies are loaded automatically, because of explicit dependencies.
But with legacy apps that depend on global dependencies, it is easier to do unit and integration testing with a full app loaded in many cases, depending how clean you have separated your units.

So maybe it makes more sense to make the --unit mode the default and rename --integration mode to --full mode (or something similar).

> [1] PS I'm interested to hear your thoughts about the above. The two things I have struggled with in the past, and still struggle with here is that 
a) There's no callback to know when the routing is done
b) There's no callback for when the subscriptions triggered by the route change are done.

> It seems a more acceptance test-style approach of just waiting until a condition is true (with a timeout) would work. I guess it's better than nothing but I wonder if you have ideas?

I personally wouldn't write tests for the routes, because the router is a third party module that is tested and assumed to work correctly. Also when you have functional acceptance tests that are automated through the user interface, your routes are tested through those tests.

> a) There's no callback to know when the routing is done

That's something the router API should provide. I once wrote a waitForRouter function for IronRouter, but I don't have one for FlowRouter (haven't looked into it).

b) There's no callback for when the subscriptions triggered by the route change are done.

I use this for Methods. I think for subscriptions it's something similar. That's something the Meteor core could provide as public API:

```js
function waitForMeteorMethods(done) {
  var check = setInterval(function () {
    if (!window.Meteor) {
      done();
    }

    if (Meteor.connection._outstandingMethodBlocks.length === 0) {
      clearInterval(check);
      done();
    }
  }, 200);
}
```

(https://github.com/meteor/meteor/blob/devel/packages/ddp-client/livedata_connection.js#L588-L615)

**Comment by Sanjo** [comment]
@tmeasday I found the hidden subscriptions ready function :D https://github.com/meteor/meteor/blob/devel/packages/ddp-client/livedata_connection.js#L1693-L1699

```js
function waitForMeteorSubscriptions(done) {
  var check = setInterval(function () {
    if (!window.Meteor) {
      done();
    }

    if (Meteor.connection._allSubscriptionsReady()) {
      clearInterval(check);
      done();
    }
  }, 200);
}
```

or combined with Methods also:

```js
function waitForMeteorMethodsAndSubscriptions(done) {
  var check = setInterval(function () {
    if (!window.Meteor) {
      done();
    }

    if (Meteor.connection._outstandingMethodBlocks.length === 0 &&
        Meteor.connection._allSubscriptionsReady()
    ) {
      clearInterval(check);
      done();
    }
  }, 200);
}
```

**Comment by avital** [comment]
I like the idea of `meteor test-app` and `meteor test-app --full`. So that with apps transitioning into 100% modules, you just run `meteor test-app` to run your tests.

**Comment by avital** [comment]
And the documentation is clear: "`test-app` runs the test files in your app with their dependencies. Passing `--full` also loads your app (and hides it)"

**Comment by tmeasday** [comment]
For the record we went with `meteor test` and `meteor test --full-app`.

**Comment by samhatoum** [comment]
Awesome!

> So I fear our "unit test mode / integration test mode" is a misnomer really. "Integration test mode" tests are really a special kind of integration test where the whole app is available. What would you call such a test?

I would call these pseudo-unit tests. Even if the tests run in "full-app" mode, we can still achieve unit testing by using spies and mocks and they will run ultra fast. The only difference is that Meteor needs to be loaded first, so that's the heavy part. However, as Jonas mentioned, with modules and proper isolation, true unit testing is supported. 

@avital why do you have to hide the app? Perhaps in unit mode that's a good idea but in the `--full` mode i would want to have access to the DOM using jQuery for instance. If the reason is to display the test reporter, perhaps that can go on a different route, like `/test-report`?

**Comment by tmeasday** [comment]
The app is hidden via CSS so most jQuery etc will work just fine. If you need stuff to be visible on the screen (e.g. for clicks or screenshots) I'd say you are writing an acceptance test, right?

It can't go on a different route as that would stop router tests etc.

**Comment by samhatoum** [comment]
Yes for acceptance tests, I actually tried to run Chimp against the app in test mode and got an "element is not in a clickable state" error or similar.

I would like to take advantage of the `*.tests.js` loading mechanism, as it allows me to load some specific modules for e2e testing. 

With Velocity, I ran a before hook that removed the in-app reporter from the DOM. I guess that's still an option, though I think a command line option like `--no-reporter` or similar might be nicer experience.

**Comment by tmeasday** [comment]
What are the modules you are thinking of @samhatoum?

Would it make sense to just make them "debug only" imports? You can import them like

```js
if (Meteor.isDevelopment) {
  require('/imports/test-helpers/something.js');
}
```

**Comment by Sanjo** [comment]
> I would like to take advantage of the *.tests.js loading mechanism, as it allows me to load some specific modules for e2e testing.

I think the test driver package could also load those e2e testing modules, right?

**Comment by samhatoum** [comment]
@tmeasday Chimp has a `server.execute` method, and with the new modules system, we need the ability to require modules at runtime in the `server.execute` context. As per @benjamn's [advice](https://github.com/meteor/meteor/issues/6068#issuecomment-178940948), I currently include a `module-loader.js` file like this for this to happen:

```javascript
// Force meteor to load modules at build time, so they can be required in Chimp's server.execute
if (false) {
  require('./imports/validation');
  require('./imports/models/collections');
  require('./imports/models/account-holder');
  require('./imports/domain/services/bank-service');
  require('./imports/domain/services/bank-service/server');
  require('./imports/application/services/account-service');
  require('./imports/application/services/account-service/server');
  require('./imports/application/services/bank-service/server');
}
```

It would be much cleaner if this file was called `module-loader.tests.js` and not bundled for production builds. That's my current use-case that can't be solved with the `debugOnly` solution

**Comment by tmeasday** [comment]
Hmmm, interesting issue. One solution would be to create a "null" test reporter and run using that reporter. All it needs to do is define a `runTests` symbol (which can do nothing).

I'm not quite sure what the principled solution here is however.

**Comment by samhatoum** [comment]
I've been thinking along the same lines as the null reporter. It's only needed when you want to do `server.execute` commands, which already requires the user to install `xolvio:backdoor`. 

@sanjo and I are looking at revisiting the Meteor UX for Chimp soon, I'll let you know how we get on.
