### ISSUE TITLE
Suggestion: Files and images

### ISSUE THREAD

**Issue by Urigo** [meteor/guide#25]

**Comment by stubailo** [comment]
It's at the bottom here: https://github.com/meteor/guide/blob/master/outlines.md#meteor-guide-forms-user-input-and-methods

**Comment by stubailo** [comment]
Does that look like a good place for it to you?

**Comment by Urigo** [comment]
yes sorry !

**Comment by jesperordrup** [comment]
I searched for this in the published guide. I initially navigated to User Interfaces and looked after topics covering Forms, Input, upload & images. 

Is it covered anywhere in the guide? If not I suggest the following topics being added to User Interfaces. 

Forms
- Simple example (template, helpers, validation)
- Uploading files to cfs
- Using package aldeed:autoform

Files & Images
- Uploading files to CFS
- Packages

Fun fact: manual does not mention forms, documentation only mention forms in an example and i cant find it in the guide.

I hope this is the right place for this suggestion?

**Comment by tmeasday** [comment]
Hi @jesperordrup - This sure is the right place for suggestions!

We do have a article planned for forms: https://github.com/meteor/guide/issues/29, which you'll notice has a section on uploads: https://github.com/meteor/guide/blob/master/outlines/forms.md

Right now we unfortunately need to focus on other articles for the upcoming 1.3 release but we understand this is a major deficiency right now.

**Comment by m-adil** [comment]
@tmeasday [that link](https://github.com/meteor/guide/blob/master/outlines/forms.md) is not functional anymore. Is there any major update on this now?

**Comment by lorensr** [comment]
@m-adil Here it is:

https://github.com/meteor/guide/blob/master/meta/outlines/forms.md

and you can follow issue #29 for updates

**Comment by m-adil** [comment]
@lorensr thanks. Yeah I'd visited #29 before commenting here but there's no update since more than an year.
