### ISSUE TITLE
Setup https

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#255]

**Comment by lorensr** [comment]
I was searching for something and an https link came up in google results:

![image](https://cloud.githubusercontent.com/assets/251288/14840944/0376f388-0c07-11e6-8a36-08082f2d8d5a.png)

got timeout

**Comment by stubailo** [comment]
Uh-oh, that's not good! We turned it on then we had caching issues so we disabled it...

**Comment by lorensr** [comment]
How long ago? If recently, I'd imagine the Google crawler will soon realize it can't show the https links it generally prefers and switch to http

**Comment by stubailo** [comment]
Yeah that was like two days ago. Hopefully it's not a problem for long.

**Comment by abernix** [comment]
@stubailo Is this something that can be fixed in Google Webmaster Tools?  Don't know who at MDG might have access, but I know they let you set preferences, show errors, etc. on certain things in there  – maybe even trigger a recrawl?  Just a thought.

**Comment by tmeasday** [comment]
@abernix I'm not sure if it's possible to ask google to remove https links only but I suspect it'll resolve itself in a few days.

**Comment by DylanKojiCheslin** [comment]
currently the site's https. is this the desired behavior?

**Comment by tmeasday** [comment]
I guess we ended up doing it? I don't recall
