### ISSUE TITLE
Triggered restarts doesn't reset the database when testing

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor/guide#257]
Running ``Meteor test --driver--package practicalmeteor:mocha`` resets the testing database as expected. Hereafter modifying files will trigger the test to restart, but the database won't reset. To reset the database I have to do ``ctrl`` + ``c`` and then rerun the test.

**Comment by tmeasday** [comment]
I agree this is kind of weird, but it does mirror the behaviour of `meteor test-packages` I think. 

I think we should open an issue on meteor/meteor about this..
