### ISSUE TITLE
FlowRouter and action

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#26]
Referencing this: https://github.com/meteor/guide/blob/master/content/routing.md

It says that for a route like `/`, `action` is not called. But that's not true, otherwise this wouldn't work:

```jsx
FlowRouter.route('/', {
  name: 'home',
  action() {
    ReactLayout.render(Layout, {content: <Home />});
  }
});
```

**Comment by stubailo** [comment]
Oh, I see that this is unclear. I meant specifically for the route `'/blog/:postId'`.

I should make that waaaaaay more obvious in the table.

**Comment by ffxsam** [comment]
Oh, I see what it means now. Gotcha.
