### ISSUE TITLE
Clarify the style guide

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#261]
http://guide.meteor.com/ui-ux.html

"How to build a style guide to allow you to visually test such reusable components."

This at top didn't make sense to me. I think of a style guide as – always use braces on if statements, or maybe how to code your components (smart or reusable), and I can't imagine how a style guide can test something. A bit further down:

"They are easy to add to component style guides—as we’ll see in the section about component style guides, when creating a style guide, a clean environment makes things much easier to work with."

Still didn't get it. I sorta got it when I saw the picture – Okay, it's a listing of styles and components, but I'm not sure what this means: 

1. "A list of “entries”, where each entry is a component with a list of specifications. Each specification is a list of arguments which trigger different behavior when passed to the component." 

And not sure whether the pictured app is dynamic – like can I click around and change values and see what components look like with different inputs? 

And perhaps there's a better name? While a "component library", like you'd see in Bootstrap or Ionic, might serve a different purpose, the reader will at least imagine the right kind of thing.

**Comment by stubailo** [comment]
I've been thinking the name "component explorer" is more descriptive. @dominicnguyen is giving a talk about this at Meteor night tomorrow, it should give use some images and content to improve this section. Dom, are you up for submitting a small PR to tidy it up after your talk?

**Comment by dominicnguyen** [comment]
yes!

**Comment by dominicnguyen** [comment]
Updated the content here https://github.com/meteor/guide/commit/7080288ecb87849283376d5e70107fff73cccb1e. Going to close this issue. Please reopen if it still does not make sense.
