### ISSUE TITLE
Add MongoDB Index best practices

### ISSUE THREAD

**Issue by stephenwoods** [meteor/guide#271]
I'm currently using `collectionName._ensureIndex` to add indexes to my MongoDB instances.  I've gotten confirmation from @stubailo that it's okay to do this, and I believe a note about this would make a great addition to the guide.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
