### ISSUE TITLE
Issue with anchors and scrollTop

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#272]
If you click [this link](http://guide.meteor.com/v1.3/react.html#data), you can see that the section title and part of the content is cut off. If you click in the left nav, though, it scrolls to fix this.

**Comment by stubailo** [comment]
Oh interesting, it's because of the floating navbar. Any ideas for a fix?

**Comment by ffxsam** [comment]
I've run into this issue myself. The solution (a hack?) was usually to wait till the DOM was rendered, then run the very same scrollTop function you do when clicking on an item on the left.

**Comment by stubailo** [comment]
Hmm, I'd love to accept a PR for this. The app code is in the `site/` directory.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
