### ISSUE TITLE
Information about how to hide UI from logged out users is deeply hidden

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#273]
This section: http://guide.meteor.com/routing.html#route-rendering-logic

We might be able to give it a more informative name like "how to authorize routes" or whatnot.

Based on this Reddit post: https://www.reddit.com/r/Meteor/comments/4al3ob/why_does_flow_router_have_no_builtin/

**Comment by tmeasday** [comment]
I'm not sure this is perfect but maybe gets the point across better? http://guide.meteor.com/routing.html#route-rendering-logic

**Comment by stubailo** [comment]
No, I think the heading should include the words "logged out users". This is too abstract - people don't notice it if they are just skimming.

**Comment by tmeasday** [comment]
Ok fine https://github.com/meteor/guide/commit/0fe87d3a795b2c351d1537463e8db8dbe9cc179a

**Comment by stubailo** [comment]
:heart:
