### ISSUE TITLE
[React] Containers vs pages

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#274]
http://guide.meteor.com/v1.3/react.html#using-createContainer

>Then we create a ListsShowPage container component which wraps it and provides a data source

If I may offer some thoughts on this:

What if we just have a page be a regular component or stateless function? In my projects, I usually have four folders under `client` that are responsible for the layout and structure of the app: layouts, pages, containers, and components. The reasoning for not making a page a container is that it may not even care about data that high up, and only be concerned with laying out the page. Not to mention, a page can contain multiple containers. You could have a structure like this, where containers are far down along the tree:

    P > C1 > S1 > S3 > C4 > S5
           > S2 > C2 > S4

(P = page, C = container, S = stateless func)

What do you all think?

**Comment by tmeasday** [comment]
What does the page component do in this picture though? It looks like it just renders a single container? 

Are you saying that a page usually renders more than one container at the top-level? I can definitely see why this might be the case, but it hasn't typically been my experience..

**Comment by ffxsam** [comment]
It's in charge of page layout and rendering any containers. Real world example:

```jsx
import React, { PropTypes } from 'react';
import TrackListContainer from
  '/features/TrackManager/client/containers/TrackListContainer';
 import TagListContainer from
   '/features/Tagging/client/containers/TagListContainer';
import { _i18n as i18n } from 'meteor/universe:i18n';

export default TrackManagerPage = (props) => {
  return <div className="container" style={styles.container}>
    <div className="row">
      <div className="col-md-6">
        <TrackListContainer />
      </div>
      <div className="col-md-6">
        <TagListContainer />
      </div>
    </div>
  </div>
}

TrackManagerPage.propTypes = {};
```

**Comment by tmeasday** [comment]
Yeah, so I think this is pretty reasonable in the case where you do have more than one container, but I guess in the apps I've seen it's made sense to have the page === container given that's all the page is doing (rendering that one container). 

I think it will confuse people to introduce that extra level of abstraction when the examples they are looking at don't justify it. However I can see that by not doing so we might give people the wrong impression that containers should only be used for pages.

I'm not sure. However I don't think I've got time to change it for 1.3 now.

**Comment by ffxsam** [comment]
:thought_balloon: Just food for thought. :) The reason I typically *don't* make my pages containers is because IMO they should not be concerned with data or state, only layout. I actually forgot a layer in there:

    L > P > C1 > ...

where L is a layout, e.g.:

```jsx
FlowRouter.route('/some-route', {
  action() {
    mount(MainLayout, { content: () => <SomePage /> });
  }
});
```

And my layouts typically contain a header, navigation, and footer only.

**Comment by tmeasday** [comment]
Oh, but for me typically the page component just calls out to some other layout. So in your scheme it'd look like:

```jsx
Page = () => (
  <SomeLayout>
    <SomeContainer/>
  </SomeLayout>
)
```

**Comment by ffxsam** [comment]
Ahh, interesting! Obviously there's no right or wrong way, but I thought I'd bring this up and let other people chew on it for consideration.

**Comment by stubailo** [comment]
I was talking to @helfer and he found it confusing that there was a distinction between containers and pages. Maybe we should make that more clear. Also, there is some confusion on the forum about the React article, it might be worth linking to the UI article and others because you can't just read the React one in isolation.

**Comment by ffxsam** [comment]
Which articles are you referring to?

**Comment by stubailo** [comment]
Well, the React article isn't super helpful unless you've read about app structure, data loading, routing, and user interfaces. Some people on the forums were expecting it would be a complete guide about building a Meteor app with React, but it isn't - you have to learn the parts about building a Meteor app as well.

**Comment by ffxsam** [comment]
React article.. link?

**Comment by stubailo** [comment]
http://guide.meteor.com/v1.3/react.html

**Comment by ffxsam** [comment]
Ah ok. I feel like the right process is for someone to learn React on its own, and then learn how to use it in the context of Meteor (assuming they have little knowledge of either). Whereas Blaze is part of Meteor and can be learned together, React is its own separate beast. I don't know if the Meteor Guide should be responsible for teaching people React..? Though it would certainly be a huge bonus if it had some sort of crash course. :)

On a semi-related note, once someone is comfortable with React, [this is required reading](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) IMO, and relates to our discussion on containers.

**Comment by ffxsam** [comment]
Actually (and I'm rather opinionated on this), I think Meteor makes React easier to get off the ground. Setting up webpack can be daunting, and the documentation on the webpack site is terrible. Facebook has acknowledged that pain point, and they're planning on making setting up React a lot easier, as simple as a command like `react init myproject`.

So I feel that within the context of Meteor, a great way to learn React would be:

1) `meteor create myproject && cd myproject`
2) `npm install --save react react-dom`
3) Ok, now go and find some React tutorials, and ignore everything related to webpack. :)

**Comment by tmeasday** [comment]
Let's hope so! I mean you still need to learn about data I guess, but that'd be a great developer experience. 

We should work to make the React guide a good starting point for that experience. I don't think it really is there yet, it's more just "what do you need to know to use React/Meteor" right now.
