### ISSUE TITLE
[Validated Methods] Instructions could be clearer about arguments

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#275]
I just realized that validated methods only accept a single argument (besides the callback), so that argument must be an object literal if you want to pass multiple arguments. The guide doesn't (as far as I could see) call that out, and it's important to point out because with the "old way", you could pass multiple arguments:

    Meteor.call('someMethod', arg1, arg2, (error, result) => { ... });

**Comment by stubailo** [comment]
Please submit a pull request to add this to the guide! Should be just a sentence or two in the right place.

**Comment by minfawang** [comment]
I think this argument is not strictly correct. I think validated method do support multiple arguments, and just require to pass in a validate function that works for positional argument. Isn't it the case?

**Comment by stubailo** [comment]
Not that I know of, I intentionally designed it with the opinion that one should only use keyword arguments.

**Comment by minfawang** [comment]
It seems to be the case. Thanks for clarification!

**Comment by DylanKojiCheslin** [comment]
made a PR  

You call it the same way you call the advanced Method above, but the Method definition is significantly simpler. We believe this style of Method lets you clearly see the important parts - the name of the Method sent over the wire, the format of the expected arguments, and the JavaScript namespace by which the Method can be referenced. **Validated methods only accept a single argument and a callback function.**

**Comment by stubailo** [comment]
Thanks!
