### ISSUE TITLE
Where is the complete Meteor Guide code?

### ISSUE THREAD

**Issue by Kamin12** [meteor/guide#276]
The code covered in the Meteor guide, for Blaze, is not completely demonstrated anywhere. The project with Lists_Show and Lists_Show_Page as templates, and listArgs and todoArgs as helpers. I have spent weeks learning this code, and there's not a complete overview of the demonstrated project anywhere.

**Comment by stubailo** [comment]
It's here: https://github.com/meteor/todos

This is mentioned in the introduction page to the guide.

**Comment by Kamin12** [comment]
Bruh I go to client and there is one html file with one template. Wheres it at?

**Comment by stubailo** [comment]
It's following the Meteor 1.3 app structure: http://guide.meteor.com/v1.3/structure.html

**Comment by stubailo** [comment]
Specifically this file structure recommendation: http://guide.meteor.com/v1.3/structure.html#example-app-structure

**Comment by tmeasday** [comment]
It might be confusing that the todos code is following the 1.3 guide (http://guide.meteor.com/v1.3).

The code for the 1.2 guide is here: https://github.com/meteor/todos/tree/version-1.2

**Comment by stubailo** [comment]
Yeah we might want to figure out how to make that more clear, perhaps we should put links to different versions in the README?

**Comment by Kamin12** [comment]
Put links at the top of the Guide. 

 V2: Guide Link // Repo Link
V3: Guide Link // Repo Link

**Comment by tmeasday** [comment]
I mean as much as it is annoying @Kamin12 right now, we did make a clear decision to *not* keep the guide and todos app in sync. So this kind of problem will happen.

OTOH, having an entirely different version on `master` is probably a bad idea.

**Comment by Kamin12** [comment]
It's insane for them not to be in sync.

**Comment by tmeasday** [comment]
For instance I think the problems with finding the correct file in the Blaze guide will probably still continue; that article has *not* been altered in any way for 1.3.

> It's insane for them not to be in sync.

It's just not feasible to keep everything perfect. I can tell you from long experience that it's a *lot* of work to do so. We just don't have those kind of resources. The guide is intended for intermediate developers, people can work this stuff out.

OTOH I agree that it was a mistake to push the 1.3 code to `master` on the todos app, I'll approach it a different way next time.

**Comment by Kamin12** [comment]
I think it's important for it to be clear. You don't have enough resources you say, but maybe there would be more resources if it was clear. 

This is a technology business, and user experience is very important for profitability and long term success :).

**Comment by tmeasday** [comment]
> I think it's important for it to be clear. You don't have enough resources you say, but maybe there would be more resources if it was clear.

I'm not sure what you mean by this exactly? Do you mean by linking to the todos app at the top of each guide article as you've suggested?

**Comment by Kamin12** [comment]
I just mean focus on the User Experience by making things very clear and simple. Here is the guide, here is the code for the project that is covered in the guide. 

And as you upgrade the guide, upgrade the code to. And link back to all the previous guides and previous repos. Just a clear system moving forward.

User Experience is critical for anyyyyyyyy businessssss. Even though I'm a beginner developer (less than 6 months), I have experience in design and product strategy. So I'm saying a clear, in sync, system for the Guides and example code could be a wise business decision, that could result in even more resources.
