### ISSUE TITLE
Sidebar extends past Page Height

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#280]
When I go to a section like "Collections and Schemas," its related sidebar grouping extends fully. This causes the last parts of the sidebar, like Security and Deployment to go off the page. If I want to jump from Security and Deployment, I can't.

It'd be great if the sidebar groupings could be collapsed on another click, or if a scroll bar was added.

Note: My screen is 1920 x 1080, so if it's an issue on that, it's going to be more of an issue on a smaller screen

**Comment by stubailo** [comment]
Have you tried scrolling? The sidebar should be scrollable.

**Comment by merlinpatt** [comment]
If I use the scrollbar, it only scrolls the main content.

**Comment by necmettin** [comment]
I remember having the exact same problem a few days ago, but now it's gone. @merlinpatt could you check again?

**Comment by merlinpatt** [comment]
No difference.

**Comment by tmeasday** [comment]
Dupe of #191
