### ISSUE TITLE
CSS Convention - Scoping vs BEM vs OOCSS vs SMACSS

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#281]
Is there a preferred CSS convention when developing Meteor apps?

* [BEM - Block Element Modifier](https://en.bem.info/articles/why-bem-in-a-nutshell/)
* [SMACSS - Scalable and Modular Architecture for CSS](https://smacss.com/book/categorizing)
* [OOCSS - Object Oriented CSS](https://github.com/stubbornella/oocss/wiki)
* Scoping - I couldn't find an official name for this but I'm referring to using SASS / LESS scoping where you'd have `.template-name { .li { /* css */ } }`

**Comment by tmeasday** [comment]
I don't think so really, unless @dominicnguyen has an opinion he'd like to codify?

**Comment by dominicnguyen** [comment]
No strong opinion on CSS methodologies.

**Comment by merlinpatt** [comment]
The guide recommends an `eslint` config so I think recommending a CSS methodology (which could also be [CSS in JS](https://speakerdeck.com/vjeux/react-css-in-js) that I just learned about for React) is within the scope of the guide.

**Comment by skirunman** [comment]
I don't think an convention as specific as BEM or SMACSS is in scope in the guide. With that said, some guidance along of the lines of keeping CSS as modular as possible, especially if designing using a component approach, would be good guidance.

**Comment by tmeasday** [comment]
CSS is out of scope of the guide I think.
