### ISSUE TITLE
[version-1.3] React, Using createContainer wrong braces type?

### ISSUE THREAD

**Issue by vadimmelnicuk** [meteor/guide#285]
At http://guide.meteor.com/v1.3/react.html#data in following example wrong braces are used around **params** - should it be (params) instead?

change
`export default createContainer({ params } => {
  ...
}, ListsShow);`
to
`export default createContainer(( params ) => {
  ...
}, ListsShow);`

**Comment by tmeasday** [comment]
Hey @vadimmelnicuk  - params is a single prop, so this is a destructuring argument:

```
createContainer({ params } => {});

// is shorthand for

createContainer(props => {
  const { params } = props;
});

```
