### ISSUE TITLE
Proposal, move "Meteor Cookbook Using Dates and Times" to guide

### ISSUE THREAD

**Issue by pronevich** [meteor/guide#287]
Here https://meteor.hackpad.com/Meteor-Cookbook-Using-Dates-and-Times-qSQCGFc06gH is some highlights about using dates/time and relevant meteor packages and use cases.

Seems it can be helpful part of this guide.

**Comment by tmeasday** [comment]
I think cookbook stuff shouldn't live in the guide, there'll be more to come on this soon (https://forums.meteor.com/t/community-contributed-docs-examples-from-stackoverflow/20888)
