### ISSUE TITLE
Files and Uploading

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#288]
I think that a good section to have would be *Files and Uploads*.

To get it started, I'm aware of [CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS), which appears to be no longer maintained and [Slingshot](https://github.com/CulturalMe/meteor-slingshot), which is only for client side uploading.

Thoughts?

**Comment by tmeasday** [comment]
Hi @merlinpatt - we have uploading included in our forms outline: https://github.com/meteor/guide/issues/29. 

Not sure when we'll get to it, but I'm going to close this in lieu of that.
