### ISSUE TITLE
Last active link doesn't update when scrolling to last article 

### ISSUE THREAD

**Issue by elmarti** [meteor/guide#291]
See here: http://guide.meteor.com/structure.html
I am using the most recent google chrome on a 32 inch screen, when I scroll to the bottom of the page,  "sharing accounts" does not become active; it gets stuck on "sharing data". I have checked this across a number of articles and it is the same on all.

**Comment by tmeasday** [comment]
If you need a permalink, click on the link in the sidebar. I don't see a nice way to fix this.
