### ISSUE TITLE
Useful Packages

### ISSUE THREAD

**Issue by SachaG** [meteor/guide#30]
Atmosphere is great, but it's also a little hard to navigate sometimes. So I've been keeping track of useful packages on the side as well. 

Note that the end goal for this list is to eventually publish it as a free eBook to give away on the Discover Meteor blog. But until that happens, I suppose there's no harm in discussing it here :)

### Models & Collections
- https://github.com/aldeed/meteor-simple-schema
- https://github.com/aldeed/meteor-collection2
- https://github.com/dburles/mongo-collection-instances
- https://github.com/dburles/meteor-collection-helpers
- https://github.com/matb33/meteor-collection-hooks
- https://github.com/jagi/meteor-astronomy
- https://github.com/richsilv/meteor-dumb-collections

### Forms
- https://github.com/aldeed/meteor-autoform
- https://github.com/meteortemplates/forms

### Files
- https://github.com/CollectionFS/Meteor-CollectionFS

### Routing
- https://github.com/iron-meteor/iron-router
- https://github.com/meteorhacks/flow-router

### Tables
- https://atmospherejs.com/aldeed/tabular
- https://atmospherejs.com/aslagle/reactive-table

### Templates & Components
- https://github.com/peerlibrary/meteor-blaze-components
- http://viewmodel.meteor.com
- https://github.com/aldeed/meteor-template-extension
- https://github.com/meteor-space/ui
- https://github.com/themeteorites/blaze-magic-events/

### Publications & Subscriptions
- https://github.com/meteorhacks/subs-manager
- https://atmospherejs.com/tmeasday/publish-counts
- https://github.com/meteorhacks/fast-render
- https://atmospherejs.com/peerlibrary/reactive-publish

### Performance
- https://github.com/meteorhacks/meteor-down
- https://github.com/meteorhacks/cluster

### Security
- https://github.com/meteorhacks/sikka
- https://github.com/matteodem/meteor-easy-security
- https://github.com/ongoworks/meteor-security
- https://github.com/alanning/meteor-roles

### Accounts
- https://github.com/meteor-useraccounts/core

### Other
- https://github.com/dandv/rate-limit
- https://github.com/percolatestudio/meteor-migrations
- https://github.com/percolatestudio/meteor-synced-cron
- https://github.com/bengott/meteor-avatar
- https://github.com/mizzao/meteor-user-status
- https://github.com/Meteor-Reaction/Herald
- https://github.com/cmather/meteor-handlebars-server
- https://github.com/alethes/meteor-pages
- https://github.com/matteodem/meteor-easy-search
- https://github.com/mizzao/meteor-autocomplete
- https://atmospherejs.com/anti/fake
- https://atmospherejs.com/manuelschoebel/ms-seo
- https://github.com/TAPevents/tap-i18n
- https://github.com/raix/Meteor-EventEmitter

### Admin
- https://github.com/gterrono/houston
- https://github.com/yogiben/meteor-admin

**Comment by stubailo** [comment]
**Dumb collections** seems pretty awesome as an escape hatch to scaling - if you find that a subscription is being slow I wonder how hard it would be to swap it out with one of these.

**CollectionFS** - I've never used it, I understand it's basically the way to go when doing file upload in Meteor? Are there any good alternatives we should take a look at as well?

**Subs manager** - I wonder how well this works with template subscriptions, and whether it's crucial for us to include it in the guide.

**ongoworks/security** - I'm interested in using the `Security.can` approach to things. Should investigate further. Also `Meteor.runRestricted` looks interesting!

I'm just mentioning the ones where there might be interesting discussions; some of them are quite obvious, like `tap:i18n`.

**Comment by SachaG** [comment]
Re file upload, I feel like maybe things like http://cloudinary.com/ that store your file on S3 are better?

And I think Subs Manager is really necessary for almost any Meteor app. Otherwise having to wait for subscriptions on every route change kinda makes using a single-page app pointless…

**Comment by rhyslbw** [comment]
**[space:ui](https://github.com/meteor-space/ui)**
It's worth mentioning that while space:ui (about to be renamed to space:flux) integrates with the view layer, I wouldn't categorise it under 'Templates & Components' as the goal is to better manage state using a Store and provide an event bus for components to announce changes in the view layer. The Store is a model of some concept in the UI and the API it exposes is then reusable across multiple components in the view.

**CollectionFS**
One caveat with the current implementation is that it limits the ability to run multiple instances of the app due to the use of observers for triggering cleanup and file maintenance tasks. I [worked on addressing this](https://github.com/CollectionFS/Meteor-CollectionFS/pull/667), but it's quite a big change since we're pushing the work into a mongo queue, and given the size of the current install base it needs a lot of review.

[vsivsi:job-collection](https://github.com/vsivsi/meteor-job-collection) should also be somewhere on this list @SachaG :-)

**Comment by jagi** [comment]
I would add https://atmospherejs.com/peerlibrary/reactive-publish to the Publications & Subscriptions section.

**Comment by SachaG** [comment]
@jagi added :)

**Comment by mitar** [comment]
+1 for job-collection.

**Comment by EldritchInteractive** [comment]
Constellation should be added, as well as perhaps a separate section for development related packages.

https://atmospherejs.com/babrahams/constellation

**Comment by arunoda** [comment]
@stubailo SubsManager is pretty important in template level subs. And it works pretty well with it.
See: https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management/using-subs-manager

**Comment by darko-mijic** [comment]
### Flux architecture 
https://github.com/worona/meteorflux/
Elegant solution for Flux architecture in Meteor, much simpler than space:flux

### Reactive Dependency Injection
https://github.com/meteorflux/reactive-dependency/

**Comment by Pushplaybang** [comment]
+1 for job-collection

**Comment by stubailo** [comment]
I think it wouldn't be useful to list all of the official packages on here - they are already quite popular and don't need the promotion!

**Comment by tmeasday** [comment]
I don't think the guide is the right place for this list of packages.

**Comment by mitar** [comment]
Wasn't that the whole promise of the guide? To embrace the community and point beginners to packages?

**Comment by stubailo** [comment]
Yes, but having a huge list of packages isn't very helpful. In fact, it might just cause people to get more confused that they have to learn all of these things to learn Meteor. 

If someone wants to write thoughtful articles about these packages and when they should be used, I'd be on board with that.

One option to move forward here is to make sure all of these packages are listed here: https://github.com/Urigo/awesome-meteor and then put a link to that page somewhere in the Guide. But we can't afford to be curating a huge list of packages for every possible occasion.

**Comment by mitar** [comment]
This guide really digressed into again just explaining mostly only core packages + iron router?

**Comment by stubailo** [comment]
That's not true - we have a whole host:

https://github.com/meteor/guide/issues/180#issuecomment-168779771

And that list is outdated, there's a bunch of testing-related ones as well.

Remember, the guide is _not_ about recommending cool resources or packages. It's about asking the question of what people want to accomplish with Meteor, and giving them the tools to do that. If you think there's something people want to do in Meteor that the Guide doesn't explain, then by all means let's have that conversation!

**Comment by mitar** [comment]
> If you think there's something people want to do in Meteor that the Guide doesn't explain, then by all means let's have that conversation!

I will make one example I am very familiar with: Blaze Components. They are not mentioned in the guide, despite they being pretty useful. Why? Maybe because we want to describe mostly pure Meteor. But then there should be at least a list of "do you want to lean more" or "some of things presented here are encapsulated in this package" or "for good patterns available through this package", etc.

**Comment by mitar** [comment]
> and giving them the tools to do that

You probably agree that we should provide them with the best tools to do that. Not just a tool. So if community have some packages do to something better, that should be at least mentioned, no?

**Comment by stubailo** [comment]
> Why? Maybe because we want to describe mostly pure Meteor.

I wouldn't say this is the case. I think it's more because we have analysis paralysis - should people use Blaze Components or ViewModel? Should people with Blaze apps be refactoring them to React, or Blaze Components? Does using Blaze components add too much stuff to learn? These are some of the questions I'm concerned about.

**Comment by mitar** [comment]
So, I think it would be great to just have a section at the end (or beginning) of Blaze chapter saying something along the lines: "Many patterns presented in this chapter can be found encapsulated and abstracted in the following community packages: Blaze Components, ViewModel. Moreover, React provides an alternative rendering engine with way to create components as well."

And similarly at other chapters (like data models, astronomy, etc.).

**Comment by mitar** [comment]
So what I am trying to say that lists of packages/references to community packages can be a middle ground. Instead of you having to make a decision, you just inform users where they can go on, if they want, and they decide on their own.
