### ISSUE TITLE
Make sure this is a complete replacement for the React Guide, and deprecate it

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#309]
http://react-in-meteor.readthedocs.org/en/latest/ was always meant to stick around only until NPM and React support was better in Meteor core. With the new React guide article, and better NPM support, we should remove that website.

I think some good steps are:

- [ ] Check if there is any content we didn't migrate
- [ ] Replace every page in the React guide with a link to the relevant part of the guide
- [ ] A few weeks/months later, take it down entirely

**Comment by tmeasday** [comment]
It should be a complete replacement! You could double check though.

I'll do the redirects / links sometime soon.

**Comment by stubailo** [comment]
People are noticing: https://forums.meteor.com/t/react-in-meteor-readthedocs-org/20427/2

**Comment by tmeasday** [comment]
I won't be able to get to this until next week.

**Comment by stubailo** [comment]
Done! https://github.com/meteor/react-packages/commit/f7d918be1df9fd778e9d531d519ad01a5ee9ad93

**Comment by tmeasday** [comment]
Wow, that was fast :bow:
