### ISSUE TITLE
Is there any content on IDEs?

### ISSUE THREAD

**Issue by obiwarn** [meteor/guide#310]
And why you prefer Atom?

**Comment by stubailo** [comment]
As far as I can tell, the only place we talk about editors is here: http://guide.meteor.com/code-style.html#eslint-editor

There, we mention Atom, Sublime, and WebStorm. So I don't know what you're referring to when you talk about a preference for a specific editor.

**Comment by obiwarn** [comment]
Thought it would be interesting which IDEs are recommended for Meteor and
which ones you guys prefer and why.

**Comment by stubailo** [comment]
Let's talk here: https://github.com/meteor/guide/issues/312
