### ISSUE TITLE
Application Structure: Folder for git submodules?

### ISSUE THREAD

**Issue by obiwarn** [meteor/guide#311]
imports/submodules?

**Comment by stubailo** [comment]
Is this for sharing code between multiple apps internally, or what?

**Comment by obiwarn** [comment]
yes. e.g. sharing the collections between admin and website project.

**Comment by stubailo** [comment]
If you're interested in contributing more detail, the right place to submit a PR would be to this section: http://guide.meteor.com/structure.html#sharing-code

So you could add some directions about how to include a submodule in the `imports/` folder and suggest that one place to put it would be a directory called `submodules/`.

**Comment by obiwarn** [comment]
I switched to a multi-root repo project since Webstorm's submodule support is crap.

**Comment by stubailo** [comment]
Tell me more? What do you mean by multiple root repos?

**Comment by obiwarn** [comment]
I want to introduce ES6 modules in my system. Right now  I try to share my "collections & schemas" folder between three projects (admin, website, mobile app).

And I have no clue how to do this the best way :-)

Git submodules in Webstorm are more treated like libraries. So it is rather hard to change something inside the submodule.

So now I test to have two separate git repos in every Webstorm project (e.g. collections repo & admin repo). So a better name would be multi-repo project?

**Comment by obiwarn** [comment]
OK found a solution for Webstorm:

Folders:

- mySystem
  - collections
  - admin
  - website
  - mobileApp

all 4 subfolders are separate git repos
admin, website & mobile are separate Webstorm projects
For each Webstorm project go to
- Settings > Directories > add root Folder collections (=multi-root project)
- Settings > Version Control > add Directory collections

Now all git operations are synced (e.g. a push in admin project pushes admin and collections repo)
