### ISSUE TITLE
Meteor Guide References Form Article in final release

### ISSUE THREAD

**Issue by dpeet** [meteor/guide#313]
Hey All!

Reading through the 1.3 guide (outstanding stuff btw!) and here http://guide.meteor.com/methods.html#method-form it mentions " The final released version of the Meteor guide will have a new article about forms." 

Is that article somewhere in the guide I'm missing?  I see another issue with it open that has been talked about recently.  The app I'm working on is a glorified (and complex!) input form, so I'd love to read the current best practices!

**Comment by tmeasday** [comment]
Unfortunately we didn't get round to writing that article as we don't have a great example app with a lot of forms in it, so it was a bit difficult making concrete recommendations. 

I should remove that reference :(

**Comment by stubailo** [comment]
Some discussion on the forums here:

https://forums.meteor.com/t/new-mdg-project-the-meteor-guide/10873/77?u=sashko
