### ISSUE TITLE
Document when and why to use meteor-node-stubs?

### ISSUE THREAD

**Issue by skirunman** [meteor/guide#314]
Should we document when you would need to `npm install --save meteor-node-stubs` for client-side stubs for built-in Node modules? Maybe somewhere in http://guide.meteor.com/using-packages.html#client-npm 

I see some of the Meteor tutorials have dependencies on this NPM package, but could not find anywhere in the Meteor documentation or guide telling a user when they would need to install and use this package.

See https://github.com/meteor/meteor/issues/6056

**Comment by tmeasday** [comment]
Hey @skirunman -- it's in the app skeleton, so it'll appear by default in all new Meteor apps. For that reason I don't think it necessarily needs to appear in the guide. Maybe we should have something about in the migration guide?

**Comment by skirunman** [comment]
I was not sure if it got put in a new app's package.json. Yes, probably add a one sentence blurb in the migration guide would be a good idea.

**Comment by derwaldgeist** [comment]
I want to support this. Although it is mentioned in the guide, I'm still uncertain in which cases it is actually needed.

**Comment by SimonSimCity** [comment]
@derwaldgeist as the update-guide states:
```
to allow using npm packages written for `node` on the browser
```

But I would expect those packages to have serious other things broken, as they're not written to run in the browser. If I'll find such a package, I'll make a PR to make it browser-compatible.
