### ISSUE TITLE
Add a section about migrating from meteorhacks:npm to new NPM support

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#315]
This came up in the Meteor Chef slack, seems like something a lot of people will be doing. @arunoda I don't know if you have any content about this?

**Comment by arunoda** [comment]
hmm. not sure. But, I think it's pretty straight forward as few bulletpoints. Are you looking for some automated script?

**Comment by tmeasday** [comment]
Maybe we can add the bullet points to the 1.3 migration guide?

**Comment by arunoda** [comment]
Yeah! That's good.
I also planning to write farewell post to meteorhacks:npm and cosmos:browserify :)

**Comment by stubailo** [comment]
It doesn't have to be anything fancy, just a few bullet points for the migration guide would be perfect! Just something that came up when talking to people.
