### ISSUE TITLE
App Structure: What about Mantra?

### ISSUE THREAD

**Issue by obiwarn** [meteor/guide#317]
Just an idea: 
Not sure if this is relevant but Mantra seems to get quite popular these days.
Any word on this? Do you guys recommend it?

**Comment by skirunman** [comment]
I think Mantra is overkill for most apps and is not really the "Meteor way" as they don't embrace isomorphic code. I think Mantra has some good ideas, but is out of scope for the Meteor Guide. My 2 cents.

**Comment by batjko** [comment]
I don't like the idea of having half your files do nothing but import and then export a whole bunch of other files. This middle-man logic is confusing for most Meteor apps, not to speak of any beginners or people wanting to prototype quickly. 

So I agree that it's not really the "Meteor way", at least in regard to Meteor's stated understanding of itself.

**Comment by tmeasday** [comment]
This is probably a better forum discussion.
