### ISSUE TITLE
Test documentation doesn't mention that tests in "tests" folder are ignored

### ISSUE THREAD

**Issue by siegesmund** [meteor/guide#336]
The current behavior seems to be to ignore tests in any folder called "tests". I believe that this behavior was to prevent tests being included in the build in prior Meteor versions. The documentation implies that any file that that complies with the specified naming convention will be loaded in test mode, regardless of the folder it's in. This should be clarified to avoid confusion.

> This loads your application in a special "test mode". What this does is:
> 
> Doesn't eagerly load any of our application code as Meteor normally would.
> Does eagerly load any file in our application (including in imports/ folders) that look like *.test[s].*, or *.spec[s].*
> Sets the Meteor.isTest flag to be true.
> Starts up the test driver package (see below).

**Comment by skirunman** [comment]
Yes, I noticed this as well. I'm fixing this in a PR I will submit today.

**Comment by stubailo** [comment]
Seems like this is fixed after that PR. Agreed it's a bit counterintuitive, but it was the best way to keep backcompat (Meteor 1.2 and before also ignored the `tests/` directory)
