### ISSUE TITLE
Question: where to import secret code from method

### ISSUE THREAD

**Issue by bitsuns** [meteor/guide#338]
In the [Secret Code](https://github.com/meteor/guide/blob/master/content/security.md#secret-code) example on the Security section, how/where would you import the secret code (i.e., MMR)?

If this were imported in the methods module, which is loaded on the client, the import would fail.

**Comment by stubailo** [comment]
Ah, that's a really good point. Unfortunately, ES2015 doesn't allow conditional imports, so we have to work around the standard a bit:

```js
let MMR;
if (Meteor.isServer) {
  MMR = require('/my/mmr/module');
}

// .. now we can use it on the server, but not on the client
```

This would be a really good thing to add both in the app structure, and methods articles. If anyone has time to put together a PR, that would be awesome.

**Comment by bitsuns** [comment]
Ahh, okay. Thank you for the clarification.

I may put a PR together that includes this and some of the material on async/sync w/in methods. Granted, the async section of [using-packages](https://github.com/meteor/guide/blob/master/content/using-packages.md) covers most of what I'd like to see for the latter.

**Comment by stubailo** [comment]
I'd suggest making those separate PRs just to keep the discussions separate!

**Comment by stubailo** [comment]
Similar discussion here: https://github.com/meteor/validated-method/issues/40

**Comment by TimeBandit** [comment]
This had me stumped to. I don't think the guide is explicit enough here w.r.t finally importing and running the secret sauce. Based on you response above I used require inside the !isSimulation block of a method definition. A few more worked on the guide would have saved me a lot of head scratching.
```

run({ amount, currency, source, metadata }) {

        if (this.isSimulation) {
            console.log('client side method simulation');
        } else {
            // only run server-side
            let charge = require('./server/charge').default();
            let result = charge({ amount, currency, source, metadata });
            return result
        }
    },
```

**Comment by xvendo** [comment]
This is still not clear in the meteor guide! Please give an example of the module export and the import of MMR.

**Comment by lorensr** [comment]
Does this work for you? https://github.com/meteor/guide/pull/744

**Comment by xvendo** [comment]
Thank you @lorensr. Yep that's the way to go!
