### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#34]
### Article outline

https://github.com/meteor/guide/blob/master/outlines/ui-ux-outline.md

### Major decision points

1. Components should be either 'pure' reusable components, or 'smart' app-specific data-loading components, regardless of which view framework you are using.
2. `tap:i18n` is the best internationalization library for Meteor today

---------

Old outline

## Sections

1. Reusable components
  - "pure vs impure" components
  - Using global singletons carefully (router / mongo / "stores")
  - Testing them / component harness (more to come later, just something for now)
2. UX patterns
  - Throttling event handling
  - Building a responsive / cross device application
  - Internationalizing an application
    - use https://atmospherejs.com/tap/i18n
  - Accessibility - @stubailo can you let me know what you had in mind here?
3. Realtime UX patterns
  - Using animation to reveal changes in a understandable way
  - Allowing the user to choose when changes happen to the UI.
  - Dealing with Latency Compensation - optimistically or otherwise

**Comment by stubailo** [comment]
> Accessibility - @stubailo can you let me know what you had in mind here?

I specifically don't know anything about accessibility, I added it to the outline because I think this is a point where we should do a little research, and it would reflect well on Meteor to give people tips about accessibility. This is stuff like optimizing for screen readers, having good text contrast, etc.

> Reusable components

This seems to overlap with your outline for Blaze - I think it should be here and not in the Blaze section?

**Comment by tmeasday** [comment]
Re: Accessibility -- Ok, I'll leave a dot point for it and you never know, someone might tell me the answer without me needing to do anything :/

Re: Reusable components -- I'll make sure the conceptual stuff is here (about testability, use of singletons, etc). The Blaze article can reference it and then go into detail about how to achieve it for Blaze.

**Comment by tmeasday** [comment]
Outline merged https://github.com/meteor/guide/blob/master/outlines/ui-ux-outline.md!
