### ISSUE TITLE
In navigation bar: search box overlaps other elements for width around 650px (see screenshot)

### ISSUE THREAD

**Issue by jirikrepl** [meteor/guide#347]
![meteor guide](https://cloud.githubusercontent.com/assets/2588479/14287021/8bbd2bca-fb51-11e5-909d-4cd23193867f.png)

**Comment by stubailo** [comment]
Looks like the whole website isn't very good at this width, since you can barely see the content. Perhaps we should just set a min-width on the body for this screen size to force the browser to scroll horizontally?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
