### ISSUE TITLE
Clarify startup files section about the client

### ISSUE THREAD

**Issue by joetidee** [meteor/guide#348]
Not sure if the 'Startup files' section of the docs is correct...

http://guide.meteor.com/structure.html

Should the first code block be /client/main.js and be including the imports/startup/client/routes.js file ?

**Comment by stubailo** [comment]
Yeah you're right -- this is confusing! Since we don't actually mention the `client/main.js` file which is very important for this whole thing to work. Definitely something to improve.

**Comment by townmulti** [comment]
This might be a good place to put the suggestion of adding a extra line notation to the top or bottom of the code snippets in the guide that notes what path & file the code snippet is generally recommended to be within.

**Comment by stubailo** [comment]
Hehe the tutorial technology we built really went to great lengths to achieve that, maybe we can do something simpler for the guide :P

**Comment by skirunman** [comment]
Hi @tmeasday, I'm about to submit a PR with some changes to structure.md and I think I addressed this issue. I'll cc you when I submit it.

**Comment by skirunman** [comment]
@tmeasday Here is commit with rework of structure section. 
https://github.com/meteor/guide/pull/356/commits/f652a39d0a6ab5f46d5cdd893e971fb2e6d355ef
