### ISSUE TITLE
react-mounter example uses a function instead of the component directly

### ISSUE THREAD

**Issue by rdagger** [meteor/guide#349]
http://guide.meteor.com/react.html#using-flow-router
I think 

```
mount(AppContainer, {
      main: () => <ListContainer/>,
    });
```

should be

```
mount(AppContainer, {
      main: <ListContainer/>,
    });
```

**Comment by stubailo** [comment]
You can do it either way, here's a section in the react mounter docs that documents how to use a function: https://www.npmjs.com/package/react-mounter#to-use-the-react-context

It is probably worth clarifying the guide on this point.

**Comment by rdagger** [comment]
Thanks.  It would be great to see an example including the AppContainer code too. 

Looks like the [react-mounter reference](https://www.npmjs.com/package/react-mounter#to-use-the-react-context)  specifies the function use for _React context_.

> In order to use the React context, you need to render the content component inside the layout. So we need to pass a function instead of the React element. 

I thought context was [not recommended](https://facebook.github.io/react/docs/context.html).

**Comment by stubailo** [comment]
Yeah I'm just saying it looks like the function approach works fine, regardless of whether or not you use context. But it would be helpful to see an example of the actual component being rendered.

**Comment by tmeasday** [comment]
I don't recall the reason we had to do this but I'm not sure it was because of context.

**Comment by tmeasday** [comment]
I think I recall the reason involved animation.
