### ISSUE TITLE
More examples on react integration in the guide, improve docs on react-meteor-data package.

### ISSUE THREAD

**Issue by zayaisshawn** [meteor/guide#351]
Also I'd like to know how to pass parent component's data to child component's wrapper container? I.e. Blaze's Template.parentData() equivalent in react-meteor-data's createContainer function. The example in the guide shows only that parent data can be passed as params when using react router.

**Comment by stubailo** [comment]
Yeah, I agree this is an oversight. Since the container component is such a big part of using React in Meteor, we should have a few more code samples for it.

**Comment by zayaisshawn** [comment]
That'd be great!

**Comment by zeroasterisk** [comment]
Agreed!!! 

React+Meteor is new to me and a lot of people and something that is still settling itself out... But we could all use more examples of best practices for larger apps.

Also make the tutorial also follow the single component/page/container per file... If that is the best pattern, let's follow it. If not, let's not. Right now there's a lot of stuff in one file in the tutorial and all split out in the guide.

**Comment by zeroasterisk** [comment]
Ideas:

Pass Meteor.user from container to page to components

Make a FlowRouter example app, with Accounts & Route infor passed into App, Layout, Containers, Pages, Components.

Make a ReactRouter example all, with Accounts stuff passed into Routes, App, Layout, Containers, Pages, Components.

Make an example which uses some common Meteor packages like simple schema, collection2, helpers, hooks, etc... Just so we can see how you would organize the modules and import *correctly*

I'm doing these things now, but I have no idea if I'm doing them right or not. *Guide me please :) *

**Comment by zayaisshawn** [comment]
Right now I'm playing with 2 apps, one following meteor guide. You can look at react branch of meteor todos app [here](https://github.com/meteor/todos/tree/react) for that. The other is based on mantra specs. I'd really like to stick with the official guide but it could definitely be improved by adding more samples in the react part.

**Comment by tmeasday** [comment]
See PR above + I updated the `react-meteor-data` README: https://atmospherejs.com/meteor/react-meteor-data
