### ISSUE TITLE
"import" throws syntax error

### ISSUE THREAD

**Issue by methodbox** [meteor/guide#367]
I believe your guide from here: http://guide.meteor.com/using-packages.html is missing a step.

I just upgraded an app, which coincidentally uses momentjs, so I followed your steps specifically, yet the "import" keyword isn't recognized:

Uncaught SyntaxError: Unexpected token import

Since I was upgrading, rather than doing a new app or fresh install of Meteor, I also ran ```meteor npm install --save meteor-node-stubs``` just in case.

I'm not clear what's missing here.

**Comment by tmeasday** [comment]
You probably just need to use the `ecmascript` package in your app.

**Comment by methodbox** [comment]
Guess what, I thought that was installed, but just did ```meteor list``` and it's not. Lol. Let's try that. I'll report back ;).

**Comment by methodbox** [comment]
Aaaand it works. Now I feel dumb. Thanks for the help, man!

**Comment by tmeasday** [comment]
No worries :)
