### ISSUE TITLE
Add Guide build instructions

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#382]
Add instructions to readme so that you can view html changes before submitting PRs

**Comment by tmeasday** [comment]
How's this: https://github.com/meteor/guide/blob/master/CONTRIBUTING.md#running-the-static-site-generator-locally

**Comment by lorensr** [comment]
Thanks 😊

I'm getting:

```
INFO  Start processing
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
WARN  No layout: index.html
WARN  No layout: index.html
```

and a blank web page

**Comment by tmeasday** [comment]
Oh, submodule. Updated

**Comment by lorensr** [comment]
you now need to `npm install hexo-server`, and maybe `hexo generate`, but now when I do `hexo server`, there's no `index.html`, only `index.md`

https://hexo.io/docs/server.html

**Comment by tmeasday** [comment]
@lorensr - what do you mean? I think these instructions are still correct: https://github.com/meteor/guide/blob/master/site/README.md#theme-development

**Comment by lorensr** [comment]
![image](https://cloud.githubusercontent.com/assets/251288/14798547/2abf1990-0b06-11e6-8448-1751cad85177.png)
