### ISSUE TITLE
Compare/recommend view layers

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#387]
I heard Geoff say on the podcast something like "use Blaze for quick prototyping and React for everything else", and I was looking for something similar on meteor.com that helped new people make the decision. The tutorial link just goes to the default Blaze version, and doesn't mention the others. Maybe that or somewhere else on meteor.com should change, but for adding to the Guide, should it go at the top of the User Interfaces article? 

Should this be the recommendation?

- blaze: small apps or quick prototypes
- angular: if you want to use ionic mobile framework
- react: everything else

Any other reasons to use angular over react?

**Comment by tmeasday** [comment]
I don't think we are quite ready to get into the view layer recommendation game. We could probably have some kind of comparison but it's pretty subjective.

I'm not sure, I definitely appreciate that it's not serving the "guide tells you what to do" goal.

**Comment by lorensr** [comment]
Okay, for comparison points, what about this? (I'm not v familiar w/ Angular)

1. blaze: handlebars html-like template syntax easy to get started with. 
1. angular: html with a relatively large list of [special syntax](https://angular.io/docs/ts/latest/guide/cheatsheet.html) for dynamic things like loops and click events
1. react: JSX - HTML and JS. easier to understand than angular syntax, since you know javascript, and more flexible (at least I would imagine so, since it's a whole language versus set syntax?)
1. react and angular's structure generally results in better ui components than blaze, and good components are easier to work with
1. in general, angular 2 and react have better performance [1]
1. react and angular have larger user bases. react has 40k gh stars, angular as 10k
1. react and angular codebases are more developed
1. react and angular have more open-source ui components
1. for mobile devs, if you want to do cordova ionic, angular 2. if you want native, do react native

[1] http://info.meteor.com/blog/comparing-performance-of-blaze-react-angular-meteor-and-angular-2-with-meteor

**Comment by tmeasday** [comment]
Yeah I think this is all pretty reasonable.

Maybe a "View Layers" section in the "User Interfaces" article?

**Comment by stubailo** [comment]
I'm down!

**Comment by lorensr** [comment]
Sorry Sashko, did you mean you're going to write it, or that you agree? ☺️

**Comment by stubailo** [comment]
I agree haha, done have time to write it though :)

**Comment by StanLindsey** [comment]
If React is becoming the preferred view library is it worth at some point (v1.4/1.5) swapping Blaze & React's role in the guide? Using React for all our view layer examples in the guide.
E.g. in the Methods article defining our 'simple html form' into a React Component.

Currently Meteor still ships with Blaze by default, but I know MDG are preferring React and maybe the guide should reflect/promote that as well?

**Comment by batjko** [comment]
I think that preference for React isn't quite official yet. Since Blaze remains the simplest way of creating (reactive) views in Meteor, it seems reasonable to keep recommending newbies (i.e. those for whom the guide is their entry point to learning Meteor) to start with that first.

However, I'd definitely agree that this comparison of view layers and their respective recommended use cases should be linked to prominently at place where Blaze is introduced. 
That way, it's clear to people why they are looking at Blaze, and where to find the React-based content if they'd like to skip to that.
