### ISSUE TITLE
Guidelines for content

### ISSUE THREAD

**Issue by queso** [meteor/guide#4]
We need to think about things like the 'voice' of the content, who the articles are written for, and what authors can and can't promote within their posts.

**Comment by jesseflorig** [comment]
It would make sense for the voice to remain the same as it is for the docs and getting started guides. Does it make sense for the default audience start at beginner and change depending on the topic?

As long as a product meets MDGs current best practices and doesn't compete with core directly, I'd think authors should be encouraged to promote solutions/resources.

**Comment by stubailo** [comment]
This gives some hint of the target audience:

> Focus on the intermediate developer - the guide is not for beginners who are writing their first app, and it's not for the super hackers that can code their way out of anything. The guide is for normal developers trying to get the job done.

My perception is that there is a lack of "intermediate" Meteor resources out there. There are tons and tons of "getting started" tutorials, and some super-advanced hacker tricks, but not too much of the bread-and-butter stuff. I'd say the most similar thing is Discover Meteor.

### Proposed article format

Each guide article should probably start with an approachable summary of the concept, and then go through the topics in the article in an order that's correlated with both importance to the developer and how easy it is to pick up. I think these actually coincide - hopefully things that are important for everyone to know are easy, and things that are only relevant for specific use cases can be a bit harder.

I think the easiest thing to do here is to write a sample initial guide and go from there?

**Comment by awatson1978** [comment]
I went through the Cookbook, and took a quick survey of the different types of articles in it.  Here's what I came up with:

- Article - text about some topic; may include opinionated discussion
- Checklist - a list of items to be completed in order; install scripts; etc.
- Component - code snippet for a particular UI component
- Diagram - architectural diagram or flowchart
- FAQ - general list of questions/answers
- Links - link dumps
- Overview - an introductory explanation of some system; often with diagrams
- Recipe - code snippet for accomplishing some task
- Reference - usually a reference list of some sort; eg; common error codes; directory structure
- Tutorial - article that teaches; a walkthrough of some sort
