### ISSUE TITLE
Links in guide broken

### ISSUE THREAD

**Issue by gregorybleiker** [meteor/guide#408]
When using one of the links in the guide (I noticed this with the "supported CSS pre-processors" link on http://guide.meteor.com/using-packages.html) it should take me to 
http://guide.meteor.com/build-tool.htm#css
but instead takes me to
http://guide.meteor.com/index.html#css

I am using Chromium, but am getting the same result in FF.

**Comment by tmeasday** [comment]
Fixed, thanks @gregorybleiker
