### ISSUE TITLE
Absolute vs relative import paths

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#411]
@stubailo mentioned this a few times in #222 – was a decision made? Atm we're mixing. I'd prefer absolute except perhaps when in same directory. Benefit of absolute is not having to think how many `..`s when writing, and for the reader of the contents of a file X (eg looking at Guide snippets) to be able to tell what the structure of the imports are without knowing the path of X. Con is sometimes more characters to type. 

So first and fourth blocks would change, but the middle two stay the same?

![image](https://cloud.githubusercontent.com/assets/251288/14933619/75c632d4-0e62-11e6-8ba8-80466317e39d.png)

**Comment by stubailo** [comment]
Yeah my main concern with absolute imports was that they are "non-standard", but most build systems allow configuring some sort of root so perhaps this isn't a concern.

**Comment by tmeasday** [comment]
Loren's suggestion works for me

**Comment by stubailo** [comment]
OK I'm down - so to sum it up it's:

> Use absolute import paths for everything, except when the module you're importing is in the same directory or a subdirectory of the current directory.

Which basically boils down to "no `../` in imports"? Or is there a case where you would want that?

**Comment by tmeasday** [comment]
I mean I can imagine a layout where you'd have a module that has subdirectories that reference each other. But not in our recommended FS structure.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
