### ISSUE TITLE
Communicate filename for some snippets

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#413]
Background: #412 
1. With comments:  `// foo.less`
   https://github.com/meteor/guide/pull/412/commits/924de16fe46372d12cc0628342dd7f0504719918
2. With accentuated extension snippet labels:
   https://github.com/meteor/guide/pull/412#issuecomment-216001683

If 2, then perhaps two different styles – one normal, and one accented for cases in which user needs to notice.

@dominicnguyen thoughts?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
