### ISSUE TITLE
SimpleSchema validation has changed, requires namedContext() before validate() now

### ISSUE THREAD

**Issue by cdeadlock** [meteor/guide#417]
The SimpleSchema.validate() references throughout the guide need namedContext() now

**Comment by stubailo** [comment]
@cdeadlock are you sure you aren't using a really old version of simple schema? It hasn't changed since december: https://github.com/aldeed/meteor-simple-schema

**Comment by cdeadlock** [comment]
Must be, my windows 10 is stuck on some old versions.
https://github.com/meteor/meteor/issues/6621#issuecomment-216713267
