### ISSUE TITLE
Forum vs Issue Guidelines

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#421]
I recently asked a question related to the Users and Accounts section of the guide on the related forum topic. But I'm wondering if I should have posted it here instead.

What's the difference between the forum posts and creating an issue here?

Adding this answer to the [guidelines for contributing](https://github.com/meteor/guide/blob/master/CONTRIBUTING.md) would be useful

**Comment by stubailo** [comment]
I don't think it matters really - I think we just want to make it as easy as possible to discuss and ask and answer questions. What do you think?

**Comment by tmeasday** [comment]
I think issue here should be restricted to things that aim to cause changes to the guide content. If it's a question, the forum seems best.

**Comment by merlinpatt** [comment]
I definitely agree with @tmeasday. Issues should be problems about: structure of the articles, misspellings, grammar, requests for new content, etc.

Forums should be used for: help with the topics, more specificity than the guide allows, code bugs.

The one issue with using the related forum posts is that they're already aged at this point, and if someone asks a question on them, I feel like it won't get answered because of that age. Also, the topic of the post isn't reflective of the question that is asked, so that also contributes to a lack of answers.

Perhaps it would help to have a `guide` category on the forums. I know that there's already the `help` topic but this would be even more specific help on just what's in the guide. If it goes beyond the scope of the guide, it gets recategorized to the more generic `help`.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
