### ISSUE TITLE
Testing stubbing

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#424]
we show how to mock a template helper and stub functions with simon, but what about an object? for a global object, this doesn't work:

```js
// foo-bar.test.js
Foo = {} // attempting to mock Foo
import 'foo-bar.js'
...

// foo-bar.js
Foo.bar = () => {...};

// foo.js (not included in the test)
Foo = {...}
```

gives `ReferenceError: Foo is not defined` in `foo-bar.js`. 

and what if it wasn't a global and `foo-bar.js` imported `Foo` – how do you mock an import?

**Comment by tmeasday** [comment]
I think in both cases you'd need to import `foo.js` in order to mock it.

In pure ES2015 import land, `foo-bar.js` is doing:

```js
import Foo from 'foo'; // 1
Foo.bar = ...
```

So your test would need to do 

```js
import Foo from 'foo';
// stub Foo's props
import 'foo-bar';
```

Or use a require-mocker like [Jest](https://facebook.github.io/jest/) to make line `// 1` act differently. Unfortunately things like Jest aren't really possible in Meteor right now, because of our non-standard require system, AFAICT.

In Meteor linker-land, theres

**Comment by lorensr** [comment]
Thanks! So no way currently to mock `Foo` itself, right? Like if this worked (doesn't b/c Foo is a const):
```js
import Foo from './foo.js';
Foo = {test: 'stubbed'}
import './foo-bar.js'
```

**Comment by lorensr** [comment]
What about adding this to the "Stubbing" part of [the unit test section](http://guide.meteor.com/testing.html#simple-unit-test):

If you're testing code that makes use of globals from outside the `imports/` directory, you'll need to import those globals. For instance if you have a global `Todos` collection and are testing this file:

```js
// logging.js
export const function logTodos() {
  console.table(Todos.find().fetch());
}
```

then you'll need to import `Todos` both in that file and in the test:

```js
// logging.js
import { Todos } from './todos.js'
export const function logTodos() {
  console.log(Todos.findOne());
}
```
```js
// logging.test.js
import { Todos } from './todos.js'
Todos.findOne = () => { 
  return {text: "write a guide"}
}

import { logTodos } from './logging.js'
// then test logTodos
...
```

**Comment by tmeasday** [comment]
That seems great @lorensr
