### ISSUE TITLE
Async methodology section

### ISSUE THREAD

**Issue by janat08** [meteor/guide#425]
There're a bunch of threads and topics spanning years recommending various things rellying on random packages some of them expecting npm require. I'd rather not see if any of those work without understanding much of it either.

TL:DR
https://forums.meteor.com/t/start-using-async-await-instead-of-promises-and-callbacks/17037/11
https://themeteorchef.com/snippets/synchronous-methods/#tmc-questions-comments

**Comment by lorensr** [comment]
We're got a section on wrapping server-side, let me know if anything can be clarified:

http://guide.meteor.com/using-npm-packages.html#async-callbacks

For client-side, I don't know what we should recommend. All I've done is the rare `async.parallel` with the  npm lib.

**Comment by janat08** [comment]
Yea, fair enough it has promises in them.Is that meant to be with promise libraries as in u still have to install something "This makes it very easy to serially call Promise-based libraries": the topic is misleadingly under npm packages to which I have apprehension as basic dev.

**Comment by stubailo** [comment]
@janat08 what is your usecase for asynchronous stuff, if it isn't about NPM? Mostly this stuff comes up when working with promise-based NPM packages, which is why we put it there.

**Comment by janat08** [comment]
Im agregatting a document array by datepicker parameters to use as a condition for event.

Would you recommend something as it's scary to blankly try and work with something adding that to a number of things you know you could screw up especially when you'll read that meteor initially had promises, then those got redacted, and then vaguely read into that promises are worse to something else at which point you get a github repo that mixes it up with promises and something else but gives the impression of being updated.

**Comment by stubailo** [comment]
Meteor does still have promises. The reality of JavaScript is that things become "outdated" very fast so you should just pick something and go with it!

It's a bit hard to tell from your comment exactly what you're referring to though, or how you arrived at the conclusion that Promises are the right concept for your goal.

**Comment by janat08** [comment]
I'd have to render the result as well, but then if Meteor has got promises or those features for async programming where does NPM come in, or using 3rd party packages.

**Comment by janat08** [comment]
Should I just use the stub provided to me by validated methods, it sounds like its failsafe.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
