### ISSUE TITLE
Following Factory import doesn't work

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#427]
Background: https://github.com/meteor/todos/issues/119

Our testing article does:

```
import { Factory } from 'meteor/factory';
```

Which gives this error on the client:

```
install.js:78Uncaught Error: Cannot find module 'meteor/factory'
```

Which makes sense because `factory` is not a package on atmo. However, this:

```
import { Factory } from 'meteor/dburles:factory';
```

Also doesn't work:

```
install.js:78Uncaught Error: Cannot find module 'meteor/dburles:factory'
```

@tmeasday

**Comment by tmeasday** [comment]
Isn't `Factory` a local Atmosphere package? You may need to `meteor add factory`?

**Comment by lorensr** [comment]
It is in todos, but what about for people just following the guide snippets?

**Comment by tmeasday** [comment]
Yeah, not ideal. I guess we need to update todos to use dburles factory
evebtually

**Comment by noahsw** [comment]
Why does https://github.com/meteor/todos use its own factory implementation?

**Comment by tmeasday** [comment]
A complicated and long winded reason that I think is no longer relevant @noahsw

**Comment by jakobrosenberg** [comment]
I'm copy pasting from the todos example to my own newly started project. The meteor/factory import confuses me.

**Comment by dburles** [comment]
For anyone still interested the todos example app now uses `dburles:factory`

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
