### ISSUE TITLE
Update Meteor Guide with Font Best Practices

### ISSUE THREAD

**Issue by joncursi** [meteor/guide#428]
Porting this over from https://github.com/meteor/meteor/issues/6903

There are many unanswered questions surrounding the recommended font usage within a Meteor app.

* Where should fonts be placed in the project structure?
* How should they be imported / loaded in a Meteor 1.3+ app?

[According to the Meteor Guide](http://guide.meteor.com/mobile.html):

> An important benefit of packaging up your web app as a Cordova app is that all your assets are bundled with the app. This ensures your app will load faster than a web app running on a remote server could, which can make a huge difference for users on slow mobile connections.

Does this mean that fonts will be bundled as well, if they are not loaded from a CDN?

Hoping for some suggestions / answers, and to ultimately see this information make it to the Meteor Guide.

**Comment by lorensr** [comment]
I think fonts just fall under the category of static assets covered in #429. Everything in `public/` will be bundled in Cordova. Am I missing anything? Thanks!

**Comment by joncursi** [comment]
Ah okay. Nope, let's handle in #429 then. Thanks.
