### ISSUE TITLE
Update Meteor Guide with Static Asset Best Practices

### ISSUE THREAD

**Issue by joncursi** [meteor/guide#429]
The only advice I've been able to find online on how to store and manage a project's image assets is to drop them in `public/`. In addition to this not being documented in the guide, putting images in `public/` has it's own challenges, namely caching / lack of asset fingerprinting.

I think the community could use some suggestions on static asset management best practices, and ultimately I would love to see an asset fingerprint solution arise, similar to the rails asset pipeline.

**Comment by lorensr** [comment]
the docs should mention public. looks like they don't – i'll add something saying to use it for all static assets.

here we talk about cdn:

http://guide.meteor.com/deployment.html#cdn

the css and js bundles names change when you change the code. is there any other type of caching/fingerprinting that would be helpful to talk about?

**Comment by joncursi** [comment]
That's a good write up on CDN, thank you. But if my web app is small, and I don't have a use case to pay for a CDN, I would hope that internally I could have an asset fingerprinting solution that "just works" when I deploy new versions of static assets under the same name. I.e I am a small business restaurant and my site is mostly image-based. I'm going to run into some serious trouble with users not seeing the latest images because older images with the same name will be cached on their machines. I guess this suggestion may be turning into more of a feature request.

**Comment by joncursi** [comment]
See: [What is Fingerprinting and Why Should I Care?](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark)

**Comment by lorensr** [comment]
Thanks for the link – Meteor does that for CSS and JS. For images, usually if you want a different image, you link to a different image file – is this not the case for your app? You might be able to make a package that does it using the Meteor build plugin api. 

More into on caching:

https://forums.meteor.com/t/24-hours-cache-expiry-on-static-resources/4633

Should be possible to set your own headers:

https://groups.google.com/forum/m/#!topic/meteor-talk/YbO0oUeazCI

And then bust them either with a query string or a build plugin.

On CDN pricing, Cloudflare has a free tier, and they just opened up websocket support to everyone.

**Comment by joncursi** [comment]
That is indeed the case for a Meteor app I've been working on. Imagine the homepage contains a bunch of hero shots. Maybe I'm using a plugin like [jQuery Vegas](https://vegas.jaysalvat.com/) and my images are named:

```
hero-shot-first.jpg
hero-shot-second.jpg
hero-shot-third.jpg
hero-shot-fourth.jpg
```

because I want them to execute in a defined order. I'd want to be able to swap images in and out under the `public/` directory and expect the cache to bust on deployment, without having to rename files and update my slideshow code to this:

```
hero-shot-first-breakcache.jpg
hero-shot-second-breakcache.jpg
hero-shot-third-breakcache.jpg
hero-shot-fourth-breakcache.jpg
```

and on next deployment to

```
hero-shot-first-breakcache-again.jpg
hero-shot-second-breakcache-again.jpg
hero-shot-third-breakcache-again.jpg
hero-shot-fourth-breakcache-again.jpg
```

I also do not want to automatically bust the cache every 24 hours because then my website will be perceived to be slow all the time (again, image-based site). The ideal behavior is to only bust the cache on deployment of new file versions, and to not have to rename files and update internal code to make that happen. Ala fingerprinting.

**Comment by lorensr** [comment]
I see, thanks. Might be possible with a build plugin? https://github.com/meteor/meteor/wiki/Build-Plugins-API

**Comment by lorensr** [comment]
Submitted the `public/` issue to the new docs repo: https://github.com/meteor/guide/issues/429

**Comment by lorensr** [comment]
Sorry, correct link: https://github.com/meteor/docs/issues/4
