### ISSUE TITLE
Acceptance test fixtures

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#431]
@tmeasday 

We recommend using:

`meteor test --full-app --driver-package tmeasday:acceptance-test-driver`

to be able to call your fixture methods. But the Guide defines those in:

`imports/api/generate-data.app-tests.js`

I got `method is not defined` error from my chimp tests until I moved my methods outside of imports. 

Question: should we change our recommended file structure, so that they can be used from both app-tests and acceptance tests? Like `fixtures/*.app-tests.js` or `test-methods/*.app-tests.js`

**Comment by tmeasday** [comment]
Doesn't running w/ `test --full-app` ensure that all `app-tests` files run?

**Comment by tmeasday** [comment]
I'm pretty sure this works w/ todos.. ? Or did at one point anyway :/

**Comment by lorensr** [comment]
*sigh* you're right, it works in todos. don't know what i was doing wrong. thanks 😜
