### ISSUE TITLE
Import chain not clear

### ISSUE THREAD

**Issue by abernix** [meteor/guide#436]
Moved from meteor/meteor.
@talkoren commented on [Wed May 11 2016](https://github.com/meteor/meteor/issues/7028)

The [app structure guide](http://guide.meteor.com/structure.html) does not elaborate the (non-trivial) import chain that it requires. Had to reach [this thread](https://forums.meteor.com/t/import-best-practices/20818/26) to figure it out. Opened this issue per @stubailo's request.

**Comment by tmeasday** [comment]
@talkoren I'm not sure I understand. What is the import chain?

**Comment by stubailo** [comment]
I think it's basically how a bunch of things have `index.js`, and why you need to import methods on the server, etc.

**Comment by talkoren** [comment]
Yep - all the different imports that are required in order to make an app work with the described structure (by 'chain' I was referring to how some imports depend on others).

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
