### ISSUE TITLE
Minimongo link is broken

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#442]
http://guide.meteor.com/collections.html#client-collections

Currently points to: https://www.meteor.com/mini-databases

**Comment by stubailo** [comment]
We could probably just remove the link, unless there's a good place currently where minimongo is explained.

**Comment by lorensr** [comment]
If the link was deleted and not just moved, maybe we should have a section
– we mention it a few places in the guide but don't explain

**Comment by DylanKojiCheslin** [comment]
there is an explanation in https://github.com/meteor/meteor/tree/devel/packages/minimongo   

I think a good stop gap to link to this instead.

**Comment by abernix** [comment]
Good idea.

1. Do you think linking [directly to the README](https://github.com/meteor/meteor/blob/devel/packages/minimongo/README.md) would be best or to the package (as you did)?
2. I think it should link to the [`master` branch](https://github.com/meteor/meteor/tree/master/packages/minimongo) (not `devel`).

**Comment by DylanKojiCheslin** [comment]
@abernix  
1. In the routing section there is a link to https://github.com/arillo/meteor-flow-router-helpers/ I was just trying to this example. however most links to packages reference the atmosphere link, not github, implying the guide intends to minimize unnecessary details. I think this supports linking to the README directly.   
2. totally agree, deve1 link was an oversight on my part.
