### ISSUE TITLE
Incorrect ESLint Setup Screenshot

### ISSUE THREAD

**Issue by abernix** [meteor/guide#444]
Moved over from meteor/meteor

@markoshust commented on [Fri May 13 2016](https://github.com/meteor/meteor/issues/7044)

I'm setting up eslinting from the new meteor code styling guide at http://guide.meteor.com/code-style.html

After following the instructions, WebStorm is complaining with the following error:

```
Cannot read config package: eslint-config-plugin:meteor/recommended
Error: Cannot find module 'eslint-config-plugin:meteor/recommended'
Referenced from: /Users/markshust/Sites/chanj/flow-frontend/.eslintrc.json
Error: Cannot read config package: eslint-config-plugin:meteor/recommended
Error: Cannot find module 'eslint-config-plugin:meteor/recommended'
Referenced from: /Users/markshust/Sites/chanj/flow-frontend/.eslintrc.json
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at loadPackage (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:309:28)

Process finished with exit code 1
```

---

@markoshust commented on [Fri May 13 2016](https://github.com/meteor/meteor/issues/7044#issuecomment-218939867)

Ah -- found my answer at https://github.com/airbnb/javascript/issues/465#issuecomment-129213642

This screenshot:
<img width="1031" alt="webstorm-configuration" src="https://cloud.githubusercontent.com/assets/437029/15236560/f0d1703e-1893-11e6-9b3a-381f12c0824a.png">

references the global ESLint package -- it should reference the local project eslint package.

**Comment by abernix** [comment]
I don't have this editor, so I don't fully understand – and I therefore do not have a new screenshot to provide either. 😁 

@markoshust Could you actually provide the correct screenshot in here?  Would be much appreciated!

**Comment by markoshust** [comment]
@abernix here you go:
![screenshot](https://cloud.githubusercontent.com/assets/437029/15251537/ee3179be-18f7-11e6-8381-568b6f59de0d.png)

**Comment by abernix** [comment]
For the record, @markoshust has signed the Meteor CLA on meteor/meteor/issues

My only concern here would be the "6.1.0" version of Node displayed might be potentially confusing.

**Comment by markoshust** [comment]
Here you go, I changed theme to default for consistency, and photoshopped the version number out (can see how that can be confusing)

![screenshot](https://cloud.githubusercontent.com/assets/437029/15288526/922e040e-1b39-11e6-9b95-b5bbdf2724af.png)
