### ISSUE TITLE
Publishing a Package

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#45]
The idea of this guide is to give some guidance about how to publish a package onto [Atmosphere](atmospherejs.com), to contribute and share with the community.
## Meteor Guide: Publishing a Package
1. Considering what's involved in publishing a package (i.e. do you have time to maintain it? Is it complete enough to be used by someone else?)
2. What should go in a single package, when should it be split?
3. Writing great documentation
4. Ensuring your package is solid/tested (especially in the face of public changes) 
   - Use [travis](https://github.com/arunoda/travis-ci-meteor-packages)
5. Licensing your code
6. Publishing the package to atmosphere + publicizing it?
7. How to maintain a package -- PRs + Issues
   - Be polite, don't be afraid to point people to the Meteor contribution guidelines if you want a repro

**Comment by tmeasday** [comment]
Questions on this one: 

 1. What is our recommendation on package CI? @yyx990803 is perhaps the most up-to-date on this?
 2. Do we have rules about licenses on Atmosphere? Is it implicit that it's free to use if it's up there?
 3. What's our recommended way to publicize a package? Forums? Crater.io? How do the cool kids do it these days?

**Comment by stubailo** [comment]
1. I bet Travis is the best for free stuff on GitHub - we looked at other options mainly for parallelism I think?
2. I don't know, this is probably one of those ask-a-lawyer things, but we should definitely recommend that people include a license. There's a related issue here: https://github.com/meteor/meteor/issues/5060
3. Probably the forums? Also, posting on github issue/forum threads about the issue your package solves can be effective.

**Comment by yyx990803** [comment]
I'd actually go for Circle even for free stuff, but since we already have established scripts (ones by Arunoda) for testing Meteor packages on Travis, we can keep using that. For small packages there isn't any significant difference (except Circle triggers the build much faster)

**Comment by tmeasday** [comment]
Thanks @yyx990803, we'll stick with @arunoda's thing for now then.

**Comment by stubailo** [comment]
Coming back to this, I think we should definitely recommend that people test their package both against the newest Meteor release and Meteor `devel` - and then give us a link to their badge so that we can keep tabs on which packages are broken by devel or something.

**Comment by tmeasday** [comment]
Does that actually work.. I mean how do we make the tests for every package out there run whenever devel changes?

**Comment by tmeasday** [comment]
@yyx990803 so there is an integration for circle out there: https://github.com/meteor/guide/issues/20#issuecomment-151307672

Should we recommend that then?

**Comment by dburles** [comment]
Another thing to note may be to remind developers to tag their releases in git.

**Comment by stubailo** [comment]
@tmeasday as a side project, I'm going to try to make it work (the testing against devel thing) I think it could be really valuable.

**Comment by yyx990803** [comment]
@tmeasday sure. Actually I think even just Arunoda's script will probably work on Circle with minimal changes.

**Comment by tmeasday** [comment]
Outline merged!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
