### ISSUE TITLE
Users are referred to useraccounts.meteor.com which is gone

### ISSUE THREAD

**Issue by BudgieInWA** [meteor/guide#462]
The article at http://guide.meteor.com/accounts.html has multiple links to useraccounts.meteor.com which is no longer available.

**Comment by lorensr** [comment]
@stubailo could we either reinstate (see https://github.com/meteor/guide/issues/409#issuecomment-217757139) or redirect the URL? 

@splendido below looks like the best place to redirect to?

https://github.com/meteor-useraccounts/core/blob/master/Guide.md

**Comment by lorensr** [comment]
Fixed by 172480d383fbcd5d2bc6503a4f38c146bc54030f thanks again for reporting 😊
