### ISSUE TITLE
React / Angular Equivalents of Blaze Examples

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#469]
Throughout the guide, there are a number of examples written using Blaze. For instance, [Calling a Method from a form](http://guide.meteor.com/methods.html#method-form). It would be great to have these examples written in React and Angular, and make them viewable with a tab interface. Eventually it would be cool to see an option to set the version of the guide to React, Angular, or Blaze, but that's a much later step.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
