### ISSUE TITLE
Make it possible to remove or rename the default mutator methods

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#47]
Needed for #9.

Currently, to make `insert`, `update`, and `remove` work on the client, every collection defines methods called `/collection-name/insert`, `/collection-name/update`, `/collection-name/remove`. There's no way to remove them.

It would be reasonable for people to want to define methods called this, especially with the code style we are prescribing. Also, since we are recommending for people to avoid allow/deny, these methods are useless and would clutter any list of app methods.

The best option would be for these methods to simply not exist unless allow/deny is used. That leaves an open question about `Meteor.users`, which has allow/deny rules defined by default, but if we removed the `profile` field that would no longer be the case. I would be happy if a future release of Meteor made `profile` opt-in.

**Comment by tmeasday** [comment]
I think ideally there'd be a way to opt out of allow/deny and thus these methods would never be created in the first place. I've no idea of the complexity of this though -- do you have an idea @stubailo?

**Comment by stubailo** [comment]
I think it shouldn't be too hard! Would allow/deny be a separate package then? What's the optimal UX?

**Comment by tmeasday** [comment]
How's this:

1. There are two packages: 
  - `allow-deny` that adds the methods, `Collection.prototype.insert/update/remove` on the client, `Collection.prototype.allow/deny` on the server.
  - `insecure` - which depends on the above but removes allow/deny (or whatever it does right now).

2. A new app comes with `insecure` turned on (shudder).

3. When you remove it, you have nothing, and you need to add `allow-deny` if you want it.
  - but maybe for a release or two we wire up `Collection.prototype.allow/deny` to print a warning that you need to add the `allow-deny` package.

The scary part is that packages can depend on `allow-deny`. I don't know what to do about that.

**Comment by stubailo** [comment]
> The scary part is that packages can depend on allow-deny. I don't know what to do about that.

One option could be - you have to declare that you are turning on `allow/deny` when you initialize the colllection. That way, a package can't accidentally turn it on?

I wonder if there's a market for collection "mixins"? Because the road we are heading down includes lots of configuration and even inheritance for collections, for example to make a validated collection. If there are many packages on atmosphere that add various features to collections, for example validation, basic security, default fields, collection helpers, etc, how are they supposed to do that without overriding the prototype or inheriting?

**Comment by tmeasday** [comment]
I think mixins make sense but maybe in a world where you inherit from mongo
collection, ala rails?

Anyway I suspect you'd want a way to turn allow/deny on for everything, at
least if consistency with the way current meteor works was desired. But
maybe that's not the case?

**Comment by tmeasday** [comment]
I guess the methods could be defined at the point you first call allow for
a collection too..

**Comment by stubailo** [comment]
Wow funny - there's already an issue for something similar on Meteor: https://github.com/meteor/meteor/issues/5096

**Comment by tmeasday** [comment]
That is in no way surprising ;)

**Comment by mitar** [comment]
+1

**Comment by stubailo** [comment]
First step PR WIP: https://github.com/meteor/meteor/pull/5559

**Comment by stubailo** [comment]
Going to close this since there is some work on Meteor, and it's not a blocker for the guide.
