### ISSUE TITLE
[cordova] Explain that device permissions must be requested at run-time

### ISSUE THREAD

**Issue by abernix** [meteor/guide#470]
Per meteor/meteor#6976, as well as:
- https://forums.meteor.com/t/resolved-android-marshmallow-runtime-permissions-for-microphone-and-local-storage/22149/4
- https://github.com/dpa99c/cordova-diagnostic-plugin/#android-runtime-permissions

It needs to be explained to people that they need to request permissions to use camera, microphone, filesystem, etc. at run-time.

(This is just what I'm gathering – I unfortunately do not know Cordova very well/at all, but I will try to get back to this eventually with a PR.  Just want to leave this here before it gets forgotten.)

**Comment by abernix** [comment]
Per @lorensr in meteor/meteor#6976:

@inspiraluna here are the three places to make note:

https://github.com/meteor/guide/blob/master/content/mobile.md

(I guess in the configuring-your-app section, saying how to do Android permissions in pre-6 and in 6)

https://github.com/meteor/mobile-packages/blob/master/packages/mdg:camera/README.md
https://github.com/meteor/mobile-packages/blob/master/packages/mdg:geolocation/README.md

**Comment by inspiraluna** [comment]
okey... I did it this morning! Hope its not too bad. ;)
please check...

**Comment by abernix** [comment]
This was fixed in #472 thanks to the great contribution by, @inspiraluna.  Thanks!

(Closing)
