### ISSUE TITLE
REST API article

### ISSUE THREAD

**Issue by MichaelSavin** [meteor/guide#474]
In this article, a standard approach for creating REST API shall be described

**Comment by lorensr** [comment]
Yeah, good idea 😊 And a GraphQL API at some point too

**Comment by hiiphop** [comment]
Can you tell me how to create REST API in meteor pls!

**Comment by lorensr** [comment]
For something simple, use one of these packages:

https://github.com/stubailo/meteor-rest

Or if you have more advanced needs:

https://github.com/kahmali/meteor-restivus

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
