### ISSUE TITLE
React native guide article

### ISSUE THREAD

**Issue by MichaelSavin** [meteor/guide#475]
Please, create guide from all of articles, packages are available for now.
https://github.com/meteor/meteor/issues/6807

**Comment by lorensr** [comment]
Hi Michael, for now all we have is the RN link in this section:

http://guide.meteor.com/ui-ux.html#mobile

There seems to be two main ways of doing it – the react-native-meteor "magic" way, and the redux way: https://medium.com/@spencer_carli/how-i-use-react-native-redux-and-meteor-b69b3875dc00#.ou5jlu9n9

If one of the maintainers becomes familiar enough with RN to write or review a RN article, we can do something more substantial. @martijnwalraven might do an article at some point, but I'm guessing it will be using Apollo

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
