### ISSUE TITLE
Importing methods to the client

### ISSUE THREAD

**Issue by leocavalcante** [meteor/guide#491]
Isn't importing methods to the client-side, as exemplified in the guide, a bad practice since it exposes the method body? This will make public business rules inside them.

**Comment by lorensr** [comment]
@leocavalcante good point. When you import a function, the whole file is added to the client bundle. We could be more explicit about that here:

https://guide.meteor.com/security.html#served-files

@tmeasday in our structure we have a single place for methods in `import/api`:

![image](https://cloud.githubusercontent.com/assets/251288/16435079/81218f24-3d61-11e6-8033-cdb9c37c2079.png)

should we add a `server/methods.js` and `server/methods.tests.js`?

**Comment by tmeasday** [comment]
Yeah, I'm as discussed in the [security section](https://guide.meteor.com/security.html#secret-code) in such cases you would write two copies of the method and put one in a server-only file. You don't *have* to put it in a `server` folder if you don't import it on the client, but it's probably the safest thing to do.

**Comment by leocavalcante** [comment]
Unfortunately this approach forces the use of global objects, right?

**Comment by lorensr** [comment]
Nope, from `client/main.js` you can:
```js
import { updateText } from '/import/api/lists/methods.js';
updateText.call
```
and `/import/api/lists/server/methods.js` will not be included in client js bundle.

**Comment by leocavalcante** [comment]
But at `/import/api/lists/methods.js` you must import `/import/api/lists/server/methods.js`.
It will thrown a `Cannot find module` error, 'cause '**/server**' paths are excluded from client bundle.

**Comment by lorensr** [comment]
> But at /import/api/lists/methods.js you must import /import/api/lists/server/methods.js.

I think the idea is to not import, and instead redefine a shorter, simpler method for the client without the sensitive business logic

**Comment by tmeasday** [comment]
Yeah, the key thing is to just name the two methods the same thing (with the `name` field)

**Comment by leocavalcante** [comment]
Hm! Right, got it. Basically splitting the method object to a `name` and `run` server code and a `name` and `call` client code, where `name` value is the same on both sides. So definitely to accomplish it without relaying on a global object is to relay on a constant (`name` property value).

I found my self on a constant sort of thing borrowing `actions` and `actionTypes` naming stuff from Redux.

```js
// imports/actionTypes.js
export const UPDATE_TEXT = 'todos.updateText'
```
```js
// imports/actions.js
import { Meteor } from 'meteor/meteor'
import { UPDATE_TEXT } from './actionTypes'

export const updateText = (text) => {
  Meteor.call(UPDATE_TEXT, text)
}
```
```js
// server/methods.js
import { Meteor } from 'meteor/meteor'
import { UPDATE_TEXT } from '/imports/actionTypes'

Meteor.methods({
  [UPDATE_TEXT](text) {
    console.log(text)
  }
})
```
```js
// client/main.js
import { Meteor } from 'meteor/meteor'
import { updateText } from '/imports/actions'

updateText('foo')
```
