### ISSUE TITLE
Talk about React Perf Tools

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#493]
https://github.com/meteor/guide/pull/263#issuecomment-229212246

**Comment by toinevk** [comment]
@lorensr given React Performance Tools have been deprecated - would it make sense to use [profiling-components-with-the-chrome-performance-tab](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) instead?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
