### ISSUE TITLE
Which top-level fields are free to use in Meteor.users collection?

### ISSUE THREAD

**Issue by malaire** [meteor/guide#516]
"Users and Accounts"[1] tells that
> The best way to store your custom data onto the Meteor.users collection is to add a new uniquely-named top-level field on the user document.

but doesn't tell which top-level fields can be used, i.e. will never be used by Meteor.

[1] https://guide.meteor.com/accounts.html

**Comment by lorensr** [comment]
Thanks, good idea. 

@tmeasday is this a complete list of top-level user fields that might be used by Meteor? 

```
_id
createdAt
services
profile
emails
username
```

**Comment by tmeasday** [comment]
Sounds right @lorensr. I'm sure someone will tell us if we forgot something :)
