### ISSUE TITLE
Could use more clarification on password resets, account verification, etc

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#523]
Specifically regarding this:
https://github.com/meteor/guide/blob/master/content/accounts.md

> Here's how you would use one of these functions:

``` js
Accounts.onResetPasswordLink((token, done) => {
  // Display the password reset UI, get the new password...

  Accounts.resetPassword(token, newPassword, (err) => {
    if (err) {
      // Display error
    } else {
      // Resume normal operation
      done();
    }
  });
})
```

But in the context of React, things are a bit trickier. Where does this function call go?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
