### ISSUE TITLE
TypeScript section

### ISSUE THREAD

**Issue by ghost** [meteor/guide#531]
We are a lot of people who like the improved intellisense, and the types, that TypeScript bring to the table.

I therefore suggest that the guide should have a TypeScript section showing how to install TypeScript, and how interfaces can be used when creating React components.

And of course explain how Typings and type declarations work.

Any comments/opinions on this are very welcome. I would like to hear what you guys think before I spend time making a draft.

**Comment by abernix** [comment]
I'll actually leave this open until we decide to open other sub-tasks.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
