### ISSUE TITLE
Suggestion: Provide Check/Match Validation Example for Meteor Method Validations

### ISSUE THREAD

**Issue by JeremyIglehart** [meteor/guide#554]
I know that `check/match` are "on the way out" in some people's hearts...

But [while simple-schema is moving from 1.0 to 2.0](https://github.com/aldeed/meteor-simple-schema/issues/640#issuecomment-241933838) and until 2.0 is actually stable for production use - a stable alternative is really needed.

I'm new to Meteor, so I reference the guide - A LOT and it's really great work.  I thought that maybe this could make it even better for those coming after me.

It took me a really long time before I figured out a way to work around this.

In the sections:

https://guide.meteor.com/methods.html#advanced-boilerplate
https://guide.meteor.com/methods.html#validated-method

There is no alternative to simple-schema given, when a custom check/match function is a completely acceptable alternative.

My suggestion is simple - let's provide another example of a meteor method in these two places that demonstrates the use check/match for a simple meteor method.

I could possibly provide an example, but might need help editing the PR to make sure it's worthy for the guide.

**Comment by lorensr** [comment]
Does 1.x still work? If so, my inclination would be to wait and switch when
they release a 2.0

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
