### ISSUE TITLE
[Collections and Schemas] Not clear what Lists is

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#555]
https://guide.meteor.com/collections.html#schemas

With regards to:

```js
Lists.schema = new SimpleSchema({
  name: {type: String},
  incompleteCount: {type: Number, defaultValue: 0},
  userId: {type: String, regEx: SimpleSchema.RegEx.Id, optional: true}
});
```

`Lists` is not mentioned before this point, so it's not clear what it is. Is it a `Mongo.Collection`? Something else? Can we attach schemas directly onto the collection (even if it has no effect without the `collection2` package), just for convenience?

**Comment by abernix** [comment]
@ffxsam Curious what you think about this clarification.  If you look in the paragraph below, it will actually explain the reasoning for doing so. :)

**Comment by ffxsam** [comment]
I like it! 👍  Just thinking from the perspective of a newbie. :)
