### ISSUE TITLE
Next and Previous pages bottom links are incorrect

### ISSUE THREAD

**Issue by kvetoslavnovak** [meteor/guide#556]
For example:

page Code Style https://guide.meteor.com/code-style.html has link to page 
NEXT -> Collections and Schemas.
but it should be Application Structure

page Application Structure https://guide.meteor.com/structure.html has links to pages
PREVIOUS <- Security and NEXT -> Testing
but previous is Code Style and next is Migrating to Meteor 1.4

**Comment by bengott** [comment]
I just noticed this too. I would expect that hexo uses the `order` number in the front matter block at the top of each article to generate the Previous and Next links, but maybe I'm wrong, because the links are incorrect even though the order is correct? Also, I see that that the sidebar order is defined in [_config.yml](https://github.com/meteor/guide/blob/master/site/_config.yml)... Perhaps I'm missing something. I'll try to dig into it later.

**Comment by bengott** [comment]
I narrowed it down to this .ejs file in the hexo-theme-meteor submodule: https://github.com/meteor/hexo-theme-meteor/blob/230dae5b64b4d1736cd43aab23a21258fc4040a7/layout/page.ejs#L76

The list of pages isn't being sorted correctly, which results in the incorrect Previous/Next links. There are also two redirect placeholder pages that end up in the list as `undefined`. Not sure yet if those are messing up the sort. Also, I'm not familiar with the `.find({}).sort({order: 1})` syntax... It actually kind of looks like a MongoDB query. Is this .ejs-specific? I did a quick search, but didn't have much luck. Perhaps someone more familiar with this file could chime in? @tmeasday @dominicnguyen @stubailo

**Comment by stubailo** [comment]
The sidebar is defined with config, and the previous and next buttons are defined by the order field. I think we should switch to using config for everything-as far as I know order came first and then we added the sidebar thing, and it seems redundant now.

**Comment by bengott** [comment]
Good idea.. much more straightforward that way. I'll work on a PR to do that.

**Comment by stubailo** [comment]
That's here: https://github.com/meteor/hexo-theme-meteor

**Comment by bengott** [comment]
Right, I'll do the PR on that repo. And then we'll need to bump the theme submodule here, eh?

**Comment by stubailo** [comment]
Yeah, we have like 10+ of these sites at this point, so we'll handle it.

**Comment by bengott** [comment]
PR submitted.
https://github.com/meteor/hexo-theme-meteor/pull/28

Perhaps we should also remove all the front matter `order` fields to reduce ambiguity and possible confusion? (assuming they're not used for anything else...)

**Comment by stubailo** [comment]
Yeah once that is merged we should definitely remove those, since they are not used for anything else.

**Comment by tmeasday** [comment]
👏

**Comment by bengott** [comment]
yay, git submodules! ;)
