### ISSUE TITLE
There is no pathFor template helper in flow-router by default?

### ISSUE THREAD

**Issue by lehtu** [meteor/guide#561]
Hi,

I just found problem in the documentation: [useraccounts-customizing-routes](https://guide.meteor.com/accounts.html#useraccounts-customizing-routes)

There is this section:
```
<div class="btns-group">
  <a href="{{pathFor 'signin'}}" class="btn-secondary">Sign In</a>
  <a href="{{pathFor 'join'}}" class="btn-secondary">Join</a>
</div>
```
What I found is that you need to have something like [arillo:flow-router-helpers](https://atmospherejs.com/arillo/flow-router-helpers) installed to get pathFor template helper.

Cheers!

**Comment by abernix** [comment]
Thanks for reporting this!  I opened PR #570 to hopefully clear this up.  Can you take a look and see if that change would have made this more clear for you?
