### ISSUE TITLE
Unclear when to import with name of object

### ISSUE THREAD

**Issue by lucfranken** [meteor/guide#568]
While following the tutorial: https://www.meteor.com/tutorials/blaze/collections

As a user new to Meteor and imports.

I see two examples in 3.2 and 3.3:

Server:

`import '../imports/api/tasks.js';`

Client: 

`import { Tasks } from '../api/tasks.js';`

So I lookup how that works in the guide: https://guide.meteor.com/structure.html#intro-to-import-export

I see no examples of the client way of importing Tasks. I only see the server example. At: https://guide.meteor.com/structure.html#importing-from-packages I see the structure as shown in client but that has to do with packages.

As a new user it is unclear to me why I should use a different syntax on server and client.

And in this case also I don't know the correct reasoning for it.

Test results:
- Format of client works on both
- Format of server works only on server

So why would I ever use that format on server? The user needs some guidance here on why it is better to use that format on the server OR the tutorial should just use the same format when it doesn't really matter.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
