### ISSUE TITLE
Update 'factory' to use published repo

### ISSUE THREAD

**Issue by abernix** [meteor/guide#576]
This is dependent on meteor/todos#193 but this was a problem identified originally in the in the docs repo.

---

@Denly commented on [Mon Oct 17 2016](https://github.com/meteor/docs/issues/96)

import { Factory } from 'meteor/factory';
should be 
import { Factory } from 'meteor/dburles:factory';
in all related test code ex. https://guide.meteor.com/testing.html#simple-react-unit-test
not sure it is the problem or my setting tho. my meter has no meteor/factory

---

@abernix commented on [Tue Oct 18 2016](https://github.com/meteor/docs/issues/96#issuecomment-254488590)

Thanks for reporting this issue!

I'm guessing this code sample was meant to refer to the `factory` package which is [locally installed in the React `todos` example app](https://github.com/meteor/todos/tree/react/packages/factory).

Someone else would need to clarify if it was okay to use `dburles:factory` here in this example because I'm not sure what the reason is for the local `factory` package - but you're right, this snippet wouldn't have access to it!

---

@hwillson commented on [Tue Oct 18 2016](https://github.com/meteor/docs/issues/96#issuecomment-254496651)

No, they can't be directly swapped. The todos `factory` package is different. There was some discussion about merging the todos `factory` and  `dburles:factory` packages together in meteor/todos#119, but for now that work has been put on-hold.

---

@abernix commented on [Tue Oct 18 2016](https://github.com/meteor/docs/issues/96#issuecomment-254501305)

Ah, I see.  Ok, so I wonder for the time-being if the best issue would be to either:
1. Link to the [`TodoItem.tests.js` file itself](https://github.com/meteor/todos/blob/e2b367ec145be9cf03b215cea3430626f222f0b6/imports/ui/components/TodoItem.tests.js) so it has some context; or
2. Put a JS-style code comment above those lines, indicating that they are local packages.

🤔 

(Also, I guess this entire conversation should be on the [meteor/guide](https://github.com/meteor/guide/issues) repo.)

---

@hwillson commented on [Tue Oct 18 2016](https://github.com/meteor/docs/issues/96#issuecomment-254503593)

I like the idea of implementing both 1 & 2. This question has come up a few times on the forums as well, so the more context we can provide the better!

---

@tmeasday commented on [Tue Oct 18 2016](https://github.com/meteor/docs/issues/96#issuecomment-254633307)

I think we should switch to using the public package if possible, especially in the guide. 

---

@hwillson commented on [Wed Oct 19 2016](https://github.com/meteor/docs/issues/96#issuecomment-254780765)

Thanks @tmeasday - as a super quick workaround I can create a public/published version of the todos `factory` package, and fire in PR's to update todos and the Guide. This is a quick fix - the better longterm fix would be to continue with the ideas mentioned in meteor/todos#138. In the short term however, the quick fix will at least help reduce some confusion. Does this sound okay?

---

@tmeasday commented on [Thu Oct 20 2016](https://github.com/meteor/docs/issues/96#issuecomment-254968420)

Sure thing @hwillson 

---

@hwillson commented on [Thu Oct 20 2016](https://github.com/meteor/docs/issues/96#issuecomment-255072140)

Great - I've created meteor/todos#193 to track this work.

**Comment by dburles** [comment]
I think this has been resolved @abernix

**Comment by dburles** [comment]
Just came across https://github.com/meteor/guide/pull/598 so *almost* resolved I guess :)

**Comment by abernix** [comment]
Thanks, @dburles 😄
