### ISSUE TITLE
Example app: To-Dos or Microscope?

### ISSUE THREAD

**Issue by SachaG** [meteor/guide#58]
Here's a thought: what about using Microscope as an example app, instead of to-dos? It's a little more complex, so it features a lot of concepts that are not present in To-Dos (for example, pagination). And it's also an app that many people are already familiar with.

**Comment by stubailo** [comment]
I will defer on this decision to @tmeasday, since he knows much more about microscope than I could ever find out.

**Comment by tmeasday** [comment]
I guess we did Todos
