### ISSUE TITLE
Using npm module as dependency for meteor package

### ISSUE THREAD

**Issue by harishreddy-m** [meteor/guide#594]
Npm.depends({}) in package.js is suggested in guide.But, this is not working.
Meteor version : 1.4.2.3
Created an issue in meteor project 
https://github.com/meteor/meteor/issues/8200
More details provided in the link above

**Comment by abernix** [comment]
You'll note that the Meteor guide provides a very specific instruction for using this:

> Use `Npm.depends` at the top level of your `package.js` file

I wrote a bit of an extensive write-up about the problem in https://github.com/meteor/meteor/issues/8200#issuecomment-270723863, but I'm closing this as the Guide is accurate.  The issue shall remain open.

Thanks!
