### ISSUE TITLE
Another example to look for the Research

### ISSUE THREAD

**Issue by VladShcherbin** [meteor/guide#6]
While this is still in discussion, we can have a look, how similar is done in [Laravel framework](https://github.com/laravel/laravel), which is deeply loved by a lot of php devs.

The [documentation](http://laravel.com/docs):
- **is divided into sections and pages**. Makes it easy to find what you need, goes from basic to advanced things.
- **has framework versions** (divided by gh branches). Even the navigation sidebar changes from version to version and has different sections.
- **is held in a separate [repository](https://github.com/laravel/docs)**. Easy to contribute, maintain and see the differences from version to version. *(3000+ commits, 400+ contributors)*
- **has search input box**. Easy to find what you need when you are already in the docs.
- **has great seo**. Google `laravel xxx` - 99% you get to the docs.

The website is also held in an open [repository](https://github.com/laravel/laravel.com) so that everyone can see, how it is build. It is also updated to the latest version of the framework.

**Comment by stubailo** [comment]
Wow, I love the styling. One thing I haven't quite been able to decide is - how complicated should the navigation be? Is the amount they have sufficient, and then the rest is done through the table of contents of the article? Or should the sidebar have more fine-grained navigation?

**Comment by VladShcherbin** [comment]
@stubailo I don't think we need more navigation that this - it will be hard to view the whole navigation list to find what you need. Or we will even need to use `cmd + F`.

Instead, we need to think about the section names and ask a question - where will you probably try to find what you need. In each section there is a table of contents with sub-sections with hashtags and even more sub-sub-sections if you need. For example:

- [ORM Relations](http://laravel.com/docs/5.1/eloquent-relationships)
  - [sub] [Defining Relations](http://laravel.com/docs/5.1/eloquent-relationships#defining-relationships)
    - [sub sub] [One to Many](http://laravel.com/docs/5.1/eloquent-relationships#one-to-many)

There is also a great search bar - you can write what you need and it will show this section:
<img width="696" alt="screen shot 2015-10-06 at 7 37 36 pm" src="https://cloud.githubusercontent.com/assets/6711845/10315236/c03ab61c-6c61-11e5-9b34-1af163df964a.png">

And you can always google it, it will always be in the top 3 and will have the link to this subsection. `laravel one many`:
<img width="520" alt="screen shot 2015-10-06 at 7 34 16 pm" src="https://cloud.githubusercontent.com/assets/6711845/10315180/5fe92eba-6c61-11e5-9292-8ef2868d2141.png">

**Comment by stubailo** [comment]
OK, I'm pretty convinced. I agree that it would be terrible if you needed to navigate the table of contents via Ctrl-F.
