### ISSUE TITLE
Reference meteor create --full option at the Example Directory Layout section

### ISSUE THREAD

**Issue by aliogaili** [meteor/guide#615]
[PR7807 ](https://github.com/meteor/meteor/pull/7807) introduced new options for the meteor create command. Executing ``` meteor create help ```  will output the following: 

> Options:
  --package  Create a new meteor package instead of an app.
  --example  Example template to use.
  --list     Show list of available examples.
  --bare     Create an empty app.
  --full     Create a scaffolded app.

Since the Meteor Guide is recommending the full option, it might be useful to include the following statement to the [Example Directory Layout](https://guide.meteor.com/structure.html#example-app-structure): 

> To scaffold an app with similar structure, you can use ```meteor create appName --full ```

Or something along those lines.

**Comment by lorensr** [comment]
Thanks for the suggestion!

**Comment by brandoncanaday** [comment]
great suggestion, and glad I saw that line... I was about to manually create that structure and just run 'cp .meteor_template/' whenever I wanted to start a new project
