### ISSUE TITLE
Make it easier to find MongoDB hosting advice

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#620]
This section is super hard to find: https://guide.meteor.com/deployment.html#galaxy-mongo

I think we should make it a more prominent heading.

**Comment by lorensr** [comment]
I had the same thought! Fixed by #612

![image](https://cloud.githubusercontent.com/assets/251288/25447641/f68f7e1e-2a83-11e7-9f61-19f481c3902b.png)
