### ISSUE TITLE
Mention that local packages still need to be added to be used

### ISSUE THREAD

**Issue by hwillson** [meteor/guide#623]
When an application wants to use a local package, that local package first needs to be "added" to the application, using something like `meteor add`, modifying the `.meteor/packages` file by hand, etc. The fact that local packages aren't added automatically has caused some issues/grief for developers. Adding a small note in the Guide, likely under the [Using Atmosphere Packages](https://guide.meteor.com/using-atmosphere-packages.html) section, that mentions local packages must be added (when needed), should help clear up this confusion.

For the full backstory on this request, see meteor/meteor#3237. Thanks!

**Comment by abernix** [comment]
Hmm, we don't even really mention the concept of an unpublished Atmosphere package, do we?

We do have this section on Overriding Atmosphere packages though:
https://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages
