### ISSUE TITLE
Named Client Side Only Collections

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#633]
Per [this issue](https://github.com/meteor/meteor/issues/3825), it seems that having named client collections is supported but undocumented with the following

```
new Mongo.Connect('name', { collection: null })
```

I feel the best place to put this would be under the [Local Collections](https://guide.meteor.com/collections.html#local-collections) section, but my fear is that it would it likely be confusing for newcomers who are just reading through the guide.

Perhaps a simple warning or an "Advanced" subheader would do the trick?

**Comment by lorensr** [comment]
Thank you 😊
