### ISSUE TITLE
Update mobile guide for Cordova compatibility version feature

### ISSUE THREAD

**Issue by skirunman** [meteor/guide#636]
A new feature to support overriding of blocking hot code reload was added in Meteor 1.4.4.2 as per this PR https://github.com/meteor/meteor/pull/8581 and as documented in this issue https://github.com/meteor/meteor/issues/7030 

Opening this issue just to make sure that how to use this feature gets added to the guide.

**Comment by mikepaszkiewicz** [comment]
I'm currently experimenting with getting this working on my latest builds, but haven't been able to get it working. Would be happy to contribute to the docs once I fully grasp it. @skirunman have you had any luck using this new feature?

**Comment by skirunman** [comment]
No, we are not using this feature at this time.

**Comment by skirunman** [comment]
Closing as handled here:
https://guide.meteor.com/mobile.html#controlling-compatibility-version
