### ISSUE TITLE
Figure out how to badge a package against `master` and `devel`

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#64]
I think this is a code ticket? I'm not quite sure what would be involved here. Do we need to work with the publisher of the CI integration?

**Comment by tmeasday** [comment]
See https://github.com/meteor/guide/issues/45#issuecomment-151215004

**Comment by stubailo** [comment]
There's a good thread about it here: https://forums.meteor.com/t/get-notified-when-your-package-breaks-on-new-meteor-versions/12529
