### ISSUE TITLE
Document how to properly use dynamic expressions with imports

### ISSUE THREAD

**Issue by hwillson** [meteor/guide#641]
This has come up several times now in `meteor/meteor` issues. We should consider documenting how to leverage dynamic expressions with `import`'s. A detailed explanation of how to do this can be found in https://github.com/meteor/meteor/pull/8327#issuecomment-280876264, and https://github.com/meteor/meteor/issues/8744 is an example of one of the recent issues that outline the confusion around this.

**Comment by dr-dimitru** [comment]
Usage on importing core meteor packages and/or atmosphere packages should be mentioned too, see https://github.com/meteor/meteor/issues/8745

**Comment by coagmano** [comment]
So is the current advice if you need to do dynamic imports using an expression is to use a whitelist?

What would a whitelist look like? Like this?
```
if (false) {
    import('meteor/foo')
    import('bar')
    import('meteor/baz:baz')
}
```

**Comment by chrisbutler** [comment]
i think getting this stuff documented ASAP is really important... i'm willing to help in any way i can

**Comment by toinevk** [comment]
@hwillson would this not be better suited to the API rather than the guide?

**Comment by hwillson** [comment]
@toinevk Yes, I think so! I just wanted to create a placeholder for this idea, so for some reason I picked the Guide repo. I've moved this over to https://github.com/meteor/docs/issues/394. Thanks!
