### ISSUE TITLE
Replace Kadira Analytics with Galaxy APM

### ISSUE THREAD

**Issue by lightningboss** [meteor/guide#645]
In the past months, kadira was shut down. The guide [doesn't reflect that yet](https://guide.meteor.com/deployment.html#kadira).

It should be updated to show alternatives or to call attention to Galaxy's live monitoring.

**Comment by lorensr** [comment]
Thanks @lightningboss 😊 

Maybe @rohit2b would be a good person to replace the Kadira section with a Galaxy APM section?

**Comment by rohit2b** [comment]
Thanks! I'll take this.

**Comment by greggman** [comment]
#665

**Comment by abernix** [comment]
Fixed by #665.  Thanks, @greggman!
