### ISSUE TITLE
Package page for reactive-var but not reactive-dict

### ISSUE THREAD

**Issue by coagmano** [meteor/guide#654]
Since there's a docs page for [reactive-var](http://docs.meteor.com/api/reactive-var.html), should we add one for reactive-dict?

I'm of the opinion that all packages that [ship with meteor](https://github.com/meteor/meteor/tree/master/packages) should be included in the api docs

If there's interest I can draft something based on ReactiveVar?

**Comment by hwillson** [comment]
Hi @coagmano - yes, we definitely should, but this is already being tracked in the `meteor/docs` repo. See https://github.com/meteor/docs/issues/52. Thanks!

**Comment by coagmano** [comment]
Cheers, I'll follow that one
