### ISSUE TITLE
How To Migrate Meteor 1.2 To Meteor 1.5 Version

### ISSUE THREAD

**Issue by salimakhtar786** [meteor/guide#658]
My Meteor application ( that is in Blaze ) currently running @1.2 version.

I want to migrate it into Meteor 1.5 version.

Is there any need to migrate into 1.3 then 1.4 first and then 1.5 Meteor version or can I migrate directly into Meteor 1.5 version?

What should I do?

**Comment by abernix** [comment]
This is explained in the [Migration Guide for Meteor 1.5](https://guide.meteor.com/1.5-migration.html).  It's not mandatory to upgrade to 1.3 and 1.4 first, but there are very important steps that you need to take – so you should read the guide, including the Migrating to 1.3 and 1.4 guides, which should have all the details (including this specific question). :smile:
