### ISSUE TITLE
Accounts base recommends non-existent blog for API help

### ISSUE THREAD

**Issue by levithomason** [meteor/guide#663]
The [`accounts-base`](https://guide.meteor.com/accounts.html#accounts-base) docs note there is no documentation for "An API for registering new login handlers".  In lieu, users are pointed to the blog at meteorhacks.com.  However, that site doesn't exist either.

You can see the source for the Accounts docs [here](https://github.com/meteor/guide/blame/master/content/accounts.md#L33).

**Comment by hwillson** [comment]
Thanks @levithomason - it's quite a shame that the meteorhacks.com site and all of its great content was taken down. You can still see the [linked to article using the wayback machine](https://web.archive.org/web/20160913210817/https://meteorhacks.com/extending-meteor-accounts), but the Guide should definitely be updated.

**Comment by levithomason** [comment]
Indeed, thanks for the wayback link also.

**Comment by lorensr** [comment]
See also:

client: [Accounts.callLoginMethod](https://github.com/meteor/meteor/blob/201c767b317dd6d03476436ce6161aa8159a1fe5/packages/accounts-base/accounts_client.js#L221-L230)

server: [Accounts.registerLoginHandler](https://github.com/meteor/meteor/blob/201c767b317dd6d03476436ce6161aa8159a1fe5/packages/accounts-base/accounts_server.js#L417-L434)

**Comment by StorytellerCZ** [comment]
Currently the links use archived version, but there is a lot of space for improvement here. If anyone wants to take on this then please go ahead.
