### ISSUE TITLE
[React] version issues

### ISSUE THREAD

**Issue by merlinpatt** [meteor/guide#667]
Right now the guide tells you to install react, without providing a version. That means that currently you will end up with React 16.

But later on in the guide, it tells you to install react-mounter, which requires a peer dependency of React 15.

While I've put in a [PR for react-mounter](https://github.com/kadirahq/react-mounter/pull/30) to add React 16 as a peer dependency, that's not an ideal solution for the guide, especially as it grows and expands. What happens when multiple things are behind on the current version of React?

So what's a good solution to this?

The quickest fix would be to add a version to everything but that's not ideal. It doesn't scale well for maintenance and it's possible that the guide may end up recommending a version with a bug that gets fixed later.

Another quick fix might be to just add a warning saying to follow the npm recommendations but that would also lead to issues, especially if different packages require different versions.

Thoughts on a possible better solution?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
