### ISSUE TITLE
juliancwirko:postcss is not maintained anymore

### ISSUE THREAD

**Issue by mitar** [meteor/guide#668]
Sadly: https://github.com/juliancwirko/meteor-postcss/

I think this just shows how postcss should probably be rolled into the Meteor proper. There is no easy way to do autoprefixing anymore now, and there are also [known issues](https://github.com/meteor/meteor/issues/7075) with current CSS minimization.

I would suggest that guide adds at least a warning that juliancwirko:postcss is not maintained anymore.

**Comment by hwillson** [comment]
Regrading `postcss` being rolled into Meteor, this PR is related (as a first step anyways): https://github.com/meteor/meteor/pull/9263

**Comment by StorytellerCZ** [comment]
The package is now maintained by MCP, so we don't have to change anything anymore.
