### ISSUE TITLE
Code for react router not working

### ISSUE THREAD

**Issue by medihack** [meteor/guide#681]
The [code](https://guide.meteor.com/react.html#using-react-router) for `react-router` doesn't seem to work. Could it be that it is for version 3 of the react-router (and not the current version 4)? It is really hard to find out such things when there is no hint at all in the guide what versions are used :-(

**Comment by klaussner** [comment]
What error are you getting? The guide has already been [updated for the new version `react-router`](https://github.com/meteor/guide/pull/625).
