### ISSUE TITLE
Show how to use local NPM and Atmosphere packages

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/guide#682]
Coming from [this comment](https://github.com/meteor/meteor/issues/8444#issuecomment-349003579).

Suggestions:
 1. How to add local Atmosphere package
 2. How to add local NPM package
 3. How to add local NPM package into local Atmosphere package

#### Local Atmosphere packages
```shell
# Go to your Meteor App directory
cd meteor_app
# Create and go to projects directory
mkdir projects
cd projects

# Option 1: Link cloned or other local package
ln -s /full/path/to/package/directory

# Option 2: Create new project
meteor create --package package-name
```

##### Git (package.*json*):
```json
{
  "name": "my app",
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "fs-extra": "https://github.com/jprichardson/node-fs-extra/archive/4.0.2.tar.gz"
  }
}
```

##### Local (package.*json*):
```json
{
  "name": "my app",
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "fs-extra": "file:///full/path/to/local/npm/package"
  }
}
```

##### Git (package.*js*):
```js
Npm.depends({
  "fs-extra": "https://github.com/jprichardson/node-fs-extra/archive/4.0.2.tar.gz"
});
```

##### Local (package.*js*):
```js
Npm.depends({
  "fs-extra": "file:///full/path/to/local/npm/package"
});
```

I'm ready to send a PR, once suggestion is approved.

**Comment by lorensr** [comment]
Looks good, also overlaps some with https://guide.meteor.com/writing-npm-packages.html#including-in-app

Can you do relative file paths for npm?

**Comment by dr-dimitru** [comment]
Hello @lorensr ,

> Can you do relative file paths for npm?

Yes, it just should start with `file://./` - [here is example](https://github.com/VeliovGroup/spiderable-middleware/blob/master/package.json#L50)

**Comment by dr-dimitru** [comment]
> https://guide.meteor.com/writing-npm-packages.html#including-in-app

Thank you for this link, completely forgot about `npm link` command :)
I gusess we can use it instead of typing `file://`, but at the same time, typing it in is more visual approach

**Comment by lorensr** [comment]
I like giving all the options

**Comment by dr-dimitru** [comment]
Hello everyone,

Should we step forward with a PR?

**Comment by hwillson** [comment]
We'd definitely review a PR for this @dr-dimitru - thanks!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
