### ISSUE TITLE
Custom Babel presets conflicting with Meteor Babel presets

### ISSUE THREAD

**Issue by hwillson** [meteor/guide#690]
We should add a note somewhere in the Guide that discusses Meteor's use of Babel presets, mentioning to be careful when adding custom presets that are already used by Meteor. See https://github.com/meteor/meteor/issues/9571#issuecomment-360223847 for the full details.

**Comment by toinevk** [comment]
How about under Build -> JavaScript transpilation -> Babel ? Happy to submit a PR.

**Comment by guilhermedecampo** [comment]
That would be great guys. 
Spend some time to realize some errors after updating to 1.6.1 because of custom babel presets conflicting with Meteor ones.

Best!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
