### ISSUE TITLE
Swap practicalmeteor:mocha for meteortesting:mocha

### ISSUE THREAD

**Issue by coagmano** [meteor/guide#691]
1.6.1 release notes recommend swapping `practicalmeteor:mocha` for `meteortesting:mocha`, but the guide has many references to `practicalmeteor:mocha` throughout

Not sure how much work is involved in switching, but the guide shouldn't refer to a package with known issues on 1.6.1

**Comment by abernix** [comment]
I think they are almost entirely interchangeable.  Could you report back with your findings and submit a PR to make the swap if you find this to be true?

**Comment by toinevk** [comment]
I have actioned this and its ready for review.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
