### ISSUE TITLE
Suggestion for documentation guide

### ISSUE THREAD

**Issue by maasha** [meteor/guide#703]
How about a guide on documentation of code to augment the Style guide? JSDoc or ESDoc is highly useful for auto generated API and to track documentation coverage.

**Comment by abernix** [comment]
Could you clarify what you're talking about?  We already use JSDoc to generate all the API documentation for https://docs.meteor.com, but the Guide doesn't have any direct links to the Meteor codebase.

**Comment by maasha** [comment]
So how can I myself use JSDoc/ESDoc to generate API documentation? And ESDoc have a very nifty reporting tool to illustrate documentation coverage.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
