### ISSUE TITLE
xolvio:cleaner no longer works

### ISSUE THREAD

**Issue by hwillson** [meteor/guide#705]
Reference: https://github.com/meteor/meteor/issues/9630

Seems like `xolvio:cleaner` has been abandoned, so we should probably consider removing it from the Guide (unless of course someone in the community steps forward with a patched and newly maintained version).

**Comment by lgandecki** [comment]
@hwillson please see https://github.com/meteor/meteor/issues/9630

**Comment by hwillson** [comment]
Awesome - glad to hear it @lgandecki! Closing this off - and thanks!
