### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by queso** [meteor/guide#71]
I propose we have an article in the guide that covers all the different ways that you can debug Meteor. I know some of this may seem obvious like putting a breakpoint into Chrome, but we target both experienced and new developers and should help them get up to speed. Also coming to Javascript from X language may be a bit of a shocker to people since they may have experience programming, just not in JS.

I propose we talk about:
1. Using the `debugger` keyword
2. Using client side consoles in browsers like Chrome and Safari
3. Starting up with `meteor --debug` to do node debugging
4. Using `meteor shell`

Optional parts of the article would include:
1. Debugging a running iOS simulator or device using Safari
2. Debugging an android device using Chrome
3. Using Kadira debug (pretty sure it is free)
4. Using Chrome profilers

**Comment by queso** [comment]
@stubailo let me know what you think of this topic.

**Comment by stubailo** [comment]
I think we were going to distribute these among other guides, but perhaps like testing, this deserves its own article. What do you think, @tmeasday? I don't know where else we could put stuff like `meteor debug`, `meteor shell`, etc.

**Comment by tmeasday** [comment]
I could get behind an article

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
