### ISSUE TITLE
www.discovermeteor.com links result in cert warning

### ISSUE THREAD

**Issue by weltan** [meteor/guide#712]
**Issue**
[The Meteor Guide security page](https://github.com/meteor/guide/blob/master/content/security.md) has a [couple](https://www.discovermeteor.com/blog/allow-deny-security-challenge/) [links](https://www.discovermeteor.com/blog/allow-deny-challenge-results/) to blog posts on the Discover Meteor blog that have an expired SSL cert and thus result in a cert warning. The cert has been expired since Sept 25, 2017. 

A cursory google search seems to indicate that these blog posts weren't re-published somewhere else. 

**Suggested Fix**
I don't know if you have control over the discovermeteor.com domain, but if you do, would be great for the cert to be updated...Looks like their site has some good SEO, but is totally down because the cert is expired?

**Comment by hwillson** [comment]
Ping @SachaG.

**Comment by abernix** [comment]
Thanks for bringing this up.  There is indeed some great content on discovermeteor.com!  We don't have control over the site, but I've reached out to the owners to see about getting that resolved.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
