### ISSUE TITLE
Build a `cursor-utils` package that allows "slicing" cursors

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#73]
Does anyone out there know of something like this?

What it should do is something like:

```js
// returns a new cursor that does the "intersection" between `cursor` and `query` and `options`
CursorUtils.find(cursor, query, options)

// as above but findOne
CursorUtils.findOne(cursor, query, options)
```

The only real complexity is that it needs to work on client and server.

**Comment by tmeasday** [comment]
Investigate cursor to collection?

**Comment by tmeasday** [comment]
https://github.com/tmeasday/cursor-utils

**Comment by stubailo** [comment]
@tmeasday move to `meteor/cursor-utils`? Also, I feel like the word `utils` in the title is a cop-out. Maybe `filter-cursor`?

**Comment by tmeasday** [comment]
Should we make this a `mdg:` package? I'm kind of hoping someone else will want to take over maintaining it.. perhaps even publish it under their name...

Agreed about `cursor-utils`. Maybe it should just be `cursor`? `Cursor.find(c, ...)` works well?

**Comment by tmeasday** [comment]
I guess we aren't doing this for real? Do we close this issue or come back to it later?
