### ISSUE TITLE
Using React Router with Accounts

### ISSUE THREAD

**Issue by lorensr** [meteor/guide#753]
From https://github.com/meteor/guide/pull/625#issuecomment-370188043

> Second problem is that in the guide I can't really find how to properly use React-router with the accounts system. It probably would be a big help for everyone if there was a clear example or maybe a next step in the Todo App with React explaining it.
Also you can't use AppContainer in the same way as in FlowRouter. Because in the above example AppContainer wont be like a 'layout' component.

> I found a couple of authentication examples online: The Meteor Chef and one on StackOverflow but the one from StackOverflow uses onEnter and that's not React-router v4 but v3. There are more examples but they're using older version of react-router.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
