### ISSUE TITLE
Smart components versus subs-cache

### ISSUE THREAD

**Issue by janat08** [meteor/guide#754]
I imagine one of the reasons for subscribing and passing data in the same place is to avoid compounding publications that between different templates are not batched.

Would using https://github.com/ccorcos/meteor-subs-cache that improves a lot on kadiras sub manager make a valid use case for self-contained templates and thus more reusable.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
