### ISSUE TITLE
Explain various forms of equality in reactive vars

### ISSUE THREAD

**Issue by mitar** [meteor/guide#79]
More or less explain for Blaze, and as a general guideline to think about that when creating reactive variables and pros and cons (current approach is very conservative, but it is assured to be correct, if you now you can use EJSON.equals, you can use that, but it is slower, if you have immutable objects you can use referential equality).

Solution to this is, in cases where you cannot control reactive variable equality (like in data contexts) is to use things like [computed field](https://github.com/peerlibrary/meteor-computed-field) (which was made exactly for this reason to encapsulate a common pattern I was using: creating a reactive variable with wanted equality and then have an autorun which is copying the value from the other reactive variable to mine, knowing that mine will consolidate changes.

See:
* https://github.com/meteor/meteor/issues/4073
* https://github.com/meteor/meteor/issues/3966
* https://github.com/peerlibrary/meteor-blaze-components/issues/49

**Comment by stubailo** [comment]
Seems like this would go in a tracker guide if we had one.

**Comment by tmeasday** [comment]
Let's put this in #234 maybe
