### ISSUE TITLE
Collate testing packages

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#80]
We need to get the best packages for various patterns in testing Meteor apps:

 - [ ] Stubbing everything
 - [ ] Stubbing methods
 - [ ] Stubbing publications
 - [ ] Collecting data from publications (testing pubs)
 - [ ] Interspersing client/side assertions
 - [ ] Rendering Blaze templates in isolation
 - [ ] More..

**Comment by Sanjo** [comment]
* Stubbing everything: https://github.com/meteor-velocity/meteor-stubs. I prefer to stub selectively and run tests in the app context.
* Stubbing methods: https://github.com/meteor/meteor/pull/5561
* Stubbing publications: Haven't thought about this yet.
* Interspersing client/side assertions: What does that mean?
* Rendering Blaze templates in isolation: Use client unit mode of sanjo:jasmine. It uses the Karma Test Runner and will run the tests in a browser. The whole client side app context gets loaded. In your tests you use Blaze.renderWithData and Blaze.remove.

**Comment by tmeasday** [comment]
Hey @Sanjo, thanks for this. 

Re:

  1. Stubbing everything -- I'm still trying to understand exactly how meteor-stubs is intended to be used. Does it just make everything a noop, and then it's your responsibility to stub the things again that you want to "work"?

  e.g. does it make `Meteor.userId()` just return `null`, and if you want to make it return something, you stub it again?

  2. Interspersing client/server assertions - What I mean is a way to in a single test switch contexts between client and server to test that stuff is happening on both sides of the stack:
   - So @mitar mentioned one way to do it here: https://github.com/meteor/guide/issues/20#issuecomment-151315215
   - Also, I think Gargarin[https://github.com/anticoders/gagarin] seems pretty cool for this.
   - I'm wondering what Velocity offers in this direction

3. Rendering Blaze templates: yeah so there's some boilerplate of @cmather's that I copy around for this that looks like: https://github.com/meteor/todos/blob/master/packages/lists-show/lists-show-tests.js#L7-L24. I'm wondering if there's a package out there that does this?

**Comment by Sanjo** [comment]
Re: Stubbing everything: Like you said. This comes from the beginning of Velocity where we had a package that ran unit tests outside of a Meteor app context. As I said, I don't use it to write my tests.

Re: Interspersing client/server assertions: We currently don't have it in any Velocity testing framework. I like how Gargarin does it. I think this technique should be extracted into a separate package, so everyone can use it.

Re: Rendering Blaze templates: Here is some thinking on how to provide a better API for Blaze template testing: https://github.com/meteor-velocity/velocity-helpers/issues/4. Could be implemented in Meteor in the same way as my Meteor.stubMethods pull-request.

**Comment by tmeasday** [comment]
That's helpful, thanks @sanjo

**Comment by samhatoum** [comment]
Chimp now supports Interspersing client/server assertions and can do so using both Mocha and Cucumber. We created a separate package to do the interspersing it's called [backdoor](https://github.com/xolvio/meteor-backdoor).

execute on server
```javascript
var getMeteorSettings = function(setting) {
  return Meteor.settings[setting]; // runs on the server
};
var result = server.execute(getMeteorSettings, 'mySetting');
console.log(result); // in the test context
```

execute on the client
```javascript
var userProfileProperty = function(property) {
  return Meteor.user().profile[property]; // runs on the client
};
var result = client.execute(getMeteorSettings, 'mySetting');
console.log(result); // in the test context
```

Of course you can do this for pub/subs, methods and such
