### ISSUE TITLE
Update all react router (and associated) code samples

### ISSUE THREAD

**Issue by hwillson** [meteor/guide#800]
PR https://github.com/meteor/todos/pull/261 updates the `react` branch of `todos` to use `react-router` 4 (and adjusts the codebase to follow the `react-router` 4 way of thinking). Once that PR is merged, we'll need to update the `react-router` code samples in the Guide to match `todos`.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
