### ISSUE TITLE
React

### ISSUE THREAD

**Issue by sys13** [meteor/guide#83]
Would love an article about React, or React versions of the other articles.

Switching over to React has had some of its own issues, mostly around forms though I'm now using formsy-react with formsy-react-material-ui - bugs and all. Don't have it integrated with simple-schema :(

There is currently http://react-in-meteor.readthedocs.org but it doesn't cover all that nice stuff in the guide.

**Comment by stubailo** [comment]
Right now, it's not 100% clear what the best practices are for a lot of these things in React. As we figure it out, it would be good to have a guide article for it as well, just like we have for Blaze.

Also, as we are thinking about the patterns in the guide, we should also be thinking about how they would work with React.

**Comment by dburles** [comment]
+1 the biggest unknown for me has been related to the ongoing discussion here https://github.com/meteor/react-packages/issues/19

@sys13 I did come up with a decent react mixin for SS, though it's a work in progress and not public..

**Comment by yyx990803** [comment]
Feedback welcome on the outline: https://github.com/meteor/guide/pull/218
