### ISSUE TITLE
A list of meteor URLs needed to be added for a corporate proxy whitelist

### ISSUE THREAD

**Issue by michaeljquinn** [meteor/guide#837]
While there is lots of discussion around how to set the appropriate variables to enable meteor to 
work via a corporate proxy (i.e. HTTP_PROXY, http_proxy, npm config etc...), there appears to be 
a dearth of information of what URLS to put into a proxy configuration whitelist (e.g squid config)

There are 2 aspects to this
1 - We really need a default whitelist of URLs that we can add to a proxy configuration
2 - some way (e.g when we do a meteor start or meteor build) of resolving the requests for a package 
into the ACTUAL URL being accessed to do the download.  eg packages.meteor, or atmospherejs etc....
A simple command line arg or "debug" mode would be nice for us to be able to trace those failing URLS (the connection error - 403 etc...) to allow us to quickly compile the whitelist and submit it to the corporate proxy demi gods 

thanks

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
