### ISSUE TITLE
Testing ES2015 modules and app code

### ISSUE THREAD

**Issue by Sanjo** [meteor/guide#85]
The next release of Meteor will support ES2015 modules. This implies to me that you can modularize your app without the overhead of the Meteor package package.js. Therefore it seems shortsighted to me if the Meteor Guide wouldn't cover testing ES2015 modules and app code in the outline.

**Comment by stubailo** [comment]
I think it won't be all that different. Right now, you unit test code by testing individual packages, in the new world it will be individual modules. It seems to me that the only difference is the way you define the module, and I'll be happy to get rid of package.js everywhere.

If we do this right, then transitioning to modules will be pretty easy, and will mostly just involve getting rid of a lot of places where we needed to define `package.js` files.

> Meteor Guide wouldn't cover testing ES2015 modules

This will always have to be a living document, so this can be a good exercise in how hard it will be to update the guide for the new release. I think the best case scenario is where we work with @benjamn to update the guide and then release it at the same time as Meteor 1.3, depending on how the release schedule works out.

**Comment by tmeasday** [comment]
I do still think it's an open question on how you test a random ES2015 module in from your app in say mocha. But it's a hard question to answer until @benjamn's come a little further down the road with it.

**Comment by rjakobsson** [comment]
Do you have any more clues on this at the moment?

**Comment by stubailo** [comment]
There's a detailed answer by Tom here: https://forums.meteor.com/t/the-state-of-velocity-and-testing-in-meteor/15084/50?u=sashko
