### ISSUE TITLE
Microservices

### ISSUE THREAD

**Issue by zimt28** [meteor/guide#86]
I've searched this project but couldn't find anything about microservices. I think @debergalis wrote that there'd be some information, but this line has been removed from the blogpost .. Anyway, microservices seem to be a great thing and they would be a good topic for the meteor guide :)

**Comment by stubailo** [comment]
There's a bit of a mention here: https://github.com/meteor/guide/blob/master/outlines/structure.md

I think the idea is that at some point your project gets too big to be one "app" - you might want to split out some code into a second app to have a separate UI, independently scaled services, etc.

Is there something in particular that you are looking for about microservices?

**Comment by rhyslbw** [comment]
Maybe this could include a list of tools grouped into microservice concepts, with a sentence or two explaining how they are commonly used to help with distributing the system. There's also a few key things like authentication, from client or other server, that could also be addressed.

## Native DDP
https://bulletproofmeteor.com/architecture/microservices-with-meteor-and-ddp

## Long running or resource intensive units of work
https://github.com/vsivsi/meteor-job-collection

## Service management
https://github.com/meteorhacks/cluster#microservices

## Distributed messaging
https://github.com/meteor-space/event-sourcing
_The Commit Store is now also the messaging queue, so you can make event subscriptions in other connected services with support for multiple instances to be running. A collection observer triggers a findAndModify on the queue to mark it as received by the service, publishes the event in the current process's, then marks it as published for that service. The last step here is to allow for automatic failure handling_

**Comment by tmeasday** [comment]
There's some stuff about this here: http://guide.meteor.com/structure.html#splitting-your-app

Would take a PR with a bit more detail... but I'll close this as it's a bit old now, feel free to reopen.
