### ISSUE TITLE
When and what is the best practice to group your app in modules (packages)?

### ISSUE THREAD

**Issue by rodrigocprates** [meteor/guide#87]
Reading on the web, is not too easy to find a good approach on how is the best way to separate your functionalities/modules in packages and when you should do that.

**Comment by stubailo** [comment]
There will be two parts of the guide that will be helpful for this:

1. The application structure guide suggests that a "medium-sized" application should be entirely composed of packages (and will switch to ES2015 modules when Meteor 1.3 supports them) https://github.com/meteor/guide/blob/master/outlines/structure.md
2. We're also working on an example app here: https://github.com/meteor/todos The app is still a work in progress, but you can see we're putting all of the functionality in packages.
