### ISSUE TITLE
Version solving

### ISSUE THREAD

**Issue by ffxsam** [meteor/guide#88]
I'd love to see an authoritative section in the guide detailing how the heck version solving works. I've posted about this on the forum before, and I've pointed out inconsistencies from what the official documentation states. Though of course, the documentation should probably be updated as well.

For reference: https://forums.meteor.com/t/package-version-numbers-highly-confusing/8340

**Comment by stubailo** [comment]
Way ahead of you. It's in the outline: https://github.com/meteor/guide/blob/master/outlines/packages.md

Here's a rough draft (although this will be completely rewritten): https://github.com/meteor/guide/blob/master/content/packages.md#semantic-versioning-and-version-constraints

**Comment by stubailo** [comment]
Is there some stuff in particular that would be helpful to cover?
