### ISSUE TITLE
Add testing with Cypress to the guide

### ISSUE THREAD

**Issue by mitar** [meteor/guide#888]
I just tried it out and I am really impressed. Pretty easy integration with Meteor for acceptance testing. I have tried to use chimp before as described in the guide, but Cypress is really nice.

**Comment by chris-visser** [comment]
Hey. Are you able to make a PR for the guide about this?

**Comment by mitar** [comment]
Sorry, don't have time at the moment. But [you can check out my app here to see how I did it](https://github.com/peer/doc).

**Comment by floo51** [comment]
Maybe late to the party, but I wrote [a tutorial](https://marmelab.com/blog/2019/02/28/cypress-on-meteor.html) on how to setup cypress with meteor. Might be useful to some of you 🙂

**Comment by mitar** [comment]
I have also some useful Percy commands to run Meteor methods and to reset database here: https://github.com/peer/doc/blob/devel/tests/cypress/support/commands.js

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
