### ISSUE TITLE
Documentation error in the Meteor guide Method section.

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/guide#890]
The documentation of the meteor guide says that if an exception is thrown inside the stub of a method, that stub get's stopped but the server side method is still called. This is not the case in Meteor, the server side method is never called.

See:
https://guide.meteor.com/methods.html#call-lifecycle

> If an exception is thrown from the Method simulation, then by default Meteor ignores it and continues to step (2). 

Step (2) being sending the DDP request which in reality is never sent.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
