### ISSUE TITLE
Blank screen issue on android mobile with meteor version 1.7

### ISSUE THREAD

**Issue by dcpliot** [meteor/guide#891]
I created simple login project using meteor version 1.7 with basic packages,and I deployed the code into galaxy server.Then finally,I built an app and installed on mobile.But whenever I open it,I will get login page for 2 seconds,then irrespective of performing user actions on it,the screen suddenly goes of for a second and comes back.This happens exactly  twice ,sometimes if screen goes means it will show only blank screen and will not be settled to login page.These below are the npm and atmosphere  packages I am using currently:
NPM packages are as follows:
  "dependencies": {
    "@babel/runtime": "7.0.0-beta.55",
    "bufferutil": "^4.0.0",
    "emitter": "0.0.5",
    "jquery": "^2.2.4",
    "meteor-node-stubs": "^0.4.1",
    "utf-8-validate": "^5.0.1"
  },
Atmosphere packages are as follows:
meteor-base@1.4.0           
mobile-experience@1.0.5   
mongo@1.5.0             
blaze-html-templates@1.0.4 
reactive-var@1.0.11            
tracker@1.2.0               
standard-minifier-css@1.4.1   
standard-minifier-js@2.3.4  
es5-shim@4.8.0               
ecmascript@0.11.1              
shell-server@0.3.1          
browser-policy
underscore
iron:router

**Comment by lorensr** [comment]
I'd recommend StackOverflow, or an issue on [meteor/meteor](https://github.com/meteor/meteor/issues) if you can provide a small reproduction.
