### ISSUE TITLE
Roles & Permissions

### ISSUE THREAD

**Issue by SachaG** [meteor/guide#93]
Has there been any discussion on how to deal with roles and permissions? i.e. which users can edit which documents, or which fields on these documents?

In Telescope I control this through the schema (see [video](https://www.youtube.com/watch?v=545QZXHinbY)). For example:

```js
  url: {
    type: String,
    optional: true,
    editableBy: ["member", "admin"]
  },
```

Means that the document is editable either by a regular user (provided they own the document), or by an admin. I don't use the roles package because it seems overkill for what I need, but it would probably work just as well with it. 

Just wondering if that pattern can be useful, or else how other people deal with that kind of permissions checking?

**Comment by brylie** [comment]
It would also be useful to cover ownership permissions. E.g. When a document or certain fields should be editable only by the original creator. We also have a use case where the original creator wants to invite/allow other specific users to edit - where collaborator user IDs can be stored in an array.

**Comment by brylie** [comment]
@tmeasday why is this issue being closed? Please provide an update/reason, so that we understand the resolution of this issue.

**Comment by stubailo** [comment]
Oh, we just noticed there is already a roles and permissions section in the users and accounts article. If you have ideas for how to improve it, we could reopen with a new title.
